### ISSUE TITLE
Jep invoke only supports methods in the globals dictionary

### ISSUE THREAD

**Issue by xsank** [ninia/jep#100]
- OS Platform, Distribution, and Version: windows7，both python and jep.jar are 3.7.0
- Python Distribution and Version: 2.7.10
- Java Distribution and Version: 1.8

python file:
``` python
def cal(x,y):
    return x+y
```

|call|result|
|---|---|
|jep.invoke("add.cal", x,y)|error|
|jep.getValue("add.cal(x,y)")|success|
|jep.eval("tmp=add.cal(x,y)")|success|

ps:x,y should be replaced by 1,2,3...

error detail:
``` java
Exception in thread "main" jep.JepException: Object was not found in the global dictionary.
	at jep.Jep.invoke(Native Method)
	at jep.Jep.invoke(Jep.java:531)
	at com.demo.test.Main.main(Main.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
```

**Comment by xsank** [comment]
I know the problem,  you have to call the method `createModule` before use the `invoke` method,  so that the `jepThread->globals` will record these.
But the `createModule` and `invoke` methods have some bugs, maybe your should check this carefully.

**Comment by bsteffensmeier** [comment]
As mentioned in the [javadoc for invoke](https://github.com/ninia/jep/blob/v3.7.0/src/jep/Jep.java#L515), the name passed to invoke must be the name of a global variable. In this case "add" is the name of a global variable and "cal" is the name of an attribute on that object. "add.cal" is not the name of a global variable so it does not work, this is the expected behavior. The alternatives you suggested are acceptable, if you prefer invoke then you would need to use an eval to get the function into a global variable like this:

```
jep.eval("tmp = add.cal")
jep.invoke("tmp", x, y)
jep.eval("tmp = None")
```

**Comment by xsank** [comment]
@bsteffensmeier 
i read the wiki as follows first:  
```
try(Jep jep = new Jep(false)) {
    jep.eval("import somePyModule");

    jep.setValue("arg", obj);
    jep.eval("x = somePyModule.foo1(arg)");
    Object result1 = jep.getValue("x");

    Object result2 = jep.getValue("somePyModule.foo2()");

    Object result3 = jep.invoke("somePyModule.foo3", obj); // maybe should be fixed

   jep.runScript("path/To/Script");
}
```  
so, i thought it should works...   

now it works ,thank you for your help.

**Comment by djbarker** [comment]
Is there a technical reason that `invoke` can only use global variables? 
I've also run against this. To get around it I just do `from foo.bar import *` so that they're in the global scope.

**Comment by bsteffensmeier** [comment]
Currently to access the PyObject to invoke it is just a dict lookup on the globals dict. Doing anything else would require additional processing, the most practical way to do that would be to simply eval the statement that is passed to invoke. That makes me nervous from a performance perspective, particularly for the simple case where it is just a global object, I would be hesitant to add the eval if it is going to noticeably slow down everyone currently using invoke.

I have not looked deep enough to see if my performance concerns are legitimate or completely premature. I'm sure python eval is very optimized and the performance change might be negligible compared to all the other back and forth we are doing with JNI. Currently this is not a high priority for me to investigate, but I am open to a pull request if anyone else has some time to look into it. 

@djbarker I appreciate the extra feedback. There are many little oddities in jep and I don't  have time  to look into everything so it helps to hear from people using jep to know what changes would have the greatest impact. I'm going to reopen this issue and I'll try to investigate more eventually if no one else gets to it first.

**Comment by djbarker** [comment]
Thanks. I guess an implementation would be searching nested dicts based on splitting the invoke target's name by `'.'`? 
The obvious benefit of `invoke` over `eval` is that one can pass in Java objects as function arguments.

**Comment by SemanticBeeng** [comment]
Should this work?

**Comment by bsteffensmeier** [comment]
@SemanticBeeng dataLayerModule is part of the globals dictionary, however dataLayerModule.connect is not so that will not work.

**Comment by SemanticBeeng** [comment]
So `jep.invoke` can never be used to call methods of objects or classes (`staticmethod`) but only top level functions - is this a correct inference?

**Comment by bsteffensmeier** [comment]
@SemanticBeeng I apologize if this is overly pedantic but I want to be accurate. I'm not sure invoke is quite as black and white as you make it to be, for example the following code prints `2`
```
  public static void main(String[] args) throws JepException{
    try(Jep jep = new Jep()) {
        jep.eval("class TheClass(object):\n" +
                 "    @staticmethod\n" +
                 "    def theStaticMethod(arg):" +
                 "        return arg + 1\n");
        jep.eval("tmp = TheClass.theStaticMethod");
        Object result = jep.invoke("tmp", 1);
        System.out.println(result);
    }
  }
```
Technically `tmp` is still a staticmethod, and I wouldn't consider it to be a "top level function", technically you can `invoke()` any callable python obect. However for things like methods of objects or `staticmethod` most people are used to accessing it with the `.` notation and calling it all in one statement and that doesn't currently work in `invoke()`.

I don't understand what you are saying about the dataLayerModule. I don't think it particularly matters to jep how you import a module. A workaround mentioned earlier in this thread is to just import the attributes from the module, so for your example something like this might let you invoke `connect()` easier:

```
jep.eval("from modules.data_layer import connect");
jep.invoke("connect", somePlace);
```

**Comment by SemanticBeeng** [comment]
> _"r for things like methods of objects or staticmethod most people are used to accessing it with the . notation and calling it all in one statement and that doesn't currently work in invoke()."_

Thank you for the detailed clarification and the exact code example that works, Ben.

**Comment by bsteffensmeier** [comment]
I pushed a118695 to the dev_3.8 branch which will allow methods to be called using invoke and should resolve this issue. I would appreciate it if anyone interested in this feature would check out that branch and try it to ensure it is working as expected before the official release.

**Comment by SemanticBeeng** [comment]
Reviewed and looks good.

> _"a Python function name in globals dict *or the name of a global object and method using dot notation*."_

https://github.com/ninia/jep/blob/a1186954b9cbc2f2718a3d073500dc8f8f1b8d21/src/main/java/jep/Jep.java#L356-L357

**Comment by SemanticBeeng** [comment]
In same context, a great application would be to stream `apache arrow` data through `jep`.

See http://wesmckinney.com/blog/arrow-streaming-columnar/.
As you can see in the code below, in order to achieve incrementality, a "reference" mechanism is necessary.

```
import time
import numpy as np
import pandas as pd
import pyarrow as pa

def generate_data(total_size, ncols):
    nrows = total_size / ncols / np.dtype('float64').itemsize
    return pd.DataFrame({
        'c' + str(i): np.random.randn(nrows)
        for i in range(ncols)
    })

KILOBYTE = 1 << 10
MEGABYTE = KILOBYTE * KILOBYTE
DATA_SIZE = 1024 * MEGABYTE
NCOLS = 16

def get_timing(f, niter):
    start = time.clock_gettime(time.CLOCK_REALTIME)
    for i in range(niter):
        f()
    return (time.clock_gettime(time.CLOCK_REALTIME) - start) / NITER

def read_as_dataframe(klass, source):
    reader = klass(source)
    table = reader.read_all()
    return table.to_pandas()
NITER = 5
results = []

CHUNKSIZES = [16 * KILOBYTE, 64 * KILOBYTE, 256 * KILOBYTE, MEGABYTE, 16 * MEGABYTE]

for chunksize in CHUNKSIZES:
    nchunks = DATA_SIZE // chunksize
    batch = pa.RecordBatch.from_pandas(generate_data(chunksize, NCOLS))

    sink = pa.InMemoryOutputStream()
    stream_writer = pa.StreamWriter(sink, batch.schema)

    for i in range(nchunks):
        stream_writer.write_batch(batch)

    source = sink.get_result()

    elapsed = get_timing(lambda: read_as_dataframe(pa.StreamReader, source), NITER)

    result = (chunksize, elapsed)
    print(result)
    results.append(result)
```

**Comment by ndjensen** [comment]
Functionality added to invoke on methods on instances in Jep 3.8.
