### ISSUE TITLE
Only single thread could call the invoke method at the same time, otherwise the jvm would crash.

### ISSUE THREAD

**Issue by xsank** [ninia/jep#101]
- OS Platform, Distribution, and Version: windows7 , jep 3.7.0
- Python Distribution and Version: 2.7.10
- Java Distribution and Version: 1.8 

RT

**Comment by bsteffensmeier** [comment]
Can you provide an example. I tried this and I didn't have any problems:

```java
import jep.Jep;
import jep.JepException;

public class Test{

    private static int THREAD_COUNT = 32;

    private static int LOOP_COUNT = 1000;

    private static void invokeAlot(){
        try(Jep jep = new Jep(false)) {
            jep.eval("import time");
            StringBuilder function = new StringBuilder();
            function.append("def f(a):\n");
            // Sleep to make sure we stay in the invoke awhile
            function.append("  time.sleep(0.2)\n");
            function.append("  return a + 1\n");
            jep.eval(function.toString());
            Integer arg = 0;
            for(int i = 0 ; i < LOOP_COUNT ; i += 1){
                arg = (Integer) jep.invoke("f", arg);
            }
            // Just to make sure it did what I planned.
            System.out.println(arg.intValue() == LOOP_COUNT);
        }catch(JepException e){
            e.printStackTrace();
        }
    }

    public static void main(String[] args) throws InterruptedException{
        Thread[] t = new Thread[THREAD_COUNT];
        for(int i = 0 ; i < THREAD_COUNT ; i += 1){
            t[i] = new Thread(Test::invokeAlot);
            t[i].start();
        }
        for(int i = 0 ; i < THREAD_COUNT ; i += 1){
            t[i].join();
        }
    }

}
```

**Comment by xsank** [comment]
Each thread have a single Jep object in your test.  You know, the jeb object with a sub-interpreter cost a lot.  
It will be good fi the sub-interpreter could be reused.  
If you use multi-thead to call the invoke, it will crash immediatlly.  
I know the Jep will bind the current thread, and the method such as: eval(),  getValue(),  runScript()... should use the bind thread. But the invoke method do not have that limit. I thought if i use multi-thread will be more efficient.

**Comment by ndjensen** [comment]
It's not possible to reuse a Jep interpreter from a different thread.  See this page: https://github.com/ninia/jep/wiki/How-Jep-Works#threading-complications

It's a mistake in Jep's code that it did not throw an exception in invoke(...) when you used a different thread to access the same Jep instance.  I will correct that mistake so it will throw an exception in the future.

**Comment by ndjensen** [comment]
https://github.com/ninia/jep/commit/5485619a76c20d74c1d493798a9fa06997a3e334 will block the Jep instance's invoke(...) methods from being used from another thread.
