### ISSUE TITLE
Unable to import my local python modules in the script directory by default in Jep

### ISSUE THREAD

**Issue by rvshettigar** [ninia/jep#109]
I am trying to run a python script within Jep which uses a local python module.
However, when trying to run it using Jep, I get an ImportError. This runs fine if I try to execute the script directly.
```
[error] Exception in thread "main" jep.JepException: <type 'exceptions.ImportError'>: No module named data
[error] 	at app/python/model_serving.<module>(model_serving.py:14)
[error] 	at jep.Jep.run(Native Method)
[error] 	at jep.Jep.runScript(Jep.java:506)
[error] 	at jep.Jep.runScript(Jep.java:482)

```

Please let me know if I am missing something here.

Update:
I was able to import my local module by including the path in the JepConfig.
I was wondering if it would it be possible to add include path of the script's directory by default.

**Comment by bsteffensmeier** [comment]
When we set up the include path we do not know what script you will be running so I don't see how we could add it by default.

**Comment by bsteffensmeier** [comment]
I'm closing this because it is inactive and has no clear way to move forward.
