### ISSUE TITLE
How can I choose python version to run with jep?

### ISSUE THREAD

**Issue by akapit** [ninia/jep#112]
- OS Platform, Distribution, and Version: macOS Sierra 10.13.2
- Python Distribution and Version: 3.6.3 (and 2.7.1)
- Java Distribution and Version: Java 8

There is any way I can choose which python version to run with Jep?
It's taking the 2.7* by default and I need to run with the 3.6 version.

I also saw that jep DYLD_LIBRARY_PATH is being installed in /usr/local/lib/python2.7/site-packages/jep, but not in the 3.6 one.

Any hint?

Thanks!

**Comment by ndjensen** [comment]
From @bsteffensmeier on the mailing list:

> It should just be a matter of ensuring you use the right python version when running setup.py. Since python2 is the default python on most systems simply running setup.py without specifying anything will install in python2, however if you run python3 explicitly it should install in python3.

> python3 setup.py install

> Similarly if you are using pip, you may need to run pip3 instead of just pip since pip is frequently defaulted to python2. If you want to use a custom python or one that is not on the PATH then you can usually get it working by just specifying the full path to the python executable.

**Comment by bsteffensmeier** [comment]
Im assuming the response resolved any confusion and closing this.
