### ISSUE TITLE
Unable to build jep. Getting error: ‘Py_HashRandomizationFlag’ undeclared (first use in this function)

### ISSUE THREAD

**Issue by sumeetmi2** [ninia/jep#114]
- OS Platform, Distribution, and Version: Centos6
- Python Distribution and Version: python2.7
- Java Distribution and Version: java1.7

i was trying to build jep project on centos and i get the following error while building. I have already installed numpy.

```
src/jep/pyembed.c: In function ‘pyembed_preinit’:
src/jep/pyembed.c:212: error: ‘Py_HashRandomizationFlag’ undeclared (first use in this function)
src/jep/pyembed.c:212: error: (Each undeclared identifier is reported only once
src/jep/pyembed.c:212: error: for each function it appears in.)
error: command 'gcc' failed with exit status 1
```

**Comment by bsteffensmeier** [comment]
There is nothing special about Py_HashRandomizationFlag, that would cause that particular symbol to go missing if other python symbols are avaialble. I can explain how that symbol is defined, and perhaps that will help you find the problem with your setup:

1. [pyembed.c includes Jep.h](https://github.com/ninia/jep/blob/v3.7.1/src/jep/pyembed.c#L44)
2. [Jep.h includes jep_platform.h](https://github.com/ninia/jep/blob/v3.7.1/src/jep/Jep.h#L35)
3. [jep_platform.h includes Python.h](https://github.com/ninia/jep/blob/v3.7.1/src/jep/jep_platform.h#L35)
4. [Python.h includes pydebug.h](https://github.com/python/cpython/blob/2.7/Include/Python.h#L86)
5. [pydebug.h defines Py_HashRandomizationFlag](https://github.com/python/cpython/blob/2.7/Include/pydebug.h#L29)

On CentOS 6 Python.h and pydebug.h should be in /usr/include/python2.7, they are normally installed by the python-devel rpm.

**Comment by sumeetmi2** [comment]
@bsteffensmeier Thanks let me try to debug it. Thank you for your prompt reply.

**Comment by sumeetmi2** [comment]
@bsteffensmeier  actually those files are located at `/usr/local/include/python2.7/` because i installed python2.7 alongside python 2.6 on my cloudera virtualbox instance and i cant remove python2.6 as cloudera has dependency on it.

**Comment by bsteffensmeier** [comment]
You must have been using the python 2.6 to build before because 2.6 did not have Py_HashRandomizationFlag. If you use python2.7 to run setup.py it should build correctly with the python 2.7 environment. @sumeetmi2, were you able to build successfully? Since we don't support python 23.6 and that is the source of the problem I would like to close this issue/

**Comment by sumeetmi2** [comment]
I solved the problem.  It was a problem with python setup.  Thank you for the response it helped me debug properly
