### ISSUE TITLE
Python hosting scala - importing class from nested package fails 

### ISSUE THREAD

**Issue by SemanticBeeng** [ninia/jep#117]
Getting 
```
$ scala -cp $JAR:$JEP_CP jep.Run $CODE_PATH/jepp/age_group.py
jep.JepException: <class 'ImportError'>: No module named 'com'
	at python_hosting_scala/src/main/scala/com/knowscieng//jepp/age_group.<module>(age_group.py:1)
	at jep.Jep.run(Native Method)
	at jep.Jep.runScript(Jep.java:506)
```

from here 

https://github.com/SemanticBeeng/Snakes-and-Ladders/blob/master/python_hosting_scala/src/main/scala/com/knowscieng/jepp/age_group.py#L1

The original code imported a Scala class from a "simple" (not nested) package but I am trying to 

```
from com.knowscieng.jepp.scalython import *
ageGroup = ScalaUtils.ageGroupMethod(21.0)
```

Original code was 

```
from scalython import *
ageGroup = ScalaUtils.ageGroupMethod(21.0)
```

`$JAR` looks like this 

```
     0 Sun Mar 11 09:03:34 PDT 2018 com/knowscieng/jython/
  2175 Sat Mar 10 07:05:38 PST 2018 com/knowscieng/jpype/ScalaUtils$.class
  3284 Sun Mar 11 09:03:34 PDT 2018 com/knowscieng/jepp/sclaython/ScalaUtils$.class
  1208 Sat Mar 10 07:05:38 PST 2018 com/knowscieng/jpype/ScalaUtils.class
  3109 Sun Mar 11 09:03:34 PDT 2018 com/knowscieng/jepp/sclaython/ScalaUtils.class
  2916 Sun Mar 11 09:03:34 PDT 2018 com/knowscieng/jepp/sclaython/ScalaUtils$Person.class
  2125 Sun Mar 11 09:03:34 PDT 2018 com/knowscieng/jepp/sclaython/ScalaUtils$Person$.class
     0 Sun Mar 11 09:19:34 PDT 2018 com/__init__.py
     0 Sun Mar 11 09:19:40 PDT 2018 com/knowscieng/__init__.py
     0 Sun Mar 11 09:19:48 PDT 2018 com/knowscieng/jepp/__init__.py
```
Where I manually patched the `__init__.py` (empty) files hoping that this is what Python is looking for.
(as per https://stackoverflow.com/a/4116384/4032515)

Is this - nested package import - supposed to work?
Is there something special to do to make `Jep` treat nested Scala packages as Python modules?

Please advise.
UPDATE: must be my fault because this fails on my package _only_ (now not nested )

```
from java.lang import Integer
from java.util import ArrayList as AL
from sclaython import *
```
---
UPDATE/FIX: this works. 
```
java -cp $JAR:$JEP_CP:/usr/share/scala/lib/scala-library.jar jep.Run $CODE_PATH/jepp/age_group.py
```
Executing with `scala` was the issue!
What is the exact reason for this? 

Asking because may need to need use `jep` from processes started with scala and/or processes I do not control how they are started, like a `apache spark` worker.

How to make it work in this case? (some custom `java_import_hook.py,`?) 
Please provide detailed guidance.

**Comment by ndjensen** [comment]
We don't officially support Scala but I will try to help.

Jep uses the interface [ClassEnquirer](https://github.com/ninia/jep/blob/v3.7.1/src/jep/ClassEnquirer.java) to determine if an import is a Java class or a Python module.  In your case Jep thought com was a Python module otherwise it would have been a ClassNotFoundException.  The default ClassEnquirer is [ClassList](https://github.com/ninia/jep/blob/v3.7.1/src/jep/ClassList.java#L75) which includes all the classes shipped with the JVM and anything found in jars on the Java classpath.

Were your com.* classes in a jar on the Java classpath?

You can implement your own ClassEnquirer to use other techniques to determine if it's a Java class or Python module.  There's also another one provided by Jep called the [NamingConventionClassEnquirer](https://github.com/ninia/jep/blob/v3.7.1/src/jep/NamingConventionClassEnquirer.java).

**Comment by SemanticBeeng** [comment]
_"Were your com.* classes in a jar on the Java classpath?"_ - yes. the same jar was on the classpath for both invocations, with `java` and with `scala`. Worked only when the command line used `java`

This did not work:
```
 scala -cp $JAR:$JEP_CP jep.Run $CODE_PATH/jepp/age_group.py
```

This did (same binary)
```
java -cp $JAR:$JEP_CP:/usr/share/scala/lib/scala-library.jar jep.Run $CODE_PATH/jepp/age_group.py
```
So it must have to do with class loading indeed. 
I need this to work when called from `apache spark` (written in scala) so it would be good to know exactly where it fails in first case to be prepared.

**Comment by ndjensen** [comment]
Debug into ClassList.loadClassPath().  https://github.com/ninia/jep/blob/v3.7.1/src/jep/ClassList.java#L75  I'm guessing Scala is not setting the classpath correctly.

**Comment by bsteffensmeier** [comment]
@SemanticBeeng Any insight into what is going on here. We don't technically support scala so I am tempted to close this issue, however if there is something simple we can add to support scala better I think it would be worthwhile to help other scala users.

**Comment by SemanticBeeng** [comment]
`jep` and above thing work with Scala okay.
Used a custom class loader and `ClassEnquirer`  and works.
Many thanks.
