### ISSUE TITLE
Scala hosting Python - converting complex Python object to Scala and calling back

### ISSUE THREAD

**Issue by SemanticBeeng** [ninia/jep#118]
Scenario

Scala class `Main` contains object `S1` and calls script `p1.py`  which loads a `pandas` data frame and wants to set it back to `S1`.

Is this possible?
How will `p1.py` use the current Jep instance from `Main` to convert the data frame?

Please advise.

**Comment by SemanticBeeng** [comment]
A concrete example 

https://github.com/SemanticBeeng/Snakes-and-Ladders/blob/master/scala_hosting_python/src/main/scala/com/knowscieng/jepp/advanced/AdvancedPythonAndR.scala#L24

How can I return a Scala equivalent of this data frame
https://github.com/SemanticBeeng/Snakes-and-Ladders/blob/master/scala_hosting_python/src/main/scala/com/knowscieng/jepp/advanced/ts_test.py#L13

or of this `rpy2.robjects.vectors.FloatVector`
https://github.com/SemanticBeeng/Snakes-and-Ladders/blob/master/scala_hosting_python/src/main/scala/com/knowscieng/jepp/advanced/ts_test.py#L70

Is there a way to define custom converters?

**Comment by ndjensen** [comment]
> How can I return a Scala equivalent of this data frame

The only way in the current version of Jep would be to make a Scala/Java object, import it and instantiate it in Python, and then set it up by invoking Scala/Java methods on it.  When getting a value out of Python, Jep will turn it into a String of the object if all its built-in conversion methods fail.  That is issue #43.

> Is there a way to return a reference only (to the data frame) that Python would recognize if I sent it back from Scala in a subsequent call?

In the current version of Jep, no.

> Is there a way to define custom converters?

At present only if you do as I state above and have a Scala/Java object and write your own conversion code in Python.

Ideally we would return a pointer to a Python object that provides some features and could be passed back into Python.  I have an experimental branch on my fork that supports that.  https://github.com/ndjensen/jep/tree/dev_4.0/src/main/java/jep/python  You might play with that and provide feedback if you think it should make it into Jep.

**Comment by SemanticBeeng** [comment]
Thanks, will study to understand better.

Please have a look at `ScalaPy` : seems it does some things that should be part of core.

https://github.com/shadaj/scalapy/blob/master/src/main/scala/me/shadaj/scalapy/py/Ref.scala#L7
and cool application to wrap `NumPy` and `Tensorflow`

https://github.com/shadaj/scalapy-tensorflow/blob/master/src/test/scala/me/shadaj/scalapy/tensorflow/Example.scala#L25

I am curious how this compares to the new features in the 4.0 branch.

**Comment by SemanticBeeng** [comment]
_"write your own conversion code in Python."_ - care to share an example if a complex conversion?

**Comment by ndjensen** [comment]
A simplistic example that is a bit out of date: https://github.com/Unidata/awips2-core/blob/unidata_17.1.1/common/com.raytheon.uf.common.python/utility/common_static/base/python/JUtil.py#L138

Regarding scalapy, we accept pull requests of solid code, if you contribute good code it will be included sooner rather than later.  Otherwise I don't know when we'll get to some features.

**Comment by SemanticBeeng** [comment]
_"We don't officially support Scala but I will try to help."_ from https://github.com/ninia/jep/issues/117#issuecomment-372428331

_"Regarding scalapy, we accept pull requests of solid code"_ - so would you start to accept Scala pull requests if you find the mechanisms it introduces as useful and worthy of being in "core"?

@shadaj : would you be interested to contribute these key wrapping/referencing/facading techniques to `Jep`?
https://github.com/shadaj/scalapy/blob/master/src/main/scala/me/shadaj/scalapy/py/Ref.scala#L7
https://github.com/shadaj/scalapy/blob/master/src/main/scala/me/shadaj/scalapy/py/PyFunction.scala
https://github.com/shadaj/scalapy/blob/master/src/main/scala/me/shadaj/scalapy/py/ObjectFascade.scala#L13
https://github.com/shadaj/scalapy/blob/master/src/main/scala/me/shadaj/scalapy/py/DynamicRef.scala#L17

**Comment by ndjensen** [comment]
We are a small project aimed at Java, at this time we don't want to include Scala code.  That's that much more code to maintain and test with each release.  That said, if there are features that Jep could include to make scalapy work better, or features inspired from scalapy, we would consider those.

**Comment by SemanticBeeng** [comment]
Understood, thanks.
Things on https://github.com/ndjensen/jep/tree/dev_4.0/src/main/java/jep/python  look indeed useful and worth developing. 

Some things like `PyPointer`  are interesting and/but potentially overlapping/related to `Ref` from `ScalaPy` so it would be good to make the relation more explicit.

My specific need is to return to Scala and manage references to `Pandas`.
Memory management looks good. Maybe if you added more tests/executable specs to state the scenarios you want to cover?

**Comment by SemanticBeeng** [comment]
@ndjensen 
> _"Ideally we would return a pointer to a Python object that provides some features and could be passed back into Python. "_

Definitely this is great and needed evolution.
Is there a way to use this now (reliable enough)? (using 3.7.1 atm)

**Comment by ndjensen** [comment]
No, there's not a reliable way to do that at present.

**Comment by ndjensen** [comment]
3.8 which is now released enables you to get a Python object/reference and use it in Java.  See [javadoc](http://ninia.github.io/jep/javadoc/) for `jep.python.PythonObject` and `jep.python.PythonCallable` and `Jep.getValue(String name, Class<T> class)`.  You can use `jep.getValue(name, PyObject.class)` or `Jep.getValue(name, PyCallable.class)` to get the PyObject.
