### ISSUE TITLE
Is there an easy way to create a Pandas DataFrame using jep?

### ISSUE THREAD

**Issue by tomtobin** [ninia/jep#120]
I have lists of POJOs in Java and can marshal into a jep.PyJList of jep.PyJMaps using the following:

```
List<Map<String, Object>> dataMaps = new ArrayList<>();
for (Map record : data.asMaps()) {
    dataMaps.add(record);
}
jep.set("MyData", dataMaps);

```
I now need this as a DataFrame - tried:
```
pd.DataFrame(MyData)
pd.DataFrame(list(MyData))
pd.DataFrame.from_records(MyData)

```
... no luck - any suggestions

**Comment by ndjensen** [comment]
I'm not familiar with Pandas but presuming it takes a Python dictionary you should be able to convert a PyJMap to a normal Python dictionary.  PyJMap implements the Python mapping protocol so it appears as a dictionary to most commands but it's still a Java object that is wrapped inside a Python object.  In Java terms, PyJMap can be considered an interface that matches dictionary, but it doesn't support all the operations/functions a dictionary does.  So you could try looping over the map and turning it into a dictionary such as

```python
d = {}
for key in MyData:
    d[key] = MyData[key]
```

Do you have a specific error message?  Someone on the mailing list may be able to help too.

**Comment by bsteffensmeier** [comment]
This issue is inactive and I don't see any bugs or problems originating from jep so I am closing it.
