### ISSUE TITLE
Compilation error while trying to install jep

### ISSUE THREAD

**Issue by ps3331333** [ninia/jep#121]
- Windows 10 64-bit
- Python 3.6.4 64-bit
- Java 1.8.0_151 64-bit

When entering on the command line  `pip install jep` I get the following error:

> error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": 
> http://landinghub.visualstudio.com/visual-cpp-build-tools

I downloaded and installed Build Tools for Visual Studio 2017 (the latest version), included Windows 8.1 and Windows 10 SDKs, run again the installation and got the same error. What step am I missing?

**Comment by ndjensen** [comment]
"The installer also includes the MSVC compiler toolset from VS 2015 Update 3."  Did you ensure that you installed that?  It may be a checkbox in the install process.
