### ISSUE TITLE
Getting numpy array in Scala program

### ISSUE THREAD

**Issue by ps3331333** [ninia/jep#123]
I have the following snippet in a file named `first.py` :
```
import numpy as np
def retArray():
    array = np.array([[3, -1, 2, 'a'], [0, 4, -3, 'b']])
    return array
```
I call it from a jep-based Scala program, like so:

```
  val jep = new Jep
  jep.runScript("first.py")
  jep.eval("a = retArray()")
  val a = jep.getValue("a")
  println(a)
```
This works fine, but I need variable `a` to be a list of vectors, and be accessible with indexes such as `a(1)`. How to instantiate `a` with `getValue` ?

**Comment by ndjensen** [comment]
Why are you using numpy?  Why not just use a Python list?

**Comment by ps3331333** [comment]
Because I want to check that the interface with numpy works in my environment.

**Comment by bsteffensmeier** [comment]
The jep.NDArray class only works with numpy arrays that are compatible with java primitive arrays. Since your array mixes types it will not work and you will need to perform some conversion in python before calling getValue()

**Comment by ps3331333** [comment]
What is the maximum length allowed in an `eval` statement? Since in Scala I can work with different types in a single collection (i.e. strings and ints) , I could build an `eval` statement that will "load" the collection in Python.

**Comment by bsteffensmeier** [comment]
There is no maximum length for an eval statement

**Comment by bsteffensmeier** [comment]
I do not think anything else needs to be done for this issue.
