### ISSUE TITLE
Scala: Getting "Not a pyjfield object" while running the example

### ISSUE THREAD

**Issue by pgschr** [ninia/jep#124]
- OS Platform, Distribution, and Version: Windows 10
- Python Distribution and Version: 3.6.4
- Java Distribution and Version: Java 8, Scala 2.11

I'm trying to reproduce in Scala the example in Getting Started as described [here](https://github.com/ninia/jep/wiki/Getting-Started#example-code).

The first problem I have is that the variable `obj` is not defined in the Java program, I assume that it represents a Java class that is instantiated, but the definition of this class in the example is missing.

I tried anyway using a class named MyClass (see bellow), but I get the error: `<class 'TypeError'>: Not a pyjfield object`.

Scala:

```
class MyClass (var x: Int, var y: Int) {
  def someFuncion = {
    println(x + y)
  }
}

object App extends App{

  val jep = new Jep
  jep.runScript("first.py")

  val obj = new MyClass (1,2)
  jep.set("arg", obj)
  jep.eval("x = setX(arg)")
  val result1 = jep.getValue("x")
    
}:


```

Python:

```
def setX(obj):
    obj.x = 99

```

By the way, the method `jep.setValue` in the Getting Started example seems to  have been replaced with `jep.set (String,Object)`.

**Comment by bsteffensmeier** [comment]
It looks like the part that fails is `obj.x = 99`. In this case obj is scala object, which I would think is really just a java object. You can only assign values to fields on a java object if those fields are public. I don't know much about how scala code is compiled, but [this post on stackoverflow](https://stackoverflow.com/questions/10347384/scala-can-i-declare-a-public-field-that-will-not-generate-getters-and-setters-w) suggests it is not making a public field which would explain why it doesn't work.

**Comment by pgschr** [comment]
If I replace `obj.x = 99` with `return obj.x` (i.e. I'm not assigning a value to `obj.x`) I get the following error:
`<class 'TypeError'>: Expected java.lang.Object but received a method.`.  in `jep.getValue("x")`. I'm returning an integer, why does it say that it received a method?

**Comment by pgschr** [comment]
Thanks, returning in the Python function `return obj.x()` worked (i.e. not attempting to change the value of a protected member)/ Note that I had to use `x()` instead of simply `x`.

**Comment by bsteffensmeier** [comment]
This is specific to interoperability with scala and there is a known workaround. There are not currently any plans to add scala specific support.
