### ISSUE TITLE
Loading Python scripts from classpath

### ISSUE THREAD

**Issue by SemanticBeeng** [ninia/jep#127]
Is there a way to load Python code / scripts from classpath ?

This API seems to suggest it but implementation does not even try:
https://github.com/ndjensen/jep/blob/master/src/jep/Jep.java#L501-L503

Judging by this https://github.com/ndjensen/jep/blob/master/src/jep/Jep.java#L509 it is not possible to do run scripts from a memory variable.

Tried to replace
```
       jep.runScript(scriptName + ".py", getClass.getClassLoader)
```
with

```
      val stream = getClass.getResourceAsStream(s"$scriptName.py")
      val script = scala.io.Source.fromInputStream( stream ).mkString

      jep.setClassLoader(getClass.getClassLoader)
      jep.eval(script)
```
and getting 

```
java.lang.RuntimeException: jep.JepException: <class 'SyntaxError'>: ('multiple statements found while compiling a single statement', ('<string>', 1, 13, 'import numpy\n'))
java.lang.RuntimeException: jep.JepException: <class 'SyntaxError'>: ('multiple statements found while compiling a single statement', ('<string>', 1, 13, 'import numpy\n'))
```

`eval` can work with one line at a time only?
How to eval the entire body of a script from a string?
Would that be equivalent to `runScript` ?

Please advise - thank you.

**Comment by ndjensen** [comment]
Please use the mailing list for questions and github issues for actual issues.

runScript(String) expects a path to a filename.  [It is looking for a file.](https://github.com/ninia/jep/blob/dev_3.7/src/jep/pyembed.c#L1462)  It primarily exists to enable a command line execution of the jep script, for example `python someFile.py` has an equivalent `jep someFile.py`.

`eval` works on one line at a time unless you're in interactive mode as set on the `JepConfig`.  Please see the [javadoc for eval](https://github.com/ninia/jep/blob/dev_3.7/src/jep/Jep.java#L537).

**Comment by SemanticBeeng** [comment]
> "Please use the mailing list for questions and github issues for actual issues."

Will do, yes. 
Was hoping this to become a feature request but the code reviews showed this might not be possible,

Thanks
