### ISSUE TITLE
DirectNDArray#getLength should consider .limit(), not .capacity()

### ISSUE THREAD

**Issue by strelec** [ninia/jep#129]
Capacity is not the right measure for length, because it discards all the metadata about the buffer.

The correct size is the difference between the limit and the pos (they also call it "offset").

**Comment by bsteffensmeier** [comment]
I don't think we can use the position or limit because those attributes are mutable, if they change then the DirectNDArray could become invalid. I would prefer to use only the immutable attributes of the buffer so we can catch invalid dimensions during construction.
