### ISSUE TITLE
Import of numpy kills console output when run from scala

### ISSUE THREAD

**Issue by tmrn411** [ninia/jep#130]
I'm running jep from scala (in Eclipse IDE) on Mac OSX.  The following code snippet produces the expected output

   ```
 jep.set("msgIn", "passed from Scala")

    jep.eval("print('printing from jep: ' + msgIn)")
    jep.eval("msgOut = msgIn + ' then passed out again'")
    
    val msgIn = jep.getValue("msgIn")
    val msgOut = jep.getValue("msgOut")
    println("printing from scala, original msg pass thru: " + msgIn)
    println("printing from scala, modified msg: " + msgOut)
```

output

```
printing from scala, original msg pass thru: passed from Scala
printing from scala, modified msg: passed from Scala then passed out again
printing from jep: passed from Scala
```

But when I import numpy, the console output from within jep gets disconnected
```
 jep.set("msgIn", "passed from Scala")

    jep.eval("import numpy")
    jep.eval("print('printing from jep: ' + msgIn)")
    jep.eval("msgOut = msgIn + ' then passed out again'")
    
    val msgIn = jep.getValue("msgIn")
    val msgOut = jep.getValue("msgOut")
    println("printing from scala, original msg pass thru: " + msgIn)
    println("printing from scala, modified msg: " + msgOut)
```
 
output
```
printing from scala, original msg pass thru: passed from Scala
printing from scala, modified msg: passed from Scala then passed out again
```

Jep seems to be running fine since I can still pass variables in, operate on them in jep, then pass them out and get the correct results.  Also, numpy seems to load fine.  I've created more complicated examples where I can pass in NDArray's, operate on them with numpy functions and then pass the correct results back out using the jep NDArray construct.

So it seems like the only thing broken is the connection to the console, which is not a critical problem, but it is a big annoyance.  

Any suggestions on tracking this down?

**Comment by bsteffensmeier** [comment]
That is weird. You should check if sys.stdout is the same object before and after importing numpy. `jep.getValue('sys.stdout')` should return a String representation of stdout that you can look at in scala. You might also try `sys.stdout.flush()` and see if that makes a difference, or even using `sys.stdout.write()` instead of `print()` although it really shouldn't matter.

I'm also curious if you are using numpy as a shared module? I can't think of any reason why that would make a difference but there is alot of shuffling that can go on under the hood if it is is shared so I would be curious if you get the same result without sharing it.

**Comment by ndjensen** [comment]
I'm curious to know what happens if you set `redirectOutputStreams` to true on the `JepConfig` when you construct the `Jep` instance.

**Comment by tmrn411** [comment]
Thanks for that suggestion.  Calling flush in jep environment got the msg out, it also fixed another subtle issue I noticed.  Above, the print from jep came out after the println in scala.  With the flush in jep it is emitted in the expected order.


```
printing from jep: passed from Scala
printing from scala, original msg pass thru: passed from Scala
printing from scala, modified msg: passed from Scala then passed out again
```

**Comment by tmrn411** [comment]
setting redirectOutputStreams also fixes the problem.  The console output comes out in the correct order, and it is not effected by the numpy import.  This is the cleaner solution since I won't need to follow up each print with a flush.  Thanks for the suggestions.
