### ISSUE TITLE
Issues during installation

### ISSUE THREAD

**Issue by gatterius** [ninia/jep#136]
Hello!
I'm trying to install jep using pip, and installation fails with this long log of warnings and errors.
[log-jep.txt](https://github.com/ninia/jep/files/2013926/log-jep.txt)
Previously I was getting and error "Visual C++ not found" though it was installed, and reinstallation of Visual Build Tools has caused the described problem.
What can be done to resolve this issue?

- OS Platform, Distribution, and Version: Windows 10
- Python Distribution and Version: Python 3.6.5
- Java Distribution and Version: JDK 9.0.4

**Comment by ndjensen** [comment]
Did you follow the instructions [here](https://github.com/ninia/jep/wiki/Windows#python-35-and-36-msvc-build-setup)?  Did you install the two Windows SDKs when you installed the build tools?

I haven't seen your error before.  Checking our appveyor build, we have 

`
C:\Program Files (x86)\Windows Kits\10\bin\x64\mt.exe -nologo -manifest build\temp.win-amd64-3.6\Release\src\main\c\Jep\jep.cp36-win_amd64.pyd.manifest -outputresource:build\lib.win-amd64-3.6\jep\jep.cp36-win_amd64.pyd;2
`

That's on the dev_3.8 branch so the location of the src is slightly different but it's basically the same as the command you're running, your build is just failing to find mt.exe.  Can you check your system and see if you have mt.exe and what directory it's in?  A quick Google search implies it moved in one release.

**Comment by gatterius** [comment]
I have installed both SDKs, but checking it I found that (as it seems) there are 2 installations of same version of Build Tools. I'll remove both and reinstall it just to make sure the problem is not caused by it.

**Comment by gatterius** [comment]
It seems like the reinstallation helped and I managed to install it using setup.py. Thanks for the help!
