### ISSUE TITLE
Using Jep loading Python libraries from an environment

### ISSUE THREAD

**Issue by pgschr** [ninia/jep#137]
- OS Platform, Distribution, and Version: Windows 10
- Python Distribution and Version: 3.6.4
- Java Distribution and Version: 8

I'm running Jep with no issues in a Play for Scala application server (calling Python scripts from Scala). All the libraries are loaded globally with no environment.

Now, I installed Anaconda and created an environment where Jep is installed. How to point the Java/Scala program to a specific environment?

**Comment by ndjensen** [comment]
Please use the mailing list if you just have a question.

Since you're on Windows, you'll need to set the environment variable PATH to the Python directory of the version you want.  You may also need to set the environment variable PYTHONHOME.
