### ISSUE TITLE
JEP doesn't build/install with Java >=10

### ISSUE THREAD

**Issue by ender8282** [ninia/jep#138]
- OS Platform, Distribution, and Version: Ubuntu 18.04
- Python Distribution and Version: Python 3.6.5
- Java Distribution and Version: Oracle JDK 10

In, I believe, Java 8 Oracle added header-file-generation support to javac.  In JDK 9 javah was deprecated and in JDK 11 it was removed entirely [1].  This means that it isn't possible to build JEP under Oracle Java 10 or OpenJDK 10.  

In short header file generation should now be done using javac in conjunction with the "-h <header_out_dir>" option.  This has the side effect of compiling the referenced java classes.  The JEP should update its builder/installer to make use of the new JDK 8+ approach.  

[1] https://docs.oracle.com/javase/9/tools/javah.htm#JSWOR687

[jep_error.txt](https://github.com/ninia/jep/files/2028265/jep_error.txt)

**Comment by ender8282** [comment]
Sorry for the duplicate.  Feel free to mark this ticket as such and close.  Any ballpark (1 day, 1 month, 1 year) on when JEP 3.8 might be released?

**Comment by ndjensen** [comment]
Sometime in the June - August timeframe of 2018.

**Comment by ndjensen** [comment]
Jep 3.8.0 is now released so this issue is resolved.
