### ISSUE TITLE
DirectNDArray to ndarray auto conversion does not trigger from JVM side

### ISSUE THREAD

**Issue by SemanticBeeng** [ninia/jep#139]
- OS Platform, Distribution, and Version: Ubuntu 16
- Python Distribution and Version: 3.6.4
- Java Distribution and Version: java version "1.8.0_161"

Context
> _" # Getting the same object from a java method triggers the automatic conversion to an ndarray."_

https://github.com/ninia/jep/blob/2af843dc55b5d8420c520153081acd041ba5022b/tests/test_numpy.py#L112-L122

According to the test this happens if creating the `DirectNDArray` from Python.

```
        from java.nio import ByteBuffer, ByteOrder

        buffer = ByteBuffer.allocateDirect(48)
        ndarray = self.createNdarrayFromBuffer(buffer.asIntBuffer())
        ndarray2 = self.test.testDirectArgAndReturn(ndarray)
        ndarray[0] = 1
        self.assertEquals(1, ndarray2[0])
        ndarray2[0] = 2
        self.assertEquals(2, ndarray[0])

        ndarray2 = self.test.testArgAndReturn(ndarray)
        self.assertEquals(ndarray[0] + 5, ndarray2[0])

        self.assertTrue(self.test.callIntMethod(ndarray))
```

Should I be able to call `ndarray.tobytes()` ?
https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.ndarray.tobytes.html

But the main issue is that if `createNdarrayFromBuffer` is from Java then in Python I still get the `DirectNDArray` wrapped in a `PyJObject` and not the `ndarray` instance.

Tried to trigger conversion by passing to `invoke`:
1. an instance of `DirectNDArray`  
2. an `ArrayList` with an  instance of `DirectNDArray`  inside and calling `get(0)` from Python
3. an object of custom type with an  instance of `DirectNDArray`  inside and calling `getData()` from Python

My end goal is to get the bytes from the converted `ndarray` while benefiting from the excellent feature of shared (zero copy) memory feature that `jep` provides.

Thanks

**Comment by SemanticBeeng** [comment]
Example code I'd expect to work

```
def convert(util: DataWindowRawHelper):

    from java.nio import ByteBuffer, ByteOrder

    buffer = ByteBuffer.allocateDirect(48)
    #ndarray = self.createNdarrayFromBuffer(buffer.asIntBuffer())

    DirectNDArray = jep.findClass("jep.DirectNDArray")
    from java.util import ArrayList
    # Start off with a pyjobject which is a DirectNDArray
    dndarray = DirectNDArray(buffer.asIntBuffer())

    dndarray = util.inAndOut(dndarray)
    from java.util import ArrayList
    a = ArrayList()
    a.add(dndarray)
    # Getting the same object from a java method triggers the automatic
    # conversion to an ndarray.
    return a.get(0).tobytes('F')
```

Expected `a.get(0).tobytes('F')` to succeed as call on an `ndarray` object.

Instead I get 

```
ep.JepException: <class 'AttributeError'>: 'jep.PyJObject' object has no attribute 'tobytes' 
```

**Comment by ndjensen** [comment]
Ok, so the unit test is a bit misleading.  Should you instantiate a Java object from within Python, including NDArray and DirectNDArray, you will always get a PyJObject or one of it's subclasses.  Automatic conversions do not happen when you're calling a Java constructor from Python.  This enables you to get the object you specified, e.g. java.lang.Integer or java.lang.String, instead of the Python equivalent.

> Tried to trigger conversion by passing to invoke:
>    an instance of DirectNDArray
>    an ArrayList with an instance of DirectNDArray inside and calling get(0) from Python
>    an object of custom type with an instance of DirectNDArray inside and calling getData() from Python

This should be impossible if you compiled Jep with numpy support.  When you run python setup.py build you should see something like `numpy include found at somePathToPython/site-packages/numpy/core/include`.

Try checking the type of `a.get(0)` and you probably still have a Java NDArray and not a numpy.ndarray.  Your code as written works when Jep is compiled with numpy support.

**Comment by SemanticBeeng** [comment]
Please clarify

1. _"you probably still have a Java NDArray and not a numpy.ndarray. "_
vs
2. _"Your code as written works"_

Do you mean `tobytes()` should work?

I will check if compiled with `numpy` support, thanks.

**Comment by SemanticBeeng** [comment]
I rebuilt `jep` like 100 times before and it worked! :-)
Thank you _very_ much, Nate!

**Comment by SemanticBeeng** [comment]
BTW: anything special about cleaning up this memory?
If I cleanup from JVM side will Python also let go of it through normal GC?

**Comment by SemanticBeeng** [comment]
Hope this helps others discover this feature.
Kindly consider adding tests to show `tobytes` so it is evident the conversion happened.
The current test use array index which is a bit unclear.

**Comment by bsteffensmeier** [comment]
> BTW: anything special about cleaning up this memory?
> If I cleanup from JVM side will Python also let go of it through normal GC?

The ndarray in Python maintains a reference to the Java DirectNDArray through JNI so Java cannot collect anything until Python releases it. Whenever there are no more references to the ndarray in Python it will collect the ndarray which releases the DirectNDArray and then Java is free to collect it whenever it runs GC. So the only cleanup would be to make sure you aren't inadvertently keeping a reference to the ndarray longer than intended.
