### ISSUE TITLE
 java.lang.UnsatisfiedLinkError: no jep in java.library.path (Python Anaconda3, Windows 10)

### ISSUE THREAD

**Issue by SaintNazaire** [ninia/jep#141]
## **System information**

- Windows 10 professional
- Scala 2.12.3 (built-in), 2.10.6 (built-in), 2.11.11 (built-in)
- sbt 1.1.2 (local 0.13.13 as per scalapy's build.sbt specs)
- Java 1.8 JRE 1.8.0_171
- Java 8 JDK 171
- Python 3.6.4 (Conda 4.4.10, Anaconda 1.6.9 64x bits)
- jep 3.7.1
- Eclispe Oxygen.3a (4.7.3a) build 20180405-1200
- PyDev 6.3.3.201805051638
- build.sbt config:
```
javaOptions += "-Djava.library.path=/Users/.../Anaconda3/Lib/site-packages/jep"
javaOptions += "-Djava.library.path=/Users/.../Anaconda3/Lib/site-packages/jep.dll"
javaOptions += "-Djava.library.path=/Users/.../Anaconda3/"
javaOptions += "-Djava.library.path=/Users/.../Anaconda3/Lib"
javaOptions += "-Djava.library.path=/Users/.../Anaconda3/Lib/site-packages"
javaOptions += "-Djava.library.path=/Users/.../Anaconda3/Library/bin"
javaOptions += "-Djava.library.path=/Users/.../Anaconda3/pkgs"
javaOptions += "-Djava.library.path=/Users/.../Anaconda3/DLLs"
javaOptions += "-Djava.library.path=/Users/.../.ivy2/cache/black.ninia/jep"
```
- PATH environment variable config:
```
c:\users\...\Anaconda3
c:\users\...\Anaconda3\Lib\sites-packages
c:\users\...\Anaconda3\Lib\sites-packages\jep
c:\users\...\Anaconda3\Library\bin
c:\users\...\Anaconda3\Lib\pkgs
c:\users\...\Anaconda3\DLLs
```
- LD_LIBRARY_PATH environment variable config:
```
c:\users\...\Anaconda3
c:\users\...\Anaconda3\Lib\sites-packages
c:\users\...\Anaconda3\Lib\sites-packages\jep
c:\users\...\Anaconda3\Library\bin
c:\users\...\Anaconda3\Lib\pkgs
c:\users\...\Anaconda3\DLLs
```
- pointing to the jep jar file in .../sites-packages/jep from properties in Eclipse
Click right on project > Properties > Java Build Path > Libraries > Add External JARs

## **Command triggering issue & relevant error log**

Run selection in Scala Interpreter and same from command line

`implicit val interpeter = new jep.Jep()`

>  java.lang.UnsatisfiedLinkError: no jep in java.library.path
>   at java.lang.ClassLoader.loadLibrary(Unknown Source)
>   at java.lang.Runtime.loadLibrary0(Unknown Source)
>   at java.lang.System.loadLibrary(Unknown Source)
>   at jep.Jep.<clinit>(Jep.java:217)
>   ... 48 elided

**Comment by bsteffensmeier** [comment]
You cannot use `-Djava.library.path=...` more than once. Java will only use one of them. You probably have the correct value in the list somewhere, but it seems it is picking up a different one.

`LD_LIBRARY_PATH` is common on POSIX systems, as far as I know it does nothing on windows.

I recommend setting `java.library.path` only once to the directory which contains jep.dll. I think either `/Users/.../Anaconda3/Lib/site-packages/jep` or `/Users/.../Anaconda3/Lib/site-packages` might be correct on your setup.

**Comment by SaintNazaire** [comment]
Thank for syntax error however to no avail:

`javaOptions += "-Djava.library.path=/Users/.../Anaconda3:/Users/benoi/Anaconda3/Lib/site-packages/jep:/Users/.../Anaconda3/Lib/site-packages:/Users/.../Anaconda3/Library/bin:/Users/.../Anaconda3/Library/bin:/Users/.../Anaconda3/DLLs:/Users/.../Anaconda3/pkgs"`

**Comment by ndjensen** [comment]
1. If you run the jep.bat command line script (interpreter), does that work?
2. I'm not familiar with Scala in Eclipse but am familiar with Java in Eclipse.  Are you setting -Djava.library.path through the Run Configurations -> Arguments tab -> VM arguments or setting it elsewhere?
3. Have you tried setting the PATH variable?  https://github.com/ninia/jep/wiki/FAQ#how-do-i-fix-unsatisfied-link-error-no-jep-in-javalibrarypath

**Comment by SaintNazaire** [comment]
1. jep.bat works, here is the output:

` (base) C:\WINDOWS\system32>c:\users\...\anaconda3\scripts\jep.bat`

> (base) C:\WINDOWS\system32>SETLOCAL
> 
> (base) C:\WINDOWS\system32>SET VIRTUAL_ENV=
> 
> (base) C:\WINDOWS\system32>IF NOT "" == "" (
> SET PATH="\bin";"C:\Progra~1\Java\jdk1.8.0_171\bin";"C:\Users\...\Anaconda3;C:\Users\...\Anaconda3\Library\mingw-w64\bin;C:\Users\...\Anaconda3\Library\usr\bin;C:\Users\...\Anaconda3\Library\bin;C:\Users\benoi\Anaconda3\Scripts;C:\Users\...\Anaconda3\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;
...etc... etc.. etc..."
>  SET PYTHONHOME=
> )
> 
> (base) C:\WINDOWS\system32>SET cp="c:\users\...\anaconda3\Lib\site-packages\jep\jep-3.7.1.jar"
> 
> (base) C:\WINDOWS\system32>IF DEFINED CLASSPATH (SET cp="c:\users\....\anaconda3\Lib\site-packages\jep\jep-3.7.1.jar"; )
> 
> (base) C:\WINDOWS\system32>SET jni_path="c:\users\...\anaconda3\Lib\site-packages\jep"
> 
> (base) C:\WINDOWS\system32>SET args=
> 
> (base) C:\WINDOWS\system32>IF "" == "" (SET args="c:\users\...\anaconda3\Lib\site-packages\jep\console.py" )
> 
> (base) C:\WINDOWS\system32>java -classpath "c:\users\...\anaconda3\Lib\site-packages\jep\jep-3.7.1.jar" -Djava.library.path="c:\users\...\anaconda3\Lib\site-packages\jep" jep.Run "c:\users\...\anaconda3\Lib\site-packages\jep\console.py"
> 
>               No readline available. History will not be available.
> 
>                    For Windows use pyreadline and get it from the official git
>                    repo on github:
>                    https://github.com/pyreadline/pyreadline
> 
>                    Do NOT use the version on pypi.python.org, and therefore
>                    Do NOT use the version installed by pip.  It is out of date
>                    and doesn't work with Jep!

2. I am setting Djava.library.path through the build.sbt file not Run Configurations -> Arguments tab -> VM arguments

3. Yes I have tried to set all the variation for the path to no avail

**Comment by ndjensen** [comment]
Sorry that I missed some of your previous tests.  If jep.bat works then we should just need to figure out what it's doing differently than your application.  If I remember correctly, Windows filesystems are generally not case sensitive, so that's probably not it.  In your javaOptions=-Djava.library.path you have `/Users/.../...` instead of `C:/Users/.../...`  Can you add the drive name and try again?  If that doesn't work, see if you can spot something different in jep.bat's code/options from yours.

**Comment by SaintNazaire** [comment]
All else failed but I got one functional workaround which is to add jep as a managed dependency approach in build.sbt

```
libraryDependencies += "black.ninia" % "jep" % "3.7.0"
```

Also make sure that jep installed in python is 3.7.0

`pip install jep=3.7.0`

Then in Properties > Java Build Path > Librairies > jep-3.7.0.jar > Native librairy location, set the location path to the .dll, typically something like:

`C:/Users/.../Anaconda3/Lib/site-packages/jep`

Do not forget to add the following paths to the Windows environment variables %PATH%, note this links to jep but also the python librairies:

```
C:/Users/.../Anaconda3/Lib/site-packages/jep
C:/Users/.../Anaconda3/
C:/Users/.../Anaconda3/DLLs
```
Now do not forget to close restart Eclipse (or the Windows environment variables won't be reset), then 

```
sbt reload
sbt publishLocal
```

This is a functional workaround which fixes also shadaj/scalapy#6

My bet is that I don't know how to set properly the path on a windows machine (including several paths) despite hours of crawling the internet, any clue would be appreciated

`javaOptions += "-Djava.library.path=/Users/.../Anaconda3/Lib/site-packages/jep"

**Comment by yinmazhong** [comment]
In my case(ubuntu16,jep version:3.8.1):
The code below can be solved

文档上写的这个`If you built the source yourself, you can run python setup.py install to install Jep to the standard dirs.`　不好使
看setup.py源码：
` cmdclass={
              'setup_java': setup_java,
              'build_java': build_java,
              'javadoc': javadoc,
              'build_jar': build_jar,
              'build': jep_build,
              'build_ext' : build_ext,
              'build_scripts': build_scripts,
              'install_lib': jep_install,
              'clean': really_clean,
              'test': test,
          },`

所以执行
> `python3 setup.py install_lib `
才对，
执行打印如下：
> numpy include found at /home/xxh/anaconda3/lib/python3.6/site-packages/numpy/core/include
running install_lib
running build_py
running build_ext
ln -sf jep.cpython-36m-x86_64-linux-gnu.so /home/xxh/anaconda3/lib/python3.6/site-packages/jep/libjep.so

**Comment by SaintNazaire** [comment]
@yinmazhong, interesting but not relevant.

**Comment by SemanticBeeng** [comment]
@bsteffensmeier Also getting something like this without changes to my application code, after switching to `jep` 3.8.1 from 3.7.1 and running on Ubuntu 16,

```
[error]   ! initialize Numpy correctly
[error]    java.util.concurrent.ExecutionException: Boxed Error (Jep.java:181)
[error] jep.Jep$TopInterpreter.initialize(Jep.java:181)
[error] jep.Jep$TopInterpreter.access$400(Jep.java:108)
[error] jep.Jep.createTopInterpreter(Jep.java:280)
[error] jep.Jep.<init>(Jep.java:382)
[error] io.yields.platform.orchestration.shared.common.IsolatedJepCallContext$class.foreach(IsolatedJepCallContext.scala:21)
[error] io.yields.platform.orchestration.shared.specs.infrastructure.AnalysisOrchestrationIsolatedSpec.foreach(AnalysisOrchestrationIsolatedSpec.scala:10)
[error] jep.Jep.initializePython(Native Method)
[error] jep.Jep.access$100(Jep.java:57)
[error] jep.Jep$TopInterpreter$1.run(Jep.java:137)
[error] CAUSED BY
[error]  java.lang.Error: java.lang.UnsatisfiedLinkError: jep.Jep.initializePython([Ljava/lang/String;)V (Jep.java:181)
[error] jep.Jep$TopInterpreter.initialize(Jep.java:181)
[error] jep.Jep$TopInterpreter.access$400(Jep.java:108)
[error] jep.Jep.createTopInterpreter(Jep.java:280)
[error] jep.Jep.<init>(Jep.java:382)
```

Read through this happening on OSX.
https://groups.google.com/forum/#!topic/jep-project/FKeO1hE14jo

Is there something special about 3.8.1 that I need to know, please?

**Comment by ndjensen** [comment]
@SemanticBeeng, this issue is for Windows, the mailing list thread is for OS X, you're on Ubuntu, maybe a new thread on the mailing list is warranted?

Regardless, your build does not appear to be correct.  `jep.Jep$TopInterpreter` does not exist in Jep 3.8.  The logic was separated out to class `MainInterpreter`.  Please try rebuilding and make sure both the jar and the native library are at 3.8.

**Comment by ndjensen** [comment]
I'm not sure we can do anything else for this so I'm going to close the ticket.
