### ISSUE TITLE
[Python 3.7] Need help with py_compile

### ISSUE THREAD

**Issue by rapgro** [ninia/jep#142]
Is there a way to print the real error if py_compile fails? jep.eval() seems to eat what's written to stderr. 

https://github.com/ninia/jep/blob/e3d094da198fe3a8f5123cab550a6f96bd5d436d/src/jep/test/TestCompiledScript.java#L23

**Comment by bsteffensmeier** [comment]
jep.eval() should not be eating what's written to stderr. To test this I placed this script in build/testScript.py

```
def invalidMethod()
    pass
```

When I run jep.test.TestCompiledScript then I see this on stderr:

```
  File "build/testScript.py", line 1
    def invalidMethod()
                      ^
SyntaxError: invalid syntax
```

It works as expected. Can you elaborate on what you are doing to see the problem?

You might also consider investigating passing doraise=True into py_compile.compile which will give you more control over the error.

**Comment by rapgro** [comment]
Okay, let's assume py_compile works without error and generates a valid pyc file. When we try to run the test with Python 3.7, there's that error:
```
FAIL: test_compiledScript (test_run_script.TestRunScript)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/python-jep-3.7.0/python3/tests/test_run_script.py", line 18, in test_compiledScript
    jep_pipe(build_java_process_cmd('jep.test.TestCompiledScript'))
  File "/usr/lib64/python3.7/contextlib.py", line 239, in helper
    return _GeneratorContextManager(func, args, kwds)
  File "/usr/lib64/python3.7/contextlib.py", line 82, in __init__
    self.gen = func(*args, **kwds)
  File "/builddir/build/BUILD/python-jep-3.7.0/python3/tests/jep_pipe.py", line 36, in jep_pipe
    assert False, stderr
AssertionError: b'Exception in thread "main" jep.JepException: <class \'RuntimeError\'>: Bad code object in .pyc file\n\tat jep.Jep.run(Native Method)\n\tat jep.Jep.runScript(Jep.java:506)\n\tat jep.Jep.runScript(Jep.java:482)\n\tat jep.test.TestCompiledScript.main(TestCompiledScript.java:26)\n'
```

**Comment by bsteffensmeier** [comment]
Ah, that makes sense. The format of pyc files changed in Python 3.7 and since we have code that reads them it needed to be updated to reflect the new format. The current version of jep does not fully support Python 3.7 so this will not work. The next version of jep, 3.8, will be the first version to officially support Python 3.7 and support for the new pyc format was added in f1ae067. If you need this functionality now you can check out the dev_3.8 branch. We are putting the final touches on that branch and hope to have a release candidate within a week.

**Comment by rapgro** [comment]
Well, that looks somehow like a regression of #77 .

**Comment by ndjensen** [comment]
It's not a regression given Python 3.7 did not exist at the time and Jep 3.7 does not officially support Python 3.7.  If you need this capability on Python 3.7, follow @bsteffensmeier's comments and use the dev_3.8 branch.
