### ISSUE TITLE
pip install : no such file or directory for classlist_7.txt

### ISSUE THREAD

**Issue by tafka96** [ninia/jep#147]
When installing jep with pip i get the error     
error: [Errno 2] No such file or directory: 'src/main/resources/jep/classlist_7.txt'

- OS Platform, Distribution, and Version: Windows 7 
- Python Distribution and Version: Python 3.6
- Java Distribution and Version: Java 1.8

**Comment by tafka96** [comment]
full install path

Installing collected packages: jep
  Running setup.py install for jep ... error
    Complete output from command C:\Python\python.exe -u -c "import setuptools,
tokenize;__file__='C:\\Users\\p998twy\\AppData\\Local\\Temp\\pip-install-3bvir3p
x\\jep\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().repl
ace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --rec
ord C:\Users\p998twy\AppData\Local\Temp\pip-record-tcgcn3y0\install-record.txt -
-single-version-externally-managed --compile:
    numpy include found at C:\Python\lib\site-packages\numpy\core\include
    running install
    running build
    running setup_java
    Using JAVA_HOME: C:\Program Files\Java\jdk1.8.0_162
    running build_java
    C:\Program Files\Java\jdk1.8.0_162\bin\javac.exe -deprecation -d build\java
-classpath src src\main\java\jep\AbstractNDArray.java src\main\java\jep\ClassEnq
uirer.java src\main\java\jep\ClassList.java src\main\java\jep\DirectNDArray.java
 src\main\java\jep\Jep.java src\main\java\jep\JepConfig.java src\main\java\jep\J
epException.java src\main\java\jep\JepScriptEngine.java src\main\java\jep\JepScr
iptEngineFactory.java src\main\java\jep\LibraryLocator.java src\main\java\jep\Ma
inInterpreter.java src\main\java\jep\NamingConventionClassEnquirer.java src\main
\java\jep\NDArray.java src\main\java\jep\Proxy.java src\main\java\jep\PyConfig.j
ava src\main\java\jep\Run.java src\main\java\jep\SharedInterpreter.java src\main
\java\jep\Util.java src\main\java\jep\python\InvocationHandler.java src\main\jav
a\jep\python\MemoryManager.java src\main\java\jep\python\PyCallable.java src\mai
n\java\jep\python\PyClass.java src\main\java\jep\python\PyModule.java src\main\j
ava\jep\python\PyObject.java src\main\java\jep\python\PyPointer.java
    C:\Program Files\Java\jdk1.8.0_162\bin\javah.exe -classpath build\java -d bu
ild\include jep.Jep jep.MainInterpreter jep.python.InvocationHandler jep.python.
PyObject jep.python.PyCallable jep.python.PyPointer
    C:\Program Files\Java\jdk1.8.0_162\bin\javac.exe -deprecation -d build\java\
test -classpath build\java;src src\test\java\jep\test\Test.java src\test\java\je
p\test\TestCompiledScript.java src\test\java\jep\test\TestDefaultMethods.java sr
c\test\java\jep\test\TestExceptionCause.java src\test\java\jep\test\TestGetByteA
rray.java src\test\java\jep\test\TestGetCollectionBoxing.java src\test\java\jep\
test\TestGetJPyObject.java src\test\java\jep\test\TestGetTempValue.java src\test
\java\jep\test\TestGetWithClass.java src\test\java\jep\test\TestInvoke.java src\
test\java\jep\test\TestOverload.java src\test\java\jep\test\TestPreInitVariables
.java src\test\java\jep\test\TestSharedArgv.java src\test\java\jep\test\TestShar
edInterpreter.java src\test\java\jep\test\TestSharedModules.java src\test\java\j
ep\test\TestSharedModulesThreads.java src\test\java\jep\test\closeable\TestAutoC
loseable.java src\test\java\jep\test\numpy\TestNumpy.java src\test\java\jep\test
\numpy\TestNumpyArrayToString.java src\test\java\jep\test\numpy\TestNumpyProdSha
red.java src\test\java\jep\test\numpy\example\TestNumpyGILFreeze.java src\test\j
ava\jep\test\numpy\example\TestNumpyMemoryLeak.java src\test\java\jep\test\numpy
\example\TestNumpyProdLost.java src\test\java\jep\test\numpy\example\TestScipyFr
eeze.java src\test\java\jep\test\synchronization\TestCrossLangSync.java src\test
\java\jep\test\types\TestFieldTypes.java src\test\java\jep\test\types\TestMethod
Types.java src\test\java\jep\test\types\TestStaticFieldTypes.java src\test\java\
jep\test\types\TestStaticMethodTypes.java
    copying src\main\java\jep\AbstractNDArray.java to build\java\jep.src\main\ja
va\jep\AbstractNDArray.java
    copying src\main\java\jep\ClassEnquirer.java to build\java\jep.src\main\java
\jep\ClassEnquirer.java
    copying src\main\java\jep\ClassList.java to build\java\jep.src\main\java\jep
\ClassList.java
    copying src\main\java\jep\DirectNDArray.java to build\java\jep.src\main\java
\jep\DirectNDArray.java
    copying src\main\java\jep\Jep.java to build\java\jep.src\main\java\jep\Jep.j
ava
    copying src\main\java\jep\JepConfig.java to build\java\jep.src\main\java\jep
\JepConfig.java
    copying src\main\java\jep\JepException.java to build\java\jep.src\main\java\
jep\JepException.java
    copying src\main\java\jep\JepScriptEngine.java to build\java\jep.src\main\ja
va\jep\JepScriptEngine.java
    copying src\main\java\jep\JepScriptEngineFactory.java to build\java\jep.src\
main\java\jep\JepScriptEngineFactory.java
    copying src\main\java\jep\LibraryLocator.java to build\java\jep.src\main\jav
a\jep\LibraryLocator.java
    copying src\main\java\jep\MainInterpreter.java to build\java\jep.src\main\ja
va\jep\MainInterpreter.java
    copying src\main\java\jep\NamingConventionClassEnquirer.java to build\java\j
ep.src\main\java\jep\NamingConventionClassEnquirer.java
    copying src\main\java\jep\NDArray.java to build\java\jep.src\main\java\jep\N
DArray.java
    copying src\main\java\jep\Proxy.java to build\java\jep.src\main\java\jep\Pro
xy.java
    copying src\main\java\jep\PyConfig.java to build\java\jep.src\main\java\jep\
PyConfig.java
    copying src\main\java\jep\Run.java to build\java\jep.src\main\java\jep\Run.j
ava
    copying src\main\java\jep\SharedInterpreter.java to build\java\jep.src\main\
java\jep\SharedInterpreter.java
    copying src\main\java\jep\Util.java to build\java\jep.src\main\java\jep\Util
.java
    copying src\main\java\jep\python\InvocationHandler.java to build\java\jep.sr
c\main\java\jep\python\InvocationHandler.java
    copying src\main\java\jep\python\MemoryManager.java to build\java\jep.src\ma
in\java\jep\python\MemoryManager.java
    copying src\main\java\jep\python\PyCallable.java to build\java\jep.src\main\
java\jep\python\PyCallable.java
    copying src\main\java\jep\python\PyClass.java to build\java\jep.src\main\jav
a\jep\python\PyClass.java
    copying src\main\java\jep\python\PyModule.java to build\java\jep.src\main\ja
va\jep\python\PyModule.java
    copying src\main\java\jep\python\PyObject.java to build\java\jep.src\main\ja
va\jep\python\PyObject.java
    copying src\main\java\jep\python\PyPointer.java to build\java\jep.src\main\j
ava\jep\python\PyPointer.java
    copying src\test\java\jep\test\Test.java to build\java\jep.test.src\test\jav
a\jep\test\Test.java
    copying src\test\java\jep\test\TestCompiledScript.java to build\java\jep.tes
t.src\test\java\jep\test\TestCompiledScript.java
    copying src\test\java\jep\test\TestDefaultMethods.java to build\java\jep.tes
t.src\test\java\jep\test\TestDefaultMethods.java
    copying src\test\java\jep\test\TestExceptionCause.java to build\java\jep.tes
t.src\test\java\jep\test\TestExceptionCause.java
    copying src\test\java\jep\test\TestGetByteArray.java to build\java\jep.test.
src\test\java\jep\test\TestGetByteArray.java
    copying src\test\java\jep\test\TestGetCollectionBoxing.java to build\java\je
p.test.src\test\java\jep\test\TestGetCollectionBoxing.java
    copying src\test\java\jep\test\TestGetJPyObject.java to build\java\jep.test.
src\test\java\jep\test\TestGetJPyObject.java
    copying src\test\java\jep\test\TestGetTempValue.java to build\java\jep.test.
src\test\java\jep\test\TestGetTempValue.java
    copying src\test\java\jep\test\TestGetWithClass.java to build\java\jep.test.
src\test\java\jep\test\TestGetWithClass.java
    copying src\test\java\jep\test\TestInvoke.java to build\java\jep.test.src\te
st\java\jep\test\TestInvoke.java
    copying src\test\java\jep\test\TestOverload.java to build\java\jep.test.src\
test\java\jep\test\TestOverload.java
    copying src\test\java\jep\test\TestPreInitVariables.java to build\java\jep.t
est.src\test\java\jep\test\TestPreInitVariables.java
    copying src\test\java\jep\test\TestSharedArgv.java to build\java\jep.test.sr
c\test\java\jep\test\TestSharedArgv.java
    copying src\test\java\jep\test\TestSharedInterpreter.java to build\java\jep.
test.src\test\java\jep\test\TestSharedInterpreter.java
    copying src\test\java\jep\test\TestSharedModules.java to build\java\jep.test
.src\test\java\jep\test\TestSharedModules.java
    copying src\test\java\jep\test\TestSharedModulesThreads.java to build\java\j
ep.test.src\test\java\jep\test\TestSharedModulesThreads.java
    copying src\test\java\jep\test\closeable\TestAutoCloseable.java to build\jav
a\jep.test.src\test\java\jep\test\closeable\TestAutoCloseable.java
    copying src\test\java\jep\test\numpy\TestNumpy.java to build\java\jep.test.s
rc\test\java\jep\test\numpy\TestNumpy.java
    copying src\test\java\jep\test\numpy\TestNumpyArrayToString.java to build\ja
va\jep.test.src\test\java\jep\test\numpy\TestNumpyArrayToString.java
    copying src\test\java\jep\test\numpy\TestNumpyProdShared.java to build\java\
jep.test.src\test\java\jep\test\numpy\TestNumpyProdShared.java
    copying src\test\java\jep\test\numpy\example\TestNumpyGILFreeze.java to buil
d\java\jep.test.src\test\java\jep\test\numpy\example\TestNumpyGILFreeze.java
    copying src\test\java\jep\test\numpy\example\TestNumpyMemoryLeak.java to bui
ld\java\jep.test.src\test\java\jep\test\numpy\example\TestNumpyMemoryLeak.java
    copying src\test\java\jep\test\numpy\example\TestNumpyProdLost.java to build
\java\jep.test.src\test\java\jep\test\numpy\example\TestNumpyProdLost.java
    copying src\test\java\jep\test\numpy\example\TestScipyFreeze.java to build\j
ava\jep.test.src\test\java\jep\test\numpy\example\TestScipyFreeze.java
    copying src\test\java\jep\test\synchronization\TestCrossLangSync.java to bui
ld\java\jep.test.src\test\java\jep\test\synchronization\TestCrossLangSync.java
    copying src\test\java\jep\test\types\TestFieldTypes.java to build\java\jep.t
est.src\test\java\jep\test\types\TestFieldTypes.java
    copying src\test\java\jep\test\types\TestMethodTypes.java to build\java\jep.
test.src\test\java\jep\test\types\TestMethodTypes.java
    copying src\test\java\jep\test\types\TestStaticFieldTypes.java to build\java
\jep.test.src\test\java\jep\test\types\TestStaticFieldTypes.java
    copying src\test\java\jep\test\types\TestStaticMethodTypes.java to build\jav
a\jep.test.src\test\java\jep\test\types\TestStaticMethodTypes.java
    running build_jar
    copying src/main/resources/jep/classlist_7.txt to build/java/jep
    error: [Errno 2] No such file or directory: 'src/main/resources/jep/classlis
t_7.txt'

    ----------------------------------------
Command "C:\Python\python.exe -u -c "import setuptools, tokenize;__file__='C:\\U
sers\\p998twy\\AppData\\Local\\Temp\\pip-install-3bvir3px\\jep\\setup.py';f=geta
ttr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.clos
e();exec(compile(code, __file__, 'exec'))" install --record C:\Users\p998twy\App
Data\Local\Temp\pip-record-tcgcn3y0\install-record.txt --single-version-external
ly-managed --compile" failed with error code 1 in C:\Users\p998twy\AppData\Local
\Temp\pip-install-3bvir3px\jep\

**Comment by ndjensen** [comment]
Given the timing and that Jep 3.8.0 released yesterday, I just want to make sure that your pip install is trying to install Jep 3.8.0.  Can you confirm this?  I probably created the tar.gz file for pypi.org incorrectly.  :-(

**Comment by ndjensen** [comment]
I confirmed that the jep-3-8-0.tar.gz is missing those files.  Sorry.  Will work on a fix.  In the meantime use github to clone or download 3.8.0 as that should work.

**Comment by ndjensen** [comment]
Can you try again with pip?  Jep is now at 3.8.1 with the missing files included.  I'm having trouble testing pip on my machine right now.
