### ISSUE TITLE
Crash (PyErr_Restore) when re-executing sbt test

### ISSUE THREAD

**Issue by aitorhh** [ninia/jep#152]
- OS Platform, Distribution, and Version: Ubuntu 16.04.5 LTS 
- Python Distribution and Version: pyenv - 3.6.5
- Java Distribution and Version: Openjdk 8
- Jep Version: 3.8.2
- Python packages used (e.g. numpy, pandas, tensorflow): numpy

In my code, I have a simple test case to check that Jep and the libraries that are used are working fine. I basically run with `sbt "~testOnly *JepSimpleSpec".

The first execution works fine but the second time I always get a crash:
```
[hs_err_pid31112.log](https://github.com/ninia/jep/files/2289683/hs_err_pid31112.log)
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f2ce3316981, pid=31112, tid=0x00007f2cbaac0700
#
# JRE version: Java(TM) SE Runtime Environment (8.0_131-b11) (build 1.8.0_131-b11)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.131-b11 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libpython3.6m.so.1.0+0x17c981]  PyErr_Restore+0x31
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /home/aitorhh/workspace/app/app-core/hs_err_pid31112.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```
/usr/share/sbt/bin/sbt-launch-lib.bash: line 58: 31112 Aborted                 (core dumped) "$@"

**Comment by bsteffensmeier** [comment]
This was discussed on #126, and I believe sbt requires a forked JVM for jep.

**Comment by aitorhh** [comment]
Thanks for pointing out to the duplication... I missed it!
