### ISSUE TITLE
Can't find jep jars in maven repository

### ISSUE THREAD

**Issue by sampan-dong** [ninia/jep#159]
- OS Platform, Distribution, and Version:
- Python Distribution and Version:
- Java Distribution and Version:
- Jep Version:
- Python packages used (e.g. numpy, pandas, tensorflow):

**Comment by bsteffensmeier** [comment]
http://repo1.maven.org/maven2/black/ninia/jep/3.8.2/

**Comment by ndjensen** [comment]
I added an answer to the FAQ on the wiki.  Closing ticket.
