### ISSUE TITLE
Feature Request: Allow for setting of working directory of python script

### ISSUE THREAD

**Issue by pirocks** [ninia/jep#162]
- OS Platform, Distribution, and Version: All, though Linux is most important
- Python Distribution and Version: python2
- Java Distribution and Version: java 1.8.0_181
- Jep Version: A future one
- Python packages used (e.g. numpy, pandas, tensorflow): n/a

Title almost says it all. I've tried using `System.setProperty("user.dir", workingDirectory.absolutePath);`, but that hasn't worked. This is useful for python script which generate files into a working directory.

**Comment by bsteffensmeier** [comment]
Can you just use `jep.eval("os.chdir(" + workingDirectory.absolutePath + ")");`? I don't think we could do anything different than that from within jep so I don't see any benefit to adding something to jep.

**Comment by pirocks** [comment]
Sorry, for some reason I didn't think of changing the working directory from python. That would be a much better solution.
