### ISSUE TITLE
Bug in convert_jdndarray_pyndarray().

### ISSUE THREAD

**Issue by karpierz** [ninia/jep#165]
- OS Platform, Distribution, and Version: All
- Python Distribution and Version: 3.6
- Java Distribution and Version: Oracle Java 1.8
- Jep Version: 3.8.2
- Python packages used: numpy

Bug in convert_jdndarray_pyndarray().

Trivial patch:
```
--- jep-master.org/src/main/c/Jep/jep_numpy.c	2018-08-10 19:19:42.000000000 +0200
+++ jep-master/src/main/c/Jep/jep_numpy.c	2018-09-19 17:33:08.555548500 +0200
@@ -503,7 +503,7 @@
     if (!init_numpy()) {
         return NULL;
     }
-    if (!JNI_METHOD(dndarrayGetDims, env, JEP_NDARRAY_TYPE, "getDimensions",
+    if (!JNI_METHOD(dndarrayGetDims, env, JEP_DNDARRAY_TYPE, "getDimensions",
                     "()[I")) {
         process_java_exception(env);
         return NULL;
```
Thanks,
Adam Karpierz

**Comment by ndjensen** [comment]
Thank you for spotting this and reporting it.  I'm guessing it luckily works today since getDimensions() is on the super class and there's only one instance of the method getDimensions().  Regardless, it needs to be fixed.

**Comment by bsteffensmeier** [comment]
Fix is in dev_3.9 with d835aad
