### ISSUE TITLE
RecursionError maximum recursion depth exceeded when loading model

### ISSUE THREAD

**Issue by isaacmg** [ninia/jep#172]
- OS Platform, Distribution, and Version:
Mac OS X
- Python Distribution and Version:
Python 3.6
- Java Distribution and Version:
jdk 8
- Jep Version:
3.8.2 from Maven
- Python packages used (e.g. numpy, pandas, tensorflow):
PyTorch, AllenAI
Running the following code 
```java 
try{
            // Load Jep
            Jep jep = new Jep();
            jep.eval("import sys");
            jep.eval("sys.setrecursionlimit(1500)");
            jep.eval("sys.argv  = ['']");
            jep.eval("from allennlp.predictors.predictor import Predictor");
            jep.eval("the_pred = Predictor.from_path(\"https://s3-us-west-2.amazonaws.com/allennlp/models/srl-model-2018.05.25.tar.gz\")");

            jep.eval("filename = os.path.realpath('.')");
            Object result1 = jep.getValue("filename");
            System.out.println(result1);

        }
        catch(Exception e){
            e.printStackTrace();


        }
```
Produces this error
```
jep.JepException: <class 'RecursionError'>: maximum recursion depth exceeded in __instancecheck__
	at /anaconda/lib/python3.6/typing.__eq__(typing.py:759)
	at /anaconda/lib/python3.6/typing.__eq__(typing.py:760)
	at /anaconda/lib/python3.6/typing.__eq__(typing.py:760)
	at /anaconda/lib/python3.6/typing.__eq__(typing.py:760)
	at /anaconda/lib/python3.6/typing.__eq__(typing.py:760)
	at /anaconda/lib/python3.6/typing.__eq__(typing.py:760)
	at /anaconda/lib/python3.6/typ
```

Equivalent Python code runs fine
```python
from allennlp.predictors.predictor import Predictor
predictor = Predictor.from_path("https://s3-us-west-2.amazonaws.com/allennlp/models/srl-model-2018.05.25.tar.gz")
```
I updated the recursion depth limit because I wanted to see if that would fix it but it didn't. Also, the sys initialization was a fix I found from some else's issue for the argv error.

**Comment by bsteffensmeier** [comment]
Do you have the top of the stack trace, before it got stuck in typing.py?

**Comment by bsteffensmeier** [comment]
This appears to be a bug in python: https://bugs.python.org/issue29246

Is it possible for you to upgrade to python 3.6.1 or higher?

That doesn't explain why it works in regular python, something is getting initialized slightly differently but hopefully it won't matter if you can avoid hitting the python bug.

**Comment by isaacmg** [comment]
I had to create a new conda environment (to update Python)  but JEP seems to be still using my old conda environment. How do I make JEP use my new conda 3.7.1 environment? Right now I'm just using PYTHONHOME=/anaconda

**Comment by bsteffensmeier** [comment]
Did you rebuild jep in the new environment?

PYTHONHOME is only used as a last resort if libjep is not found anywhere else. So if you expect PYTHONHOME to be used ensure that you are not setting java.library.path, LD_LIBRARY_PATH and LD_PRELOAD, if any of those are set, ensure they are set to the new python.

I would recommend debugging into jep.LibraryLocator, this class is responsible for finding libjep, and possibly libpython based off the value in PYTHONHOME, so it might provide some insight as to why a particular python is chosen. In general it expects to find libjep at `$PYTHONHOME/lib/site-packages/jep/libjep.jnilib`, so in your case that would be `/anaconda/lib/site-packages/jep/libjep.jnilib`, is this library the version you are expecting? libpython should be at `$PYTHONHOME/lib/libpythonX.Y.so`. Is it loading the libpython at `/anaconda/lib/libpython3.7.so`?

**Comment by isaacmg** [comment]
Thanks I got it working.
