### ISSUE TITLE
JepException: <class 'ModuleNotFoundError'>: No module named 'math'

### ISSUE THREAD

**Issue by pedro-roberto** [ninia/jep#174]
- OS Platform, Distribution, and Version: Ubuntu 18.04.1 LTS
- Python Distribution and Version: 3.7.0
- Java Distribution and Version: Oracle JDK 1.8.0
- Jep Version: 3.8.2
- Python packages used (e.g. numpy, pandas, tensorflow): numpy

When I import numpy in python/jep (on a terminal) it works but when I do it in java I get the error in the title.

```
public static void main(String []args)  throws JepException {
Jep jep = new Jep();
jep.eval("from java.lang import System");
jep.eval("import numpy");
}

Exception in thread "main" jep.JepException: <class 'ModuleNotFoundError'>: No module named 'math'
	at /home/pedro/miniconda3/lib/python3.7/site-packages/numpy/lib/__init__.<module>(__init__.py:3)
	at /home/pedro/miniconda3/lib/python3.7/site-packages/numpy/add_newdocs.<module>(add_newdocs.py:13)
	at /home/pedro/miniconda3/lib/python3.7/site-packages/numpy/__init__.<module>(__init__.py:142)
	at <string>.<module>(<string>:1)
	at jep.Jep.eval(Native Method)
	at jep.Jep.eval(Jep.java:507)
	at com.waron.matrix.jythonExperiments.main(jythonExperiments.java:36)
```

Other attempts:

```
public static void main(String []args)  throws JepException {
Jep jep = new Jep(new JepConfig().addSharedModules("numpy"));
jep.eval("from java.lang import System");
jep.eval("a = numpy.array([1,2])");
}

Exception in thread "main" jep.JepException: <class 'NameError'>: name 'numpy' is not defined
	at <string>.<module>(<string>:1)
	at jep.Jep.eval(Native Method)
	at jep.Jep.eval(Jep.java:507)
	at com.waron.matrix.jythonExperiments.main(jythonExperiments.java:36)
```

Same type of error occurs when replacing `numpy.array` with `np.array` or `array`

I compared the `sys.path` of "normal" python and Jep's python and I obtain the same result:

```
Jep jep = new Jep();
jep.eval("from java.lang import System");
jep.eval("import sys");
jep.eval("System.out.println(sys.path)");

[/home/pedro/miniconda3/lib/python37.zip, /home/pedro/miniconda3/lib/python3.7, /usr/lib/python3.7/lib-dynload, /home/pedro/miniconda3/lib/python3.7/site-packages]
```

python
```
>> import sys
>> sys.path
['', '/home/pedro/miniconda3/lib/python37.zip', '/home/pedro/miniconda3/lib/python3.7', '/home/pedro/miniconda3/lib/python3.7/lib-dynload', '/home/pedro/miniconda3/lib/python3.7/site-packages']
```

I have tried to reinstall numpy.
Have also tried to install numpy from with the jep sub-interpreter by running:
```
jep.eval("import pip");
jep.eval("pip._internal.main(['install','numpy'])");
jep.eval("pip.main(['install','numpy'])");

Exception in thread "main" jep.JepException: <class 'AttributeError'>: module 'pip' has no attribute '_internal'
	at <string>.<module>(<string>:1)
	at jep.Jep.eval(Native Method)
	at jep.Jep.eval(Jep.java:507)
	at com.waron.matrix.jythonExperiments.main(jythonExperiments.java:44)
```

Don't know if this happens because I don't set the environment variable [LD_PRELOAD](https://github.com/ninia/jep/wiki/Linux#ld_preload). I don't understand what LD_PRELOAD is supposed to be set to. I have set it to `LD_LIBRARY_PATH="/home/pedro/miniconda3/lib/python3.7/site-packages/jep"` but it didn't work.

My numpy can be found in `/home/pedro/miniconda3/lib/python3.7/site-packages/numpy`

Please help. I need to use numpy from Java to do some large matrix multiplications, which is much faster with numpy.

**Comment by pedro-roberto** [comment]
I had looked into `./jep-3.8.2/build/scripts-3.7/jep` but as I didn't see any `LD_PRELOAD` I thought I was on the wrong script. So now I added `eho $LD_PRELOAD` in the second to last line of this script and obtained `/home/pedro/miniconda3/lib/libpython3.7m.so`. So I set my PD_PRELOAD to `/home/pedro/miniconda3/lib`

I also get this error message when I start the jep script, but numpy works there:
`ERROR: ld.so: object '/home/pedro/miniconda3/lib' from LD_PRELOAD cannot be preloaded (cannot read file data): ignored.`

**Comment by bsteffensmeier** [comment]
LD_PRELOAD needs to be set to the file that should be loaded, not the directory containing the file, so in your case it would be the full path `/home/pedro/miniconda3/lib/libpython3.7m.so`

**Comment by pedro-roberto** [comment]
yes, I tried both.

**Comment by pedro-roberto** [comment]
Ok, I think I solved it. Had to rename `/usr/lib/python3.7/lib-dynload/` so jep doesn't use the file `_gdbm.cpython-37m-x86_64-linux-gnu.so`. Many thanks!
