### ISSUE TITLE
"A fatal error has been detected by the Java Runtime Environment" after the first Jep instance

### ISSUE THREAD

**Issue by pedro-roberto** [ninia/jep#177]
- OS Platform, Distribution, and Version:  Ubuntu 18.04.1 LTS
- Python Distribution and Version: 3.7.0
- Java Distribution and Version: Oracle JDK 1.8.0
- Jep Version: 3.8.2
- Python packages used (e.g. numpy, pandas, tensorflow): numpy, pandas, math, time

After creating a first Jep instance, running a python script that uses the packages numpy, pandas, math and time, and closing that instance almost all the subsequent jep instances get a fatal error when trying to run the same script with difference arguments.  When the fatal error doesn't occur I get the following `Jep Exception`:

```
jep.JepException: <class 'SystemError'>: initialization of hashtable did not return an extension module
	at /home/pedro/miniconda3/lib/python3.7/site-packages/pandas/__init__.<module>(__init__.py:26)
```

Here is an example of the fatal error message:

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f177af10b30, pid=13777, tid=0x00007f17e05b5700
#
# JRE version: Java(TM) SE Runtime Environment (8.0_191-b12) (build 1.8.0_191-b12)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.191-b12 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libpython3.7m.so.1.0+0xa6b30]  PyType_IsSubtype+0x0
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /home/pedro/Development/waronfees/hs_err_pid13777.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```

Some error logs attached.

[hs_err_pid11662.log](https://github.com/ninia/jep/files/2678595/hs_err_pid11662.log)
[hs_err_pid12757.log](https://github.com/ninia/jep/files/2678596/hs_err_pid12757.log)
[hs_err_pid12865.log](https://github.com/ninia/jep/files/2678597/hs_err_pid12865.log)
[hs_err_pid13192.log](https://github.com/ninia/jep/files/2678598/hs_err_pid13192.log)
[hs_err_pid13646.log](https://github.com/ninia/jep/files/2678599/hs_err_pid13646.log)
[hs_err_pid14101.log](https://github.com/ninia/jep/files/2678600/hs_err_pid14101.log)

Let me know if you would like to take a look at the core dump, it has about 1 GB in size.

**Comment by bsteffensmeier** [comment]
Many cpython exxtension, including numpy, are not compatible with python sub-interpreters, each Jep instance is a python sub-interpreter. The simplest way to avoid problems is to use the SharedInterpreter class instead of Jep. Another option is to set up any incompatible extensions as shared modules in the jep config. See the wiki, specifically the section on [numpy-gotchas](https://github.com/ninia/jep/wiki/Numpy-Usage#numpy-gotchas)and the section on [cpython extensions](https://github.com/ninia/jep/wiki/Workarounds-for-CPython-Extensions).

**Comment by pedro-roberto** [comment]
I was instanciating jep as `jep = new Jep(new JepConfig().addSharedModules("numpy"));`, now that I added pandas `jep = new Jep(new JepConfig().addSharedModules("numpy", "pandas"));`, it works.

By the way, how does one create a shared interpreter? Do you mean creating a single jep instance and sharing it between threads?

**Comment by bsteffensmeier** [comment]
http://ninia.github.io/jep/javadoc/3.8/jep/SharedInterpreter.html

**Comment by bsteffensmeier** [comment]
This has been resolved.
