### ISSUE TITLE
Unable to run jep: Fatal Python error: No module named 'encodings'

### ISSUE THREAD

**Issue by Fraer** [ninia/jep#178]
Hello, on mac os 10.14.2, i've installed python 3.6 from https://www.python.org/ftp/python/3.6.8/python-3.6.8-macosx10.9.pkg

Jep 3.8.2 is correctly installed:
```
> /Library/Frameworks/Python.framework/Versions/3.6/bin/pip3 install jep
Collecting jep
Installing collected packages: jep
Successfully installed jep-3.8.2
```

But when i run the jep:
```
Fatal Python error: Py_Initialize: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'
```

What should i do ?

**Comment by Fraer** [comment]
And when i try to run a Jep eval from scala with java.library.path set to 
-Djava.library.path=-Djava.library.path=/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/jep

i get 

```
server jep.JepException: <class 'ImportError'>: Python is not installed as a framework. The Mac OS X backend will not be able to function correctly if Python is not installed as a framework. See the Python documentation for more information on installing Python as a framework on Mac OS X. Please either reinstall Python as a framework, or try one of the other backends. If you are using (Ana)Conda please install python.app and replace the use of 'python' with 'pythonw'. See 'Working with Matplotlib on OSX' in the Matplotlib FAQ for more information.
```

**Comment by bsteffensmeier** [comment]
The first thing to do is see if the jep script is able to run, this script should be located at /Library/Frameworks/Python.framework/Versions/3.6/bin/jep and running it will give a python prompt similar to running python through the command line. If the script works you can check out the environment and command it is using to see how to set an environment for jep.

The simplest way to setup the environment is to set the PYTHON_HOME environmental variable, I don't use Mac OS so I''m not sure exactly which path to use but I would guess `/Library/Frameworks/Python.framework/Versions/3.6/`.

**Comment by PradeepBadiger** [comment]
It happened to me on a linux VM where i had the jep package installed under /usr/**local**/lib64/python3.6/site-packages. Python3.6 was installed under /usr/lib64. I made use of smart library loading and it threw an error during initialization when i set the python home that follows to the jep package.

**Comment by bsteffensmeier** [comment]
@PradeepBadiger I think for your use case you would need to set a separate prefix and exec_prefix in PYTHONHOME as described in the [python documention](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONHOME). Can you start an ordinary python3.6 interpreter on your linux vm and tell us what the values of sys.prefix and sys.exec_prefix are? Unfortunatly jep does not support that format of PYTHONHOME for finding libjep so you will need to use LD_LIBRARY_PATH or -Djava.library.path to find libjep. We should add support for the multipath PYTHONHOME to LibraryLocator

**Comment by ndjensen** [comment]
Target for 3.9.1 or 4.0.0, whichever comes first.

**Comment by PradeepBadiger** [comment]
Hi @ndjensen - This is what i see.

`[root@automation02 site-packages]# python3.6`
`Python 3.6.8 (default, Apr 25 2019, 21:02:35)`
`[GCC 4.8.5 20150623 (Red Hat 4.8.5-36)] on linux`
`Type "help", "copyright", "credits" or "license" for more information.`
`>>> import sys;`
`>>> print(sys.prefix)`
`/usr`
`>>> print(sys.exec_prefix);`
`/usr`
`>>>`

For now, I kind of work around this issue by installing the package in the actual python home location of /usr/lib64/python3.6 using below command.

`python3.6 -m pip install --install-option="--prefix=/usr" jep`

**Comment by ndjensen** [comment]
I retract my statement about targeting a fix for a release, as the idea that sys.prefix and sys.exec_prefix are different is now shown to be incorrect.  At present we cannot recreate this problem and don't know how to fix it.

**Comment by ndjensen** [comment]
This may be irrelevant because the original ticket is at runtime and this error is at build time, but when building on travisCI with the Python 3.8-dev and Python 3.9-dev branches, we received that error.
https://travis-ci.org/github/ninia/jep/jobs/690178200
https://travis-ci.org/github/ninia/jep/jobs/690185988

**Comment by ndjensen** [comment]
https://bugs.python.org/issue38236 added extra output to Python 3.8 and 3.9 when this occurs.  Hopefully the extra output helps developers figure out what is going on.

**Comment by ndjensen** [comment]
Possibly related to #284

**Comment by ndjensen** [comment]
I got this on macOS with Python 3.7 and Jep 4.0 in a virtualenv.  The fix was to **not** set PYTHONHOME which then caused the jep script to not see the virtualenv's site-packages directory.
