### ISSUE TITLE
Issue With Keras

### ISSUE THREAD

**Issue by Jbiloki** [ninia/jep#180]
- OS Platform, Distribution, and Version: Mac OSX
- Python Distribution and Version: 3.7
- Java/Scala Distribution and Version: 2.11.8 (Scala)
- Jep Version: 3.8.2
- Python packages used (e.g. numpy, pandas, tensorflow): Keras, Tensorflow, Numpy

Upon running a script that creates an object to hold a feed forward model I get this return:

> jep.JepException: <class 'ImportError'>: Interpreter change detected - this module can only be loaded into one interpreter per process.

There is a custom function that builds a jep instance per string as this is a multi threaded application. If the current calling thread does not have a jep instance one is created:
```
val jep = new Jep(new JepConfig().addSharedModules("numpy", "tensorflow"))
        jep.eval("from nltk.tokenize import word_tokenize")
        jep.eval("from nltk.stem import PorterStemmer")
        jep.eval("import git")
        jep.eval("import sys")
        jep.eval("import os")
        jep.eval("sys.path.append(os.getcwd()+\"/src/main/python/\")")
        jep.eval("from Keras_API.Deep_CRF import Deep_CRF")
        jep.eval("import re")
        jep.eval("import subprocess")
        jep.eval("current_repo = git.Repo('.')")
        jeps += (currentThreadId -> jep)
```

**Comment by ndjensen** [comment]
That error is not coming from Jep.  Something you're importing, probably Keras, is creating that ImportError.  Hopefully Jep gave you a nice stacktrace to trace which import failed, and you could look into why that project did that.  A developer must have been extra careful about maintaining state and put in that exception as protection to prevent this sort of thing.

Your example code does not show keras as a shared module.  I doubt that will fix it, but it's something to try.

**Comment by bsteffensmeier** [comment]
You could also try using SharedInterpreter instead of a regular Jep instance so you don't have to figure out which modules need to be shared.

**Comment by Jbiloki** [comment]
Thank you for your feedback, after reading through the code, I used SharedInterpreter (also noted @bsteffensmeier mentioned this as well later) With some changes to the python side to allow for tensorflow to be multi threaded it is working. Thank you.

**Comment by Jbiloki** [comment]
I have an update, using shared interpreter causes threads to live forever and taking up memory, is there some way to deal with this issue?

**Comment by bsteffensmeier** [comment]
Anytime you use Jep there is a single main thread started to host the main python environment. Currently there is no way to stop this thread. I have not looked at the details of that code in awhile but I believe it is impossible or very difficult to restart python in a process after shutting down the main thread. Other than that one thread I would not expect any other threads to stay alive. Are you calling the close() method on the SharedInterpreters or using try-with-resource blocks to ensure the interpreters are closed? Can you post a small example program that I could use to try to recreate your problem?

**Comment by ndjensen** [comment]
Any update, @Jbiloki?

**Comment by Jbiloki** [comment]
@ndjensen Due to endless issues with Jep and limited support we moved on to other solutions.
