### ISSUE TITLE
Jep MultiThread

### ISSUE THREAD

**Issue by Jbiloki** [ninia/jep#181]
Working on a multi-threaded Java application is there a way to use one interpreter shared through each thread or does SharedInterpreter() only allow inner thread interactions? If so, is there an efficient way to implement Jep in a multi-threaded environment.

**Comment by bsteffensmeier** [comment]
Each Jep or SharedInterpreter can be used only only one thread. For a multiithreaded environment you just create a new Jep or SharedInterpreter on each thread.

**Comment by Jbiloki** [comment]
Is it possible to have a main Jep thread that other threads can access?

**Comment by bsteffensmeier** [comment]
Each Jep or SharedInterpreter can be used on only one thread. Jep usage can be mixed with any other Java code so if you need access form other threads I would recommend setting up some Java threading code so that you can request execution on any thread and it will be transfered to the thread with Jep for execution.

**Comment by bsteffensmeier** [comment]
Closing because there is no issue with jep.

**Comment by aghasemi** [comment]
Hello,

I had the same "issue"(in a web application), and the way I solved it was using a [Single Thread Executor](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/Executors.html#newSingleThreadExecutor--), hence ensuring that the Interpreter is created in the same thread where Python code is executed. One needs to pass all Python-related code through the `submit` method of the executor, which returns a `Future` object, and then call `get` on the `Future` object if the computation has an output.

Thought it may be useful for someone, here or in issue #30.
