### ISSUE TITLE
Incompatible library version

### ISSUE THREAD

**Issue by JoseCF** [ninia/jep#182]
- OS Platform, Distribution, and Version: MacOS Mojave 10.14.2
- Python Distribution and Version: Python 3.6.8 :: Anaconda, Inc.
- Java Distribution and Version: Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
- Jep Version: 3.8.2
- Python packages used (e.g. numpy, pandas, tensorflow):

I'm trying to execute JEP from Java, so i build from source with ./setup.py build install, later i put LD_LIBRARY_PATH and i have this trace:

Exception in thread "main" java.lang.UnsatisfiedLinkError: /Users/xxxx/anaconda3/lib/python3.6/site-packages/jep/jep.cpython-36m-darwin.so: dlopen(/Users/xxxx/anaconda3/lib/python3.6/site-packages/jep/jep.cpython-36m-darwin.so, 1): Library not loaded: @rpath/libpython3.6m.dylib
  Referenced from: /Users/xxxx/anaconda3/lib/python3.6/site-packages/jep/jep.cpython-36m-darwin.so
  **Reason: Incompatible library version: jep.cpython-36m-darwin.so requires version 3.6.0 or later, but jep.cpython-36m-darwin.so provides version 0.0.0**

Any suggestion????

**Comment by ndjensen** [comment]
I think it has something to do with using Anaconda on macOS.  I don't know where the 0.0.0 comes from.  My best guess is you compiled Jep against one version of Python and are running it against another.  Have a look at these:

https://github.com/scrapy/scrapy/issues/2703
https://github.com/ContinuumIO/anaconda-issues/issues/1266
https://stackoverflow.com/questions/23172384/lxml-runtime-error-reason-incompatible-library-version-etree-so-requires-vers

We don't officially support Anaconda, though others have gotten it to work.

**Comment by ndjensen** [comment]
Closing since the related ticket 568 for polynote is closed.
