### ISSUE TITLE
Nested Complex Type Support

### ISSUE THREAD

**Issue by miaoever** [ninia/jep#183]
Hi Team,

According to the document, currently the Jep could automatically map between the Java Complex type (Map, List...) and the corresponding Python object. However, if it's nested type, say Map[String, Map[String, Long]] in Java,  it seems that we only get the Dict[str, PyObject] without any actual type information for the value. Is there any chance we can support this scenario?

BTW, I'm happy to contribute a pull request for this feature if it's missing right now, please give me some clues about where/how should I implement it.

Thanks.

**Comment by bsteffensmeier** [comment]
What document are you refering to? What version of Jep are you using? On Jep 3.8 if you pass a Map<String,Map<String,Long>> from Java into Python you should get a PyJMap object in Python. This object will let you call Java methods to access elements or you can index into it like a Python dict. Either way when you retrieve elements you will get another layer of PyJMap objects which you can use to gt to the Longs. If you are having a speciic problem a code example demonstrating the problem would be helpful.
