### ISSUE TITLE
Unable to pass path to jep.runscript()

### ISSUE THREAD

**Issue by COA1IMB** [ninia/jep#184]
Currently, jep.runscript() expects a path. Which is not working for me, as my python script was packaged into my jar file. Therefore my URL looks something like this: 

jar:file:/C:/Users/coa1imb/Desktop/jep-test-1.9.0-SNAPSHOT.jar!/script.py

As jep tries to do: new File(path) this will lead to an exception obviously.

Are there any known workarounds to solve this issue? 

- OS Platform, Distribution, and Version: Windows 10 
- Python Distribution and Version: 3.7
- Java Distribution and Version: 1.8
- Jep Version: 3.7
- Python packages used (e.g. numpy, pandas, tensorflow):

**Comment by bsteffensmeier** [comment]
You will need to extract the file to a temporary location so you can use runScript. Or you could read the script into a string using java and use jep.exec to execute the python, see #55 for help on executing python scripts using exec.

**Comment by COA1IMB** [comment]
Thanks for the quick response, turns out that exec is the better choice for me.
