### ISSUE TITLE
LibraryLocator ignores the python home configured in PyConf when try to load libraries

### ISSUE THREAD

**Issue by nfalco79** [ninia/jep#188]
I'm try to load DLLs using the PyConf because based on the user preference I will deploy compiled libraries for a specific version of Python defined by user configuration.

I had set the PyConf.pythonHome but that path is ignored in searchPythonPath method but taken into account other methods like in searchSitePackages and searchUserSitePackages methods.
Actual code 
```
private boolean searchPythonPath() {
        if (ignoreEnv) {
            return false;
        }
        String pythonPath = System.getenv("PYTHONPATH");
        if (pythonPath != null) {
            ...
        }
        return false;
    }
```

I expect something like in searchSitePackages
```
        String pythonHome = this.pythonHome;
        if (pythonHome == null && !ignoreEnv) {
            pythonHome = System.getenv("PYTHONHOME");
        }
```

**Comment by bsteffensmeier** [comment]
Can you explain your use case in more detail, specifically where is your DLL installed?

LibraryLocator attempts to load libjep from within the jep python module so it only checks locations where python modules will be found by python. When jep is installed under python home it should be installed under site packages, this is why site packages uses python home. The purpose of the searchPythonPath method is to search for modules python will find using the PYTHONPATH environmental variable. When python loads libraries the python home is irrelevant when it processes PYTHONPATH so Jep does the same thing.

**Comment by nfalco79** [comment]
I'm in OSGi environment. The DLL are shippe with the bundle. Usually we define the Bundle-NativeCode header in the manifest so that is it automatically loaded when the bundle starts.
Something like:
<Bundle-NativeCode>
    lib/jep.dll;osname=Win32;processor=x86_64,
    lib/libjep.dylib;osname=MacOSX;processor=x86_64,
    lib/libjep.so;osname=Linux;processor=x86_64
</Bundle-NativeCode>
`
We deploy jep python scripts on a WAS work directory and configure the JepConfig.setIncludePath with that folder.

Recently we update jep from 3.5.2 with DLLs compiled only for python 3.4 to version 3.8.2 and we would make changes back compatible. I mean we would make jep 3.8.2 working with both python 3.4 and python 3.6 using a configuration property that describe which python is installed in the system. We could not use the same DLLs with both python version maybe because there is a check at runtime.
So instead use the Bundle-NativeCode header we would unzip the DLLs in the work area for the specified python and load them. So the EBA/EAR could be shipped without any IT operation (like now) to install DLLs or other software on the WAS machine.

**Comment by bsteffensmeier** [comment]
Thanks for the extra explanation.

I do not think LibraryLocator should look for libraries in python home, the current behaviour is to look everywhere the jep module could be installed and load it from there. Since python modules are not loaded from python home I do not think we should be looking there.

Since you are already unpacking things into python home, one solution may be to include the jep python files with your jar and then you could unpack the entire module into the python site packages directory where python and LibraryLocator would both find it.

I would also be in favor of modifying LibraryLocator and adding a static method to set the exact location of the library file. You are not the first person to try unpacking the libraries from a jar, such a method would provide flexibility so the library can be be unpacked wherever is most convenient for any particular environment.

**Comment by nfalco79** [comment]
> I do not think LibraryLocator should look for libraries in python home, the current behaviour is to look everywhere the jep module could be installed and load it from there. Since python modules are not loaded from python home I do not think we should be looking there.

In wiki is documented so:
>New in version 3.8: Jep will try harder to find the native library for you if you set the PYTHONHOME environment variable. When using Anaconda, set PYTHONHOME to your Anaconda installation directory, e.g. $(HOME)/anaconda3

I notice PyConf allows setup the pythonHome path so was naturally think that configuration was valid for the native code lookup too. Other reason is that all other method use the configured pythonHome by PyConf and than faultback on the PYTHONHOME environment variable. The searchPythonPath method used to lookup the native libraries is the only one different so I thought was a mistake.

>I would also be in favor of modifying LibraryLocator and adding a static method to set the exact location of the library file

Scripts we extract are:
* console.py
* java_import_hook.py
* jdbc.py
* redirect_streams.py
* shared_modules_hook.py
* version.py
that are not included in the jep.jar by default. We add all of them and native code in the repackage

**Comment by bsteffensmeier** [comment]
If you are already unpacking all of those python files, then I recommend unpacking them into a jep directory under the site-packages directory in your python installation. The LibraryLocator will use pythonHome from PyConf to find the site-pacakges directory. The process LibraryLocator uses is described in more detail in the [release notes for Jep 3.8](https://github.com/ninia/jep/blob/master/release_notes/3.8-notes.rst#smarter-library-loading)

> If the native Jep Library is not found, then Jep will attempt to find it in the jep module. To find the jep module it looks in the locations in the PYTHONPATH environmental variable and also in the site-packages directory which is found relative to the PYTHONHOME environmental variable. If the Jep Library can be found in one of those locations then it is no longer necessary to set the LD_LIBRARY_PATH and/or java.library.path to the location of the Jep library.

That wiki entry indicates that setting PYTHONHOME will help find the native library, it does not indicate you can unpack the native library into PYTHONHOME. It is intended to help the simple use case of someone doing `pip install jep` which installs the jep native library in site-packages under PYTHYONHOME. For your use case I recommend you mirror that simple case and unpack the python files and jep library in the same spot where they are installed by default.

**Comment by ndjensen** [comment]
> I would also be in favor of modifying LibraryLocator and adding a static method to set the exact location of the library file. You are not the first person to try unpacking the libraries from a jar, such a method would provide flexibility so the library can be be unpacked wherever is most convenient for any particular environment.

@bsteffensmeier, I think we should proceed with that idea for 3.9.
