### ISSUE TITLE
How to Compile a script using JEP

### ISSUE THREAD

**Issue by Seejal** [ninia/jep#191]
Hi,

Have created a Python Editor and would like to give an option to compile the script, where JEP doesn't seems to have any such option to do so.
The basic requirement is to verify the script (i.e. check for any syntax error) before even trying to execute or save the script.

The available options that I could find is only "runScript" & "eval" where runScript takes file as input parameter, which I cannot use, so the option left is eval which will execute the script.

Have used Python 3.7, JEP 3.8.2, Java 1.8

**Comment by bsteffensmeier** [comment]
Use Jep.set() to make a python str from your script and then jep.eval() to run the [compile builtin function](https://docs.python.org/3/library/functions.html#compile) from python.

```
jep.set("script", yourScriptString);
jep.eval("compile(string, '<string>', 'exec')")
```

**Comment by Seejal** [comment]
Thanks for the help, the above worked for me using (script in place of string in eval statement)

```
jep.set("**_script_**", yourScriptString);
jep.eval("compile(**_script_**, '<string>', 'exec')")
```
