### ISSUE TITLE
Direct memory support

### ISSUE THREAD

**Issue by pmjpawelec** [ninia/jep#192]
- OS Platform, Distribution, and Version: Ubuntu 16.04
- Python Distribution and Version: 3.5
- Java Distribution and Version: openjdk 8
- Jep Version: 3.8
- Python packages used (e.g. numpy, pandas, tensorflow): numpy

I tried to use DirectNPArray, but the example code from documentation results in:
`Exception in thread "main" jep.JepException: <class 'TypeError'>: 'jep.PyJObject' object does not support item assignment`

**Comment by bsteffensmeier** [comment]
The most likely cause is that numpy was not found at compile time in which case numpy support is disabled. If you look at the output of the build script when you install jep do you see text that says `numpy not found, running without numpy support` or do you see `numpy include found at ...`? If you see `numpy not found` then you can fix your issues by ensuring numpy is installed before installing jep.

**Comment by pmjpawelec** [comment]
I don't know about the output, but indeed, the reinstall using `pip install --no-cache-dir -I jep` helped with this issue.
