### ISSUE TITLE
JepException: <class 'ModuleNotFoundError'> running Jep with two files

### ISSUE THREAD

**Issue by pgschr** [ninia/jep#194]
- OS Platform, Distribution, and Version: Windows 10
- Python Distribution and Version: 3.7
- Java Distribution and Version: 1.8
- Jep Version: 3.8
- Python packages used (e.g. numpy, pandas, tensorflow): ---

I'm trying to run a Jep script that has to access a class that is in a different file. I get this error:

> JepException: <class 'ModuleNotFoundError'>: No module named '__main__.testjep2'; '__main__' is not a package

I have two classes in a `test` folder, `testjep.py` and `testjep2.py`:

`testjep2.py`:

```
class MyClass:
    x = 10
    y = 0
```

`testjep.py`:

```
from .testjep2 import MyClass


def test_function(j):
    entry = MyClass()
    return j + entry.x

```
(this code compiles in PyCharm)

And the java code (runs inside Wildfly EJB):

```
		try(Jep jep = new Jep()) {

		    jep.runScript("C:/path/test/testjep.py");
		    jep.eval("x = test_function(123)");
		    long y = (Long) jep.getValue("x");
		    System.out.println("Result is : " + y);
		} 
		catch (JepException e) {
			e.printStackTrace();
		}
```

I also set the system variable `LD_LIBRARY_PATH` as `C:/path/test` but I get the same error. How to make Jep load/locate the second file?

**Comment by bsteffensmeier** [comment]
I think you need to set your PYTHONPATH environmental variable, or you [jep include path](http://ninia.github.io/jep/javadoc/3.8/jep/JepConfig.html#setIncludePath-java.lang.String-) to point to `C:/path/test`. Also I don't think you can use a relative import from a script executed with `runScript()`

**Comment by pgschr** [comment]
I added the path (where the second file is located) to PYTHONPATH but I get the same error.  Also tried to use an absolute path with `from test.testjep2 import MyClass` and didn't work either. Any suggestions on how to include a second file?

**Comment by pgschr** [comment]
This did the trick (the con is that I have to add the path in the source code)
```
import sys
sys.path.append("C:/sofiana/projects/visualbank-py")
from test.testjep2 import MyClass
```

**Comment by ndjensen** [comment]
If you're using a `Jep` instance instead of a `SharedInterpreter` instance you can use `JepConfig.setIncludePath(...)` and it will do the same thing.  It just appends to sys.path.  https://github.com/ninia/jep/blob/v3.8.2/src/main/java/jep/Jep.java#L261

**Comment by bsteffensmeier** [comment]
> Adding "C:/test" to PYTHONPATH and declaring the import as absolute did the trick.

Closing because the issue was resolved
