### ISSUE TITLE
Tests fail in python 3.8 development builds

### ISSUE THREAD

**Issue by bsteffensmeier** [ninia/jep#198]
Any tests using jep_pipe fail on python 3.8 development builds. This is not an issue with the features those tests are testing but with the way we run the test in a subprocess. subprocess.Popen can no longer be used from the sub-interpreter where we run the tests. See https://bugzilla.redhat.com/show_bug.cgi?id=1706238 and https://bugs.python.org/issue34651

**Comment by bsteffensmeier** [comment]
Fixed in dev_3.9 under 93c1918

**Comment by bsteffensmeier** [comment]
3.9.0 has been released.

**Comment by ndjensen** [comment]
It looks like this was also fixed by a later version of Python 3.8 development.
