### ISSUE TITLE
Loading Jars / Packages

### ISSUE THREAD

**Issue by SoulSen** [ninia/jep#200]
- OS Platform, Distribution, and Version: Windows 10
- Python Distribution and Version: 3.7
- Java Distribution and Version: 1.8.0? 
- Jep Version: 3.8.2
- Python packages used (e.g. numpy, pandas, tensorflow): None

How could I load jar files or my own package within Python?

**Comment by ndjensen** [comment]
Jep is a Java library which needs to be run in a Java process.  You cannot use it from a Python process.  Like any Java process, it can find classes on the classpath that the ClassLoader has access to.
