### ISSUE TITLE
Features for Jep 4.0

### ISSUE THREAD

**Issue by ndjensen** [ninia/jep#202]
Jep 4.0 is planned for release in 2020 **or** later.  4.0 aims to clean out old API and add more notable API changes.  The ideas listed here are not a commitment, just a tracking point.  Some ideas are:

- Remove deprecated methods.  Make Jep type abstract so subclass must be instantiated.
- Remove Python 2 support. Will clean up C code.
- Remove Python 3.3, 3.4, 3.5 support. Will clean up C code.
- Change fallback last resort behavior of Jep.getValue() returning a string of the pyobject to instead return a PyObject object.
- JepException extends RuntimeException instead of Exception. Checked exceptions are not great.
- PyJType: The idea that the type of a PyJObject is a true Python Type, i.e. a Python type maps to a Java class.  For example, type(ArrayList) would be `java.util.ArrayList` instead of `PyJObject`.  Rather complicated, major roadblock is that `if (type(Object()) == Object().getClass()` works then `isinstance(Object.getClass(), Class)` won't work, and vice versa.  What to do?
- Better support for JPyObjects aka Java jep.python.PyObjects such as JPyList (jep.python.PyList extends jep.python.PyObject), JPyDict (jep.python.PyDict extends jep.python.PyObject), etc.  Also known as the reverse of the PyJList, PyJMap, PyJIterator, etc
- PEJ - Python Embedded Java: The reverse of Jep, a Python process with a JVM inside it.  Other open source projects already do this.
- Pluggable Java <-> Python type converters.  We have builtin converters for PyList <-> Java ArrayList, PyDict <-> Java HashMap, Python primitives <-> Java primitives.  We have custom converters for numpy support.  Converters should be detectable at build time and included as desired.  For example, someone could write a `pandas DataFrame` converter to a Java object, and contribute it back to the community.  But users would get to choose whether to build with pandas support or not.  Another example from a mailing list post is to convert a Python `numpy ndarray` to a `List<Float>` instead of a Java `NDArray`.  Users could write custom converters and choose which converters to build with.
- Simplify build by removing support for Python 2, Java 1.7, and Apple's JVM.  Contemplate moving to setuptools build, but we have trouble getting multiple environments to test in and could use help if we alter the build.
- Better API for pyjarray and pinning arrays (for example `with pyjarray.pin(): for loop`).  Pinning is slowing down primitive pyjarrays unless you're looping over contents.
- pyjarray interface should resemble python's built-in array interface (e.g. take a typecode to determine primitive type)

**Comment by ndjensen** [comment]
I'm going to add we should remove `Run.java`'s dependency on swing.  With the exception of swing, a quick glance through of the code shows that for Java 9+ we only need the module java.base so Jep could be run in a lightweight environment.  That may be overkill as the odds of developers making lightweight Java <-> CPython applications are probably not great.  Though it might also help with Android builds???

If someone is using the swing functionality of Run.java, I'd appreciate a comment on this ticket.

**Comment by ndjensen** [comment]
Polynote has the following in their documentation:

> Note that Jep is based on Java, not Scala. This means that when it wraps a Scala object as a PyJObject, you won’t get Scala sugar - things like multiple parameter lists, implicits, etc. - when you work with it in Python. This can limit your ability to use a lot of super-scala-stuff with Python.
 > Jep handles conversion from Python -> Scala and Polynote adds a little bit of sugar on top. 

We may want to attempt to better support Scala and said sugar, but I don't know enough to know how.

**Comment by jeremyrsmith** [comment]
@ndjensen I'm not sure it will be possible to support curried calls and implicits from within Python. At least, not without embedding the Scala compiler (which is no small commitment, believe me 😀 ) But if you want to try to do anything special for Scala then I'd be happy to pitch in! For example, on the Scala side we do have some useful Scala sugar that goes over jep; maybe it would make sense to extract that into a library...

**Comment by bsteffensmeier** [comment]
@jeremeysmith I don't know enough about scala to know exactly what we could add but I've wondered if we could basically hide some of the Java layer that Scala adds when accessing Scala object from Python.

For example I've spent time thinking about #124 dealing with Scala vars. If we wanted to add good Scala support in jep then I would think we want Scala vars to map directly to python fields like the author of that ticket requested. So when we do field assignment in python we would call the setter that Scala generated and similarly call the getter for field access. It would be entirely possible to look up Scala generated getters/setters for for field access but I would like to do it for only Scala objects and we cannot depend on scala directly.

For a Currying function from Scala being used in Python I assume you would need to do `f.apply(args)` to go through the java apply method. We could potentially detect currying functions and make them directly callable from Python, would that be more intuitive for scala users? Maybe we should be doing that for all functional interfaces anyway?

I'm not sure how much we can do without depending on scala. I also don't want to add things to jep that don't need to be there. I think its fantastic that you have a layer on top of jep that is adding things and I don't think it is productive to expand the scope of Jep to do things that you are already doing well but I'm sure there are things you can't do, or can't do efficiently from outside of Jep so if there are things we can add that make it easier to build layers on top of Jep then we should do them.

**Comment by jeremyrsmith** [comment]
@bsteffensmeier Yes, I totally agree that jep is better off being relatively low-level; anything higher-level should be left in a separate library if possible. I wasn't suggesting extracting Scala sugar into a library that jep would depend on – just that having such a library might reduce some of the desire to have such things in jep itself. I think we're on the same page there.

I also don't think trying to do special Scala stuff is right for jep, because it would be brittle (and possibly version-dependent wrt Scala) and there would be so many corner cases that I think it would generate more tickets than it solved. One thing that might be helpful (for building a Scala-specific layer atop jep, and probably other higher-level layers for other JVM languages) is if jep were to expose some interfaces that can be implemented to customize how python interacts with a Java object (this might already be possible by implementing pythonic `__magic__` methods on the Java side, but a more java-ish mechanism would help)

**Comment by rapgro** [comment]
> Remove Python 3.3, 3.4, 3.5 support. Will clean up C code.

Python 3.9 is on the way: #229

**Comment by ndjensen** [comment]
I  am adding these thoughts but again there is no commitment to make these happen or not happen.

- On 4.0 we should switch the development branch to master to be like every open source GitHub project out there.  That seems to be a de factor standard.
- 4.0 is perhaps too ambitious as it looks daunting for two developers who no longer have much time.  I need to raise the number to 4.0 since I want to break API, specifically regarding JepException (change to extend RuntimeException) and instantiating a Jep (require instantiating a SubInterpreter or SharedInterpreter).  If we drop the PyJType concept and the pluggable converters concept, it becomes more manageable, albeit there are then less reasons for a software project to upgrade.  But it'd still be cleaner for any new users or developers who want to upgrade.

**Comment by ndjensen** [comment]
Closing as Jep 4.0 has now been released.  To see what made the release, see the release notes.
