### ISSUE TITLE
get exception when i use jep to import cv2 on linux

### ISSUE THREAD

**Issue by Mrliuzh** [ninia/jep#203]
**Describe the problem**
i run my project on linux, when i use jep to import cv2  i get a exception  as follow

jep.JepException: <class 'ImportError'>: /usr/local/lib/python3.6/site-packages/cv2/cv2.cpython-36m-x86_64-linux-gnu.so: undefined symbol: PyLong_Type
        at /usr/local/lib/python3.6/site-packages/cv2/__init__.<module>(__init__.py:3)

**Environment (please complete the following information):**
- OS Platform, Distribution, and Version: centos
- Python Distribution and Version: python 3.6.5
- Java Distribution and Version: 1.8.0_221
- Jep Version:3.8.2
- Python packages used (e.g. numpy, pandas, tensorflow):

**Additional context**
python configure with --enable-shared also
but i can import cv2 withon jep

**Comment by Mrliuzh** [comment]
but i can import cv2 without jep

**Comment by bsteffensmeier** [comment]
Try setting the environmental variable LD_PRELOAD to the full path to you libpython, probably something like `LD_PRELOAD=/usr/local/lib/libpython3.6m.so`. Please let me know if that fixes it, I put [new code into 3.8](https://github.com/ninia/jep/blob/dev_3.8/src/main/c/Jep/pyembed.c#L351) specifically so LD_PRELOAD is no longer necessary so if that fixes your problem then the new code is not working in your environment so I would like to get more information about your environment so we can make that code bettter.

**Comment by Mrliuzh** [comment]
@bsteffensmeier thank you so much
the "py***" undefined symbol problem of cv2.cpython-36m-x86_64-linux-gnu.so is due to not loading the libpython3.6m.so.
when i run the ldd -r  cv2.cpython-36m-x86_64-linux-gnu.so,i get the undefined symbol too
![image](https://user-images.githubusercontent.com/28565906/64265479-8f0ab180-cf65-11e9-9656-a7a439fc6d20.png)

but  after i set the LD_PRELOAD=/usr/local/lib/libpython3.6m.so
all of the undefined symbol disappea.
![image](https://user-images.githubusercontent.com/28565906/64265709-f7599300-cf65-11e9-8a75-79cf36671d99.png)

**Comment by Mrliuzh** [comment]
so it's jep's bug or not?

**Comment by bsteffensmeier** [comment]
> so it's jep's bug or not?

I don't think it is binary, we want to do the best we can in jep, but we are stuck between java and python having different expectations for how libpython is loaded. There is a detailed description of the problem in the [code I linked earlier](https://github.com/ninia/jep/blob/dev_3.8/src/main/c/Jep/pyembed.c#L351). If we can find anything reasonable we can do in jep to make this work then we want to do that, but if there is nothing we can do then you will have to set LD_PRELOAD before running the application.

We have seen this problem in the past but the code I linked has fixed it for us, so I cannot recreate your problem to get more information. Can you modify jep and rebuild it to perform additional testing for me to try to get more information? Replace the contents of #ifdef I linked to with the following code and let me know what output you see, or if you are able to load cv2.

```c
    printf("Attempting dlopen\n");
    void* dlresult = dlopen(PYTHON_LDLIBRARY,
                            RTLD_LAZY | RTLD_NOLOAD | RTLD_GLOBAL);
    if (dlresult) {
        printf("dlopen Succeeded\n");
    } else {
        printf("dlopen Failed\n");
        char *error = dlerror();
        if (error != NULL) {
            printf("dlopen Failed: %s\n", error);
        } else {
            printf("dlopen Failed for an unknown reason\n");
        }
    }
```

**Comment by ding-c3** [comment]
Looks like the `PYTHON_LDLIBRARY` variable (input to `dlopen` [here](https://github.com/ninia/jep/blob/master/src/main/c/Jep/pyembed.c#L375) ) is loaded [here](https://github.com/ninia/jep/blob/master/setup.py#L68) via `sysconfig.get_config_var('LDLIBRARY')`. On our system, it returns "libpython3.9.a" while only "libpython3.9.so" exists on file system. We install python directly from the default conda channel https://anaconda.org/anaconda/python.

For now, we implemented a "hack" (inspired by the discussion [here](https://github.com/cocotb/cocotb/issues/1182)) by creating a symlink "libpython3.9.a" that points to "libpython3.9.so". With this hack, there is no need to use "LD_PRELOAD".

@bsteffensmeier Is there something smart JEP can do to remove the need for symlinking or "LD_PRELOAD"? Maybe swap the ".a" with ".so" if Python is compiled with `--enable-shared` and  (`sysconfig.get_config_vars('Py_ENABLE_SHARED')`)?
