### ISSUE TITLE
binascii.cpython-38-x86_64-linux-gnu.so: undefined symbol: PyFloat_Type

### ISSUE THREAD

**Issue by wherewp** [ninia/jep#206]
Hello, friendly people! Hope you had a good weekend. Hope the following bug report is helpful.

Getting the aforementioned error on a bare-bones test program:

import jep.Interpreter;
import jep.SharedInterpreter;
import jep.JepException;

class Test {
  public static void main(String[] args) {
    try {
      Interpreter interp = new SharedInterpreter();
      interp.exec("import pickle");
    } catch (JepException e) {
      System.err.println("Python/jep error: " + e.getMessage());
    }
  }
}

Steps to reproduce:
$ javac Test.java --class-path ~/.local/lib/python3.8/site-packages/jep/jep-3.9.0.jar
$ export CLASSPATH=".:~/.local/lib/python3.8/site-packages/jep/jep-3.9.0.jar"
$ java Test
Python/jep error: <class 'ImportError'>: /usr/local/lib/python3.8/lib-dynload/_struct.cpython-38-x86_64-linux-gnu.so: undefined symbol: PyFloat_Type

Running Red Hat Enterprise Linux 7.7, with manually compiled Python 3.8, configured with default options (no optimizations).

**Comment by bsteffensmeier** [comment]
PyFloat_Type should be defined in libpython. It would seem _struct.cpython-38-x86_64-linux-gnu.so does not depend on libpython so libpython will need to be loaded into the global namespace. By default JNI will load libpython in a local namespace. Try setting LD_PRELOAD to the location of your libpython so, to force it to be loaded globally.

**Comment by wherewp** [comment]
Thank you very much! Didn't realize that was where the the symbol lived. Recompiling Python with --enable-shared was sufficient to resolve the issue.
