### ISSUE TITLE
Set timeout to limit execution time of script

### ISSUE THREAD

**Issue by demom** [ninia/jep#207]
**Is your feature request related to a problem? Please describe.**
There is a lack of control to how time a script might run when executed from Java. For example, a python script which talks to a web server might hang if the web server does not respond. Setting a max execution timeout makes it easy to retake control when such things happens.

**Describe the solution you'd like**
When executing a script, a possibility to add a timeout to limit script execution. When timeout is reached, execution should be stopped and a JepTimeoutException should be thrown.

Perhaps automatically tearing down/closing the entire subinterpreter when timeout is reached would be a way to solve this issue?

**Describe alternatives you've considered**
I've tried to use TimeLimiter from googles Guava project, but it does only throw an exception when timeout is reached, not halting execution of script.

**Additional context**
I know that it is possible to use pythons multiprocess lib for this, but I really think it would be a standard feature of Jep.

**Comment by demom** [comment]
Forgot to mention: Jep is a helluva great project. Keep it up, guys!

**Comment by bsteffensmeier** [comment]
I don't see any way you could do this without running the python in a separate process because as far as I know Python does not provide any mechanism to stop execution of a specific thread after a timeout. The primary purpose of Jep is to allow Java and Python to run in the same process so I consider this to be outside the scope of Jep.

**Comment by ndjensen** [comment]
While a cool idea, I also don't see a way to safely implement this especially given how much Jep relies on PyThreadState and there's no good ways that I'm aware of to safely interrupt threads.
