### ISSUE TITLE
 library machine type 'x64' conflicts with target machine type 'X86'

### ISSUE THREAD

**Issue by danilomo** [ninia/jep#221]
I cannot build JEP or install with PIP due the error described in the output bellow. I tried to search for a way to set the target machine type in the compiler but the answers I get on google only describe how to do this with a project solution opened in Visual Studio.

Environment:
- Windows 10
- Python 3.7
- JDK 1.8.0_181
- JEP 3.9.0
- Python packages used: numpandas

**Logs**

(...)
rc\main\c\Jep\java_access\LongBuffer.obj build\temp.win32-3.7\Release\src\main\c\Jep\java_access\Map.obj build\temp.win32-3.7\Release\src\main\c\Jep\java_access\Member.obj build\temp.win32-3.7\Release\src\main\c\Jep\java_access\Method.obj build\temp.win32-3.7\Release\src\main\c\Jep\java_access\Modifier.obj build\temp.win32-3.7\Release\src\main\c\Jep\java_access\Number.obj build\temp.win32-3.7\Release\src\main\c\Jep\java_access\Object.obj build\temp.win32-3.7\Release\src\main\c\Jep\java_access\Proxy.obj build\temp.win32-3.7\Release\src\main\c\Jep\java_access\Short.obj build\temp.win32-3.7\Release\src\main\c\Jep\java_access\ShortBuffer.obj build\temp.win32-3.7\Release\src\main\c\Jep\java_access\String.obj build\temp.win32-3.7\Release\src\main\c\Jep\java_access\Throwable.obj build\temp.win32-3.7\Release\src\main\c\Jep\python\invocationhandler.obj build\temp.win32-3.7\Release\src\main\c\Jep\python\jep_object.obj build\temp.win32-3.7\Release\src\main\c\Jep\python\jpycallable.obj build\temp.win32-3.7\Release\src\main\c\Jep\python\pypointer.obj build\temp.win32-3.7\Release\src\main\c\Objects\pyjarray.obj build\temp.win32-3.7\Release\src\main\c\Objects\pyjautocloseable.obj build\temp.win32-3.7\Release\src\main\c\Objects\pyjbuffer.obj build\temp.win32-3.7\Release\src\main\c\Objects\pyjclass.obj build\temp.win32-3.7\Release\src\main\c\Objects\pyjcollection.obj build\temp.win32-3.7\Release\src\main\c\Objects\pyjconstructor.obj build\temp.win32-3.7\Release\src\main\c\Objects\pyjfield.obj build\temp.win32-3.7\Release\src\main\c\Objects\pyjiterable.obj build\temp.win32-3.7\Release\src\main\c\Objects\pyjiterator.obj build\temp.win32-3.7\Release\src\main\c\Objects\pyjlist.obj build\temp.win32-3.7\Release\src\main\c\Objects\pyjmap.obj build\temp.win32-3.7\Release\src\main\c\Objects\pyjmethod.obj build\temp.win32-3.7\Release\src\main\c\Objects\pyjmonitor.obj build\temp.win32-3.7\Release\src\main\c\Objects\pyjmultimethod.obj build\temp.win32-3.7\Release\src\main\c\Objects\pyjnumber.obj build\temp.win32-3.7\Release\src\main\c\Objects\pyjobject.obj /OUT:build\lib.win32-3.7\jep\jep.cp37-win32.pyd /MANIFESTFILE:build\temp.win32-3.7\Release\src\main\c\Jep\jep.cp37-win32.pyd.manifest /MANIFEST
       **Creating library build\lib.win32-3.7\jep\jep.cp37-win32.lib and object build\lib.win32-3.7\jep\jep.cp37-win32.exp
    pyembed.obj : error LNK2019: unresolved external symbol __imp__JNI_GetCreatedJavaVMs@12 referenced in function _pyembed_get_env
    C:\\Java\\jdk1.8.0_181\\lib\\jvm.lib : warning LNK4272: library machine type 'x64' conflicts with target machine type 'X86'
    build\lib.win32-3.7\jep\jep.cp37-win32.pyd : fatal error LNK1120: 1 unresolved externals
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\link.exe' failed with exit status 1120**
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\danilo\desktop\myenv\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\danilo\\AppData\\Local\\Temp\\pip-install-258l3yqs\\jep\\setup.py'"'"'; __file__='"'"'C:\\Users\\danilo\\AppData\\Local\\Temp\\pip-install-258l3yqs\\jep\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\danilo\AppData\Local\Temp\pip-record-gsnmpqf4\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\danilo\desktop\myenv\include\site\python3.7\jep' Check the logs for full command output.

**Comment by bsteffensmeier** [comment]
It looks like you have a 32 bit Python installation and a 64 bit Java installation. You're Java and Python need to be built for the same architecture if you want to use them together.

**Comment by danilomo** [comment]
This was exactly what was going on. I thought I had a Python 64 bits, but it was 32 bits. Not knowing this I thought the problem was with the compiler.

Thanks for the help.
