### ISSUE TITLE
Documentation of Serialization Time

### ISSUE THREAD

**Issue by RBerkheimer** [ninia/jep#222]
I am getting questions about some cloud-native performance issues and I was hoping for either a quick Jep team answer or longer discussion.

I've got a distributed HPC JVM/C/Fortran library I've worked on for a while that I want to expand into python. Collaboration with python would secure about 75-80% of our users versus the 60% we have now with current language support. 

Major issues have been raised about continued use of the JVM languages versus Python in a lambda/serverless context. There have been reports of 88% of compute time being spent in data serialization/deserialization. This is a major concern while discussing long term architecture decisions.

Does Jep address this in any way? Are there metrics that can be done, designs that can prove this isn't an issue, or are there any design patterns recommended that we can provide that can assuage this concern?

Thanks,
Ryan

**Comment by RBerkheimer** [comment]
Here's some supporting documentation for the issue, from an anaconda foundation presentation:

<img width="1032" alt="Screen Shot 2019-12-20 at 9 24 13 PM" src="https://user-images.githubusercontent.com/6161855/71301607-222df280-236f-11ea-9c4e-9e30706299c1.png">
<img width="1039" alt="Screen Shot 2019-12-20 at 9 23 47 PM" src="https://user-images.githubusercontent.com/6161855/71301610-2fe37800-236f-11ea-9dc8-a205b044d401.png">

**Comment by bsteffensmeier** [comment]
I don't understand how you are proposing to use Jep within your application. When Jep is used to communicate with Python from a Java process there is no serialization/deserialization. The C-API of both languages is used to expose the objects and methods from language directly into the other. Your diagram shows Python and Java communicating through the operating system which suggests to me they are separate processes, however the purpose of Jep is for the Python runtime and the Java runtime to coexist in the same process and directly use eachothers memory with no involvement from the Operating System.

**Comment by ndjensen** [comment]
Closing as the question seems to be directed to inter-process communication between Java and Python as opposed to Jep which is intra-process communication where the Python interpreter is running inside the JVM process.
