### ISSUE TITLE
Fatal Python error: initfsencoding: unable to load the file system codec ModuleNotFoundError: No module named 'encodings'  Current thread 0x00004230 (most recent call first):

### ISSUE THREAD

**Issue by mtsol** [ninia/jep#226]
I've followed the getting started tutorial https://github.com/ninia/jep/wiki/Getting-Started, with python 3.7.1, and jep 3.7.1. And when I run the example code: 

try (Interpreter interp = new SharedInterpreter()) {
    interp.exec("from java.lang import System");
    interp.exec("s = 'Hello World'");
    interp.exec("System.out.println(s)");
    interp.exec("print(s)");
    interp.exec("print(s[1:-1])");
}

I get the following error:
Fatal Python error: initfsencoding: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00004230 (most recent call first):

**Comment by bsteffensmeier** [comment]
- What environmental variables or system properties are using to load libjep and/or libpython?
- My initial recommendation would be to set the PYTHON_HOME environmental variable to the location of your python installation.
- If you are still having problems please try to run the jep script which should be installed into the python bin directory when you install jep, if this works then I recommend looking in that script to see how to set your environment.
- You indicate you are using jep 3.7.1 but your code is using SharedInterpreter which wasn't introduced until jep 3.8, please clarify.
- Where is the jep python module installed on your system?
- Where is the encodings module installed on your system?

**Comment by mtsol** [comment]
this error appears when we compile jep with a version other than that through which python was built. resolved the issue, hence closing.

and thanks for quick response. (Y)
