### ISSUE TITLE
`libgcc_s.so.1 must be installed for pthread_cancel to work

### ISSUE THREAD

**Issue by vasica38** [ninia/jep#227]
**Describe the bug**
I am using [wdb](https://github.com/Kozea/wdb) in python and I am invoking a method for debugging it. The jvm crashes and it throws me 
`libgcc_s.so.1 must be installed for pthread_cancel to work
Aborted (core dumped)`
it happens when I am holding the debugger and waiting. 

**To Reproduce**
python code
`import wdb ` 
 `def sum():  `
`      a=1  `
`      b=1  `
`     wdb.set_trace()  `
`     return a+b`

Java code
`Jep jepInterpret = new SharedInterpreter();`
` jepInterpret.runScript(scriptName);`
` jepInterpret.invoke("loop");`

**Environment (please complete the following information):**
- Debian GNU/Linux 9 (stretch)
- Python3.7 from conda distribution:
- Java 1.8:
- latest version:
- wdb:

**Additional context**

**Comment by bsteffensmeier** [comment]
- Is libgcc_s.so.1 installed on your system?
- Is the libgcc_s.so.1 on your system a 32bit or 64bit library, or do you have both.
- Are you running a 32 bit or 64 bit java.
- I suspect that you do not have a version of  libgcc_s.so.1 that is compatible with your java environment installed on your installed.

**Comment by vasica38** [comment]
> * Is libgcc_s.so.1 installed on your system?
> * Is the libgcc_s.so.1 on your system a 32bit or 64bit library, or do you have both.
> * Are you running a 32 bit or 64 bit java.
> * I suspect that you do not have a version of  libgcc_s.so.1 that is compatible with your java environment installed on your installed.
1) yes
2) 64 bit
3) 64 bit java

**Comment by ndjensen** [comment]
What version of gcc do you have installed?  I ask only because I found this: https://github.com/Homebrew/linuxbrew-core/issues/6841

**Comment by vasica38** [comment]
@ndjensen gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1)

**Comment by bsteffensmeier** [comment]
Try setting the environmental variable LD_PRELOAD to the complete path to libgcc_s.so.1 to force it to load and see if that helps. I'm not sure what needs that library or what the normal mechanism is to load it but in theory that should force it to load.

**Comment by vasica38** [comment]
@bsteffensmeier it didn't help. Also, it is worthy to mention that I am using openjdk and conda3.

**Comment by bsteffensmeier** [comment]
Did you get an hs_err_pid for the crash. If so can you attach it so we can see what libraries are currently loaded and confirm that the LD_PRELOAD was successful in loading libgcc_s.so.1.

**Comment by vasica38** [comment]
@bsteffensmeier I guess the problem is that jep is used by two threads. The one is the wdb is using the jep instance, and the another one is my app usage. I am going to create two jep instances and test it. Will come with a result. Thank you.

**Comment by vasica38** [comment]
@bsteffensmeier  @ndjensen 
`apt-get install -y libgl1-mesa-glx libegl1-mesa libxrandr2 libxrandr2 libxss1 libxcursor1 libxcomposite1 libasound2 libxi6 libxtst6 `
this solved the problem, don't know how and why, but it did the magic :). If you know why it solved the problem, then explain please :)
