### ISSUE TITLE
Build JEP on Win 10 64 bit

### ISSUE THREAD

**Issue by neil-benn** [ninia/jep#230]
**Describe the problem**
I'm trying to build JEP.  I've pulled down Microsoft Visual C++ 2015 build tools and started the command prompt in that package called "Visual C++ 2015 x64 Native Build Tools Command Prompt".  I can build correctly and I've run the install.  I've then tried to following get it running:

- Put jep.dll, jep.cp38-win_amd64.dll, jep.cp38-win_amd64.exp, jep.cp38-win_amd64.dll.lib in a directory and entered the value in java.library.path/
- Put every single file from the build directory in a directory
- Added the resdist dlls from the C++ Viaul Studio tools; I have concrt140.dll, msvcp140.dll, vcamp140.dll, vccorlib140.dll, vcomp140.dll and vcruntime140.dll

- For the above I've tried putting java.library.path as the directory, used MainInterpreter.setJepLibraryPath, put the directory in the windwos path env variable

  Every single method I try gives me the error from Java:

Exception in thread "main" java.lang.UnsatisfiedLinkError: C:\Users\neilb\Documents\GitHub\datapaq5\etc\jeplibs: Can't find dependent libraries
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2430)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2487)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2684)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2617)
	at java.base/java.lang.Runtime.load0(Runtime.java:767)
	at java.base/java.lang.System.load(System.java:1834)
	at jep.MainInterpreter.initialize(MainInterpreter.java:125)
	at jep.MainInterpreter.getMainInterpreter(MainInterpreter.java:101)
	at jep.Jep.<init>(Jep.java:256)
	at jep.SharedInterpreter.<init>(SharedInterpreter.java:56)
	at com.ziath.datapaq5.export.ScriptExporter.main(ScriptExporter.java:35)

**Environment (please complete the following information):**
- OS Platform, Distribution, and Version: Win10
- Python Distribution and Version: 2.8 64 bit
- Java Distribution and Version: jdk11 64 bit
- Jep Version: 0.10
- Python packages used (e.g. numpy, pandas, tensorflow): None

**Logs**
[build_output.txt](https://github.com/ninia/jep/files/4172203/build_output.txt)

Does anyone know what external dependencies it could be asking for?

**Comment by neil-benn** [comment]
OK; I've got somewhere - you need to install the vc++ distributable on the target PC.  However, this _only_ works if you load the jep.dll via java.library.path - not if you use MainInterpreter.setJepLibraryPath.  Does anyone have any ideas?

**Comment by creemama** [comment]
Just in case this is helpful to the discussion, JEP has an FAQ that answers the question ["How do I fix Unsatisfied Link Error: no jep in java.library.path?"](https://github.com/ninia/jep/wiki/FAQ#how-do-i-fix-unsatisfied-link-error-no-jep-in-javalibrarypath)

**Comment by neil-benn** [comment]
Thanks; that isn't the issue though - we can reference to jep.dll without a problem.  The issue is that JEP relies upon something else which we need to install and also the call MainInterpreter.setJepLibraryPath doesn't work.  Setting java.ibrary.path or the PATH env. variable does work but it is more difficult to use because you need this value _before_ the JDK starts up.

**Comment by creemama** [comment]
I recently ran into the "Can't find dependent libraries" error too.

Using [Dependency Walker](http://www.dependencywalker.com/), for my installation, I found that `jep.dll` depends on `jvm.dll` and `python38.dll`. `python38.dll` was in my `PYTHONHOME` directory.

I got the "Can't find dependent libraries" error because Java could not find `python38.dll`.

I fixed the problem by setting my `PATH` to the following:
```
set PYTHONHOME=C:\path\to\your\python\installation
set PATH=%PYTHONHOME%;%PYTHONHOME%\Lib\site-packages\jep;%PATH%
set PYTHONPATH=%PYTHONHOME%\DLLs;%PYTHONHOME%\Lib;%PYTHONHOME%\Lib\site-packages
```

For me, setting `PYTHONPATH` was necessary, but this may not be true for all Python 3 installations.

**Comment by ndjensen** [comment]
Thanks for sharing what you have found.  The Windows wiki page is a bit out of date, feel free to update it to help others.  Unfortunately I don't have a Windows VM to even begin trying to troubleshoot the issue with `MainInterpreter.setJepLibraryPath(...)`.  The [code](https://github.com/ninia/jep/blob/v3.9.0/src/main/java/jep/MainInterpreter.java#L123) is fairly simple so I don't know why it wouldn't work.

I wonder if we did something like
```java
System.setProperty("java.library.path", path);
```
if it would work?  Though that somewhat defeats the purpose of using Java's `System.load(filename)` which is supposed to work.

**Comment by neil-benn** [comment]
Hello,

 Setting java.library.path is an interesting one.  It actually generally
works but the advice from Oracle is to not mess with it once it has been
set.  I'll look at the code on Monday and let you know.  I imagine it is
just setting the path to call load library from?

  I'll report back when I've checked it out.  I'll need to get it working
on debian/ubuntu too but that is later.

Cheers,

Neil

**Comment by bsteffensmeier** [comment]
It might help your use case to set [Python home programatically](http://ninia.github.io/jep/javadoc/3.9/jep/PyConfig.html#setPythonHome-java.lang.String-) instead of using the environment. Jep has some logic to find both the jep library and the python library based off that python home as long as they are installed in the typical locations and you can set that after application startup but [before the first interpreter is created]([see also](http://ninia.github.io/jep/javadoc/3.9/jep/MainInterpreter.html#setInitParams-jep.PyConfig-)).

**Comment by neil-benn** [comment]
Hello,

  Unfortunately I can't do that.   We're using the system python, we can't
install a private one.  At the moment we tell the user to install python
and set the path.  We have not decided if we put jep with the app or in the
system python site-packages.  We currently are in the app because it is
easier to reference but will the java library find both in site-packages if
pythonpath is set correctly?

Cheers,

Neil

**Comment by bsteffensmeier** [comment]
The python library(python38.dll) is found by searching under the python home(either PYTHONHOME or the python home in PyConfig). jep.dll is found by searching the site-packages under python home, or by searching for it under PYTHONPATH. If you use `MainInterpreter.setJepLibraryPath` then Jep assumes you have a non-standard installation that will not work with these paths and it makes no attempt to search in other locations. If you need to use `MainInterpreter.setJepLibraryPath` and you need to specify the location of the python library then you will need to use `System.load` to load the python library yourself.

**Comment by neil-benn** [comment]
Hello,

  Thanks that is a perfect explanation!   I'll work on that on Monday.

Cheers,

Neil

**Comment by neil-benn** [comment]
I'm back onto this - CoVid related stuff pulled me off it but the majority of the work is done now.  Relating to the comment from @bsteffensmeier I now do the following:

```
		System.load("C:\\Program Files\\Python38\\python38.dll");
		MainInterpreter.setJepLibraryPath(new File("etc/jep/windows/java").getAbsolutePath());
		
		System.out.println(System.getProperty("java.library.path"));
		try (Interpreter interp = new SharedInterpreter()) {
		    // using exec(String) to invoke methods
		    interp.set("arg", 3);
		    interp.exec("x = arg * 2");
		    Object result1 = interp.getValue("x");
		    assertEquals("6", result1.toString());
		}
```
  However this is still giving me the error of :

```
java.lang.UnsatisfiedLinkError: C:\Users\neilb\Documents\GitHub\datapaq5\etc\jep\windows\java: Can't find dependent libraries
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2430)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2487)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2684)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2617)
	at java.base/java.lang.Runtime.load0(Runtime.java:767)
	at java.base/java.lang.System.load(System.java:1834)
	at jep.MainInterpreter.initialize(MainInterpreter.java:125)
	at jep.MainInterpreter.getMainInterpreter(MainInterpreter.java:101)
	at jep.Jep.<init>(Jep.java:256)
	at jep.SharedInterpreter.<init>(SharedInterpreter.java:56)
	at com.ziath.datapaq5.export.TestScriptExporter.testBasicScript(TestScriptExporter.java:32)
```

  So I'm still not there; ideas on a postcard?

**Comment by bsteffensmeier** [comment]
`MainInterpreter.setJepLibraryPath` is expecting then full path to a dll, not a directory.

**Comment by neil-benn** [comment]
Yes; I cracked the code open and read it and that is indeed the case.  Therefore the idea is todo the following:

- Install the VC++ libraries on application install
- Package the jep.dll with the app
- Bring in the jep.jar with standard maven methods
- Include the jep-compiled code with the app (the result of executing python setup.py build)
- Ask the user to provide the python install and then use python setup install to put the jep site-packages in the right place with all the correct conventions.

  When executing use the code above to actually run the scripts.

  I hope this isn't crazy and someone else reads this and it helps then even a little bit!

Cheers,

Neil
