### ISSUE TITLE
Is it possible to use Jep with a static archive libpython?

### ISSUE THREAD

**Issue by Melnorme1984** [ninia/jep#231]
I need to switch to a different Python environment which doesn't have a libpython.so. Instead it uses a libpython.a static archive file. That doesn't work with LD_PRELOAD, which means Jep doesn't work for me anymore. Is there any way to get this to work?

**Comment by bsteffensmeier** [comment]
You could try loading libpython.a from java with System.loadLibrary: https://stackoverflow.com/questions/24493337/linking-static-library-with-jni
