### ISSUE TITLE
readline.get_completer() differs when using jep and python3

### ISSUE THREAD

**Issue by creemama** [ninia/jep#235]
**Describe the bug**
I expect [`readline.get_completer()("readline.",0)`](https://docs.python.org/3/library/readline.html#readline.get_completer) to return the same thing when using `jep` and `python3`. The former returns `None`. The latter returns `readline.add_history(`.

This bug really is a feature request to add tab completion to the `jep` console. I want to support tab completion in a [Java Swing console I am writing using JEP](https://github.com/creemama/swingconsole/blob/master/swingconsole-jep/src/main/java/com/creemama/swingconsole/jep/JepEngine.java).

**To Reproduce**
Execute the following commands to reproduce the problem. If you already have `python3`, `java`, and `jep`, skip to the command `python3 -S`.
```
$ docker run -it --rm python:3.8.2 bash

# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

# apt-get update
# apt-get install -y default-jdk
# export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
# java -version
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment (build 11.0.6+10-post-Debian-1deb10u1)
OpenJDK 64-Bit Server VM (build 11.0.6+10-post-Debian-1deb10u1, mixed mode, sharing)

# pip install jep
Collecting jep
  Downloading jep-3.9.0.tar.gz (3.0 MB)
...

# python3 -S
Python 3.8.2 (default, Feb 26 2020, 14:58:38) 
[GCC 8.3.0] on linux
>>> import readline
>>> import rlcompleter
>>> print(readline.get_completer()("readline.",0))
readline.add_history(
>>> Ctrl+D

# jep
>>> import readline
>>> import rlcompleter
>>> print(readline.get_completer()("readline.",0))
None
>>> exit()
```

**Expected behavior**
`jep` should return `readline.add_history(` just like `python3`.

**Environment (please complete the following information):**
- OS Platform, Distribution, and Version:
```
# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
- Python Distribution and Version:
```
# python --version
Python 3.8.2
```
- Java Distribution and Version:
```
# java -version
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment (build 11.0.6+10-post-Debian-1deb10u1)
OpenJDK 64-Bit Server VM (build 11.0.6+10-post-Debian-1deb10u1, mixed mode, sharing)
```
- Jep Version:
```
# jep
>>> import jep
>>> jep.__VERSION__
'3.9.0'
```
- Python packages used (e.g. numpy, pandas, tensorflow): `readline`

**Additional context**
I also reproduced this problem on macOS with the following environment:
- OS Platform, Distribution, and Version:
```
$ sw_vers -productVersion
10.14.6
```
- Python Distribution and Version:
```
$ python3 --version
Python 3.7.6
```
- Java Distribution and Version:
```
$ java --version
openjdk 11.0.5 2019-10-15
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.5+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.5+10, mixed mode)
```
- Jep Version:
```
$ jep
>>> import jep
>>> jep.__VERSION__
'3.9.0'
```
- Python packages used (e.g. numpy, pandas, tensorflow): `readline`

**Comment by bsteffensmeier** [comment]
I was able to get tab completion working from the Jep interpreter working with the following commands:
```
>>> import readline
>>> import rlcompleter
>>> print(readline.get_completer()("readline.",0))
None
>>> readline.set_completer(rlcompleter.Completer(locals()).complete)
>>> print(readline.get_completer()("readline.",0))
readline.add_history(
>>> readline.parse_and_bind("tab: complete")
>>> readline.
```

I agree it would be good to have something similar in console.py so jep automatically gets tab completion. If I understand your use case correctly then you aren't actually using console.py directly so you should be able to do something similar in your application to get a completer that works for you.

**Comment by creemama** [comment]
@bsteffensmeier, your solution worked great. I made a [pull request](https://github.com/ninia/jep/pull/236) adding tab completion to `console.py`. I also added your solution to a Java class of my own: [JepCompleter](https://github.com/creemama/swingconsole/blob/master/swingconsole-jep/src/main/java/com/creemama/swingconsole/jep/JepCompleter.java).

**Comment by creemama** [comment]
Since #237 merged, I am closing this issue.
