### ISSUE TITLE
Got “Fatal Python error” while creating JEP SubInterpreter in Java

### ISSUE THREAD

**Issue by anthonyhu81** [ninia/jep#242]
Got the following error while creating JEP SubInterpreter in Java on Windows10:

    Fatal Python error: init_sys_streams: can't initialize sys standard streams
    Python runtime state: core initialized
    OSError: [WinError 6] The handle is invalid

    Current thread 0x0000569c (most recent call first):
    <no Python frame>

And then the process exit.
This error not occur every time, almost one tenth.

Any idea about this error?
Thanks!

**Comment by bsteffensmeier** [comment]
In order to better understand why you may be having problems I need some additional details on your setup.

1. What version of python are you using and where did it come from(i.e. is this an anaconda installation or an official python installer from python.org)
2. What version of java are you using.
3. What version of jep are you using.

**Comment by anthonyhu81** [comment]
1, I got the Python3.8.2 installer from https://www.python.org/downloads/release/python-382/
2, The java version is "Corretto-8.202.08.2 (build 1.8.0_202-b08)", 64bit
3, The JEP version is 3.9.0

**Comment by bsteffensmeier** [comment]
The most likely cause is that one of your std stream is closed or invalid at the time when jep is started. I recommend looking at how your java process is started and determining what you expect stdin, stderr, and stdout to be. Especially if you have an IO redirection you may be experiencing problems if other processes that are connected to your std streams are exiting.

**Comment by anthonyhu81** [comment]
Thank you @bsteffensmeier.
I redirect stdout to the log file in my C code with "freopen()", change it to 
   fopen() ;
   dup2();
and everything seems to be OK now.
