### ISSUE TITLE
Do not use /usr/libexec/java_home to detect JAVA_HOME for osx.

### ISSUE THREAD

**Issue by mushtaq** [ninia/jep#244]
**Describe the problem**

Installing/building on osx fails with `commands.util.CommandError: Encountered an error (return code 1) while executing '/usr/libexec/java_home'`

This happens in case when JDK is installed and managed using tools like [coursier](https://github.com/coursier/coursier/issues/1684) or [sdkman](https://github.com/sdkman/sdkman-cli/wiki/FAQ#on-mac-usrlibexecjava_home-does-not-detect-alternatives-installed-by-sdkman-what-can-i-do)

**Search for existing solutions**

Deleting osx check from [java.py](https://github.com/ninia/jep/blob/master/commands/java.py#L33) fixes the issue because it falls back to the environment variable JAVA_HOME which is appropriately set by these tools/users

**Environment (please complete the following information):**

- OS Platform, Distribution, and Version: MacOS Catalina
- Python Distribution and Version: Python 3.7.7
- Java Distribution and Version: JDK 11 installed via coursier or sdkman
- Jep Version: master/latest
- Python packages used (e.g. numpy, pandas, tensorflow): None

**Logs**

```text
~/p/c/jep (master) python3 setup.py build
Traceback (most recent call last):
  File "/Users/mushtaqahmed/projects/cloned/jep/commands/java.py", line 36, in get_java_home
    result = shell('/usr/libexec/java_home')
  File "/Users/mushtaqahmed/projects/cloned/jep/commands/util.py", line 104, in shell
    raise CommandError(message=msg, result=result)
commands.util.CommandError: Encountered an error (return code 1) while executing '/usr/libexec/java_home'
numpy not found, running without numpy support
Error:
Include folder should be at '/System/Library/Frameworks/JavaVM.framework/Headers' but doesn't exist. Please check you've installed the JDK properly.
```

**Additional context**

None

**Comment by ndjensen** [comment]
I think we already have this resolved on the dev_3.9 branch in preparation for 3.9.1.  Please review https://github.com/ninia/jep/pull/232/files.  With that change the `JAVA_HOME` environment variable takes precedence over `/usr/libexec/java_home`.  Do you know if `/usr/libexec/java_home` is still useful for some macs?  I'm reluctant to take it out because some macs may still use it, but I don't know how relevant it is.

**Comment by mushtaq** [comment]
Yes, that will work as well!

Honestly, I do not know if people still make use of `/usr/libexec/java_home`. We can assume, 'yes'. So, this change will take care of it as well.

Awaiting 3.9.1 release!

**Comment by aleksandersumowski** [comment]
as a temporary workaround checking out `dev_3.9` branch and installing via `python setup.py build install` worked well for me

**Comment by bsteffensmeier** [comment]
Jep 3.9.1 has been released so this is now fixed.
