### ISSUE TITLE
Unable to install jep with python 3.8 on Windows 10

### ISSUE THREAD

**Issue by FeelLemon** [ninia/jep#246]
I am trying to install jep on windows 10 with python 3.8.
I tried a lot of things, installed Visual Build tools 2019, with MSVC 14.2 and MSVC 14.1. I can't find a solution, so I'm writing this hoping someone could help me.

When I run "pip install jep" i get the following error :
`error: Microsoft Visual C++ 14.1 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/`
But as I said, I installed microsoft visual c++ build tools.
I also have environment variables VS141COMNTOOLS and VS142COMNTOOLS leading respectively to `C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.16.27023` and `C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610`

I also tried to build by cloning the sources and running "python setup.py build" but I first ahd te following error `error: Unable to find vcvarsall.bat`
So I found [this](https://github.com/ninia/jep/issues/160#issuecomment-519262848) and changed the path in msvc9compiler.find_vcvarsall to `C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build\vcvarsall.bat`.
Now, when I run "python setup.py build" the build goes further but I have another error : 
`build\lib.win32-3.8\jep\jep.cp38-win32.pyd : fatal error LNK1120: 1 externes non r▒solus`
`error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.25.28610\\bin\\HostX86\\x86\\link.exe' failed with exit status 1120`
Here, I have no clue about what to do.

Do you know something that could help me? Did someone managed to install jep with python 3.8 on windows?

**Comment by ndjensen** [comment]
I am pretty sure users have been able get Jep working with Windows and Python 3.8.  Based on t[his comment](https://github.com/ninia/jep/issues/230#issuecomment-595927778) I think we have an example of someone getting it to work.  Did you look at the [wiki for Windows](https://github.com/ninia/jep/wiki/Windows#python-35-and-36-msvc-build-setup)?  It's out of date but the same basic principles apply.  We have appveyor set up to run builds for Windows, but I checked the file and it's not set up for 3.8, so we will need to fix that and test it.

I'm surprised you got different output for pip vs `python setup.py build`.  I think pip just runs a command like `python setup.py install` which will trigger the build, though I don't know how pip actually works.

Do you have an error or errors higher up in the build output?  [This Microsoft page](https://docs.microsoft.com/en-us/cpp/error-messages/tool-errors/linker-tools-error-lnk1120?view=vs-2019) says that there should be errors before LNK1120 that will help point to the problem.

**Comment by FeelLemon** [comment]
Thank you for your reply !

Yeah I looked at the wiki, but it just says to install some Microsoft Visual C++ build tools, which I did. I couldn't install exactly those written in the wiki because I have the 2019 installer and for example I can't have the windows 8 sdk. I have the Windows 10 SDK, MSVC 14.2 and MSVC 14.1.

Well actually, the output for pip and `python setup.py build` were quite similar at first. For pip it was `Miscrosoft Visual C++ 14.1 required` vs `unable to find vcvarsall.bat` for the other build. These too errors come from the same problem in my opinion : the installation of microsoft visual c++ on my computer is not detected (the .bat file is in the visual c++ folder). The reason I then had a different output with `python setup.py build` is that I changed the file msvc9compiler.py as I said, so that python could find the vcvarsall.bat file.

Yes, I can give you the full error output (sorry, some parts were in French, I translated it) : 
`Creation of library build\lib.win32-3.8\jep\jep.cp38-win32.lib and object build\lib.win32-3.8\jep\jep.cp38-win32.exp
pyembed.obj : error LNK2019: external symbol non resolved __imp__JNI_GetCreatedJavaVMs@12 referenced in function _pyembed_startup`
`C:\\Program Files\\Java\\jdk-14.0.1\\lib\jvm.lib : warning LNK4272: type of computer library 'x64' in conflict with target computer type 'x86'`
`build\lib.win32-3.8\jep\jep.cp38-win32.pyd : fatal error LNK1120: 1 external non resolved`
`error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.25.28610\\bin\\HostX86\\x86\\link.exe' failed with exit status 1120`

It seems that the problem comes from the function _pyembed_startup ...

**Comment by bsteffensmeier** [comment]
As the error indicates, you have a conflict between parts of your system using 'x64' and other using 'x86'. It appears you have a 32 bit python installation and a 64 bit java installation. You will need to get both python and java on the same architecture to build jep.

**Comment by ndjensen** [comment]
`warning LNK4272: type of computer library 'x64' in conflict with target computer type 'x86'` is a concern.  That implies you're trying to build a 32-bit Jep which we no longer support, or else one of your libraries is 32-bit while the other is 64-bit.  For example, maybe your Python is 64-bit while your Java is 32-bit, or vice versa.

The actual error is `external symbol unresolved __imp__JNI_GetCreatedJavaVMs@12`.

- https://stackoverflow.com/questions/18714754/unresolved-external-symbol-imp-jni-createjavavm12-referenced has one solution mentioning intermixing 64-bit and 32-bit
- https://stackoverflow.com/questions/16930567/undefined-reference-to-jni-createjavavm-windows tries to explain the problem

**Comment by FeelLemon** [comment]
Tanks for your replies !

I changed my python version to 64-bits and it worked ! 
Installation with pip still didn't worked but installation through `python setup.y build` with a modified msvc9compiler.py (where I changed the location of vcvarsall.bat) worked this time.

Thanks for your help !
