### ISSUE TITLE
Found superfluous code in jep_object? 

### ISSUE THREAD

**Issue by Reissner** [ninia/jep#248]
In jep_object.c i found various methods invoking `pyembed_setparameter_array` 
such as `JNIEXPORT void JNICALL Java_jep_python_PyObject_set__JJLjava_lang_String_2_3Z`. 
Ok thus i expect a counterpart in java: in class `jep.python.PyObject` 
method `set(long, long, String, boolean[]). 
In fact, in PyObject, there is no method set. 

How can this be?? Maybe this is old code? or new code not completed??

**Comment by ndjensen** [comment]
That is dead code.  I deprecated it in 3.8 and removed the Java methods in 3.9, but as you have found, I missed some on the C side.  The `set(args)` methods were replaced by `setAttr(String, Object)`.  `PyObject.getValue()` looks like dead code too.  Please submit a pull request on the dev_3.9 branch with the dead code removed.

**Comment by ndjensen** [comment]
Fixed on dev_3.9 branch, targeted for 3.9.1.
