### ISSUE TITLE
Calling MainInterpreter.setJepLibraryPath always throws JepException

### ISSUE THREAD

**Issue by Ben-Epstein** [ninia/jep#252]
**Describe the bug**
Whenever I call `MainInterpreter.setJepLibraryPath` I get the JepException `"Jep.setJepLibraryPath(...) called after initializing python interpreter.");`  from [here](https://github.com/ninia/jep/blob/master/src/main/java/jep/MainInterpreter.java#L287)

This occurs even before creating my shared interpreter. I have no other references to any Interpreters being created.

**Code Sample**
```
public class MyClass extends MyAbstractClass {

    ByteBuffer myObj;

    public MyClass(final Blob blobData) throws SQLException, IOException {
       MainInterpreter.setJepLibraryPath("/usr/local/lib/python3.7/site-packages/jep/libjep.so");
        InputStream is = blobData.getBinaryStream();
        int fileSize = (int)blobData.length();
        final byte[] allBytes = new byte[fileSize];
        is.read(allBytes);
        this.myObj = allocateDirect(fileSize).put(allBytes);
    }

    @Override
    public Double RunIt(String data, String schema) throws InvocationTargetException, IllegalAccessException, SQLException, IOException, JepException {
        try (SharedInterpreter interp = new SharedInterpreter())
        {
            DirectNDArray<ByteBuffer> javaObj = new DirectNDArray<>(this.myObj, true);
            interp.set("jobj", javaObj);
            .......
            return result;


        } catch (JepException e) {
            e.printStackTrace();
            return -1.0;
        }
    }

```
Output:
```
"Jep.setJepLibraryPath(...) called after initializing python interpreter."); at line 25
```
(the line `MainInterpreter.setJepLibraryPath("/usr/local/lib/python3.7/site-packages/jep/libjep.so");`)

**Expected behavior**
Expect the path to be set before the SharedInterpreter is invoked

**Environment (please complete the following information):**
- Centos 7.8.2003
- CPython 3.7.3:
- Java Distribution and Version: 1.8.0_121
- Jep Version: 3.9.0
- Pickle, numpy

**Additional context**
There are a few functions in that class that do similar things. They all start their own SharedInterpreters in the `try` syntax. I'm not sure if that's part of the problem or not.

**Comment by bsteffensmeier** [comment]
`setJepLibraryPath` should only be called once in a specific JVM and must be called before any interpreters are created. I would not recommend calling it in a constructor unless that object is specifically a singleton. Your error indicates that somewhere in the JVM another interpreter has been created before calling `setJepLibraryPath`. If you aren't sure where that may be happening you could put a breakpoint in MainInterpreter.getMainInterpreter() which will be called whenever an interpreter is created.

**Comment by Ben-Epstein** [comment]
@bsteffensmeier Thanks for the reply. That is what I expected too, but this occurs on the first invocation of the constructor, so I'm not sure how it's possible.

**Comment by ndjensen** [comment]
Can you put a breakpoint in `MainInterpreter.getMainInterpreter()` and see what is invoking that?  It should only be invoked by the Jep constructor and a breakpoint will indicate if something else is calling that method or if you're creating a Jep earlier than you thought.  Put a breakpoint here: https://github.com/ninia/jep/blob/v3.9.0/src/main/java/jep/MainInterpreter.java#L98

**Comment by bsteffensmeier** [comment]
@Ben-Epstein if you can created an isolated main class that recreates the issue I would be happy to try it out and look further but based off the code you pasted I can only assume something else in your application has used a jep interpreter before your class was constructed.

**Comment by Ben-Epstein** [comment]
@bsteffensmeier understood. I fixed my issue by moving the libjep file into the shared directory, so I didn't need to call this function after all. Thank you for the support!

**Comment by sipherhern** [comment]
fix by add the path of libjep.so  to the $LD_LIBRARY_PATH
