### ISSUE TITLE
[Minor] PyPI bagde in README points to non-existent pypie.python.org/...

### ISSUE THREAD

**Issue by PawelLipski** [ninia/jep#253]
Specifically, just the version badge (Python version & license badges are okay)

**Comment by ndjensen** [comment]
Thank you for reporting this.

**Comment by ndjensen** [comment]
Fixed on https://github.com/ninia/jep/commit/0d42a2e1ddde98423b565f411ac8f72b8c43b7a8 on dev_3.9 branch, targeted for 3.9.1 release.
