### ISSUE TITLE
passing apache arrow data to python from java

### ISSUE THREAD

**Issue by zcaudate** [ninia/jep#258]
I'd like to be able to read some data from jdbc and then pass it to a python library within the jvm through apache arrow. Is there a way to do this with jep?

**Comment by bsteffensmeier** [comment]
I am not very familiar with apache arrow but from glancing at the documentation their focus is using a standard memroy layout across langauges. To use Jep with apache arrows I would expect you to be able to pass a DirectByteBuffer containing your data in the arrow format from Java to Python to allow the apache arrow libraries in either langauge to use that shared memory in a standard structure without the need to copy data.

**Comment by zcaudate** [comment]
thanks @bsteffensmeier. Also another question.  I'd like to be able to prepackage certain python libraries in the jar as resources. Is it possible to add them to the python path using JepConfig?

**Comment by bsteffensmeier** [comment]
If you extract the python libraries you could add then to the include path in the JepConfig. You could also theoretically use a the [zipimport package](https://docs.python.org/3.8/library/zipimport.html) to import directly out of the jar. I have not actually tried using zipimport to pull out of a jar and there is nothing within jep specifically to support so you would have to use Jep.exec() to run python to set up the import hooks before running the rest of your python and I cannot guarantee it would work but I don't see any reason why it wouldn't if you can package the python within your jar to match the layout zipimport is expecting.

**Comment by zcaudate** [comment]
great. I'll give that a go. thanks.
