### ISSUE TITLE
How to enable outputs when printing

### ISSUE THREAD

**Issue by zcaudate** [ninia/jep#259]
I'm currently running jep in clojure and it's super fun. However, when I run the `print` statement, I don't actually see an output anywhere.

Is there a setting somewhere that enables it?

**Comment by bsteffensmeier** [comment]
Python print will normally go to stdout. In some environments such as an IDE the java output is redirected somewhere else and it may not be obvious where stdout is even going. Jep can redirect python print statements to java System.out, you just need to use [JepConfig.setRedirectOutputStreams](http://ninia.github.io/jep/javadoc/3.9/jep/JepConfig.html#setRedirectOutputStreams-boolean-).

**Comment by zcaudate** [comment]
Okay this is working for me. Thanks!
