### ISSUE TITLE
How to get around access via another thread.

### ISSUE THREAD

**Issue by zcaudate** [ninia/jep#260]
So I have a repl environment in clojure and have bootstrapped a small evaluation environment using `hy`

```clojure
(ns jep.lib.python
  (:import jep.Interpreter
           jep.SubInterpreter
           jep.SharedInterpreter
           jep.MainInterpreter))

(defonce +init+ (MainInterpreter/setJepLibraryPath "/Users/chris/.pyenv/versions/3.7.5/lib/python3.7/site-packages/jep/libjep.jnilib"))

(defonce +jep+
  (SubInterpreter. (-> (jep.JepConfig.)
                       (.addIncludePaths (into-array ["/Users/chris/.pyenv/versions/3.7.5/lib/python3.7/site-packages"])))))

(defonce +init+
  (do (.exec +jep+ "import hy")
      (.exec +jep+ "import imp")))

(defn hy-eval
  [inter form]
  (.exec inter (format "hy.eval(hy.read_str(%s))"  (pr-str (str form)))))

(defn hy-get
  [inter form]
  (.getValue inter (format "hy.eval(hy.read_str(%s))"  (pr-str (str form)))))

(defn hy-gets
  [inter forms]
  (mapv (partial hy-get inter) forms))

(deftype PyReturn [sym]
  Object
  (toString [obj]
    (str (.getValue +jep+ (str sym))))

  clojure.lang.IDeref
  (deref [obj]
    (.getValue +jep+ (str sym))))

(defmethod print-method PyReturn
  [v w]
  (.write w (str v)))

(defmacro hy
  [& body]
  `(hy-gets +jep+ (quote ~body)))

(defmacro defpy
  [sym form]
  `(def ~sym (do (hy-eval +jep+ (quote (~'setv ~sym ~form)))
                 (PyReturn. ~(munge (str sym))))))
```

It actually works really well  and I can write code like:

```clojure
(defpy j (+ 1 2 3 4))
(defpy div-2 (fn [x] (/ x 2)))
(defpy y (div-2 j))

@y => 5
```

However, when I disconnect and then connect back, I'm getting an invalid Thread access exception:

```
Caused by jep.JepException
   Invalid thread access.

                  Jep.java:  346  jep.Jep/isValidThread
                  Jep.java:  477  jep.Jep/exec
                       nil:   -1  jdk.internal.reflect.GeneratedMethodAccessor10/invoke
DelegatingMethodAccessorImpl.java:   43  jdk.internal.reflect.DelegatingMethodAccessorImpl/invoke
               Method.java:  566  java.lang.reflect.Method/invoke
            Reflector.java:  167  clojure.lang.Reflector/invokeMatchingMethod
            Reflector.java:  102  clojure.lang.Reflector/invokeInstanceMethod
                python.clj:   19  statstrade.service.python/hy-eval
                python.clj:   17  statstrade.service.python/hy-eval
                  AFn.java:  156  clojure.lang.AFn/applyToHelper
```

And I also cannot close jep either

```clojure
(.close +jep+)
```

leads to

```
 Unhandled jep.JepException
   JEP THREAD WARNING: Unsafe close() of Python sub-interpreter by
   thread nRepl-session-518bb241-7cf5-4efe-902e-d04d3ab85d9d.  Please
   close() from the creating thread to ensure stability.

                  Jep.java: 1040  jep.Jep/close
NativeMethodAccessorImpl.java:   -2  jdk.internal.reflect.NativeMethodAccessorImpl/invoke0
NativeMethodAccessorImpl.java:   62  jdk.internal.reflect.NativeMethodAccessorImpl/invoke
DelegatingMethodAccessorImpl.java:   43  jdk.internal.reflect.DelegatingMethodAccessorImpl/invoke
               Method.java:  566  java.lang.reflect.Method/invoke
            Reflector.java:  167  clojure.lang.Reflector/invokeMatchingMethod
            Reflector.java:  438  clojure.lang.Reflector/invokeNoArgInstanceMember
                      REPL:   14  statstrade.service.python/eval16114
```

**Comment by zcaudate** [comment]
Is there anyway around it? and also, are there ways to create another SharedInterpreter in the same session?

**Comment by bsteffensmeier** [comment]
All interaction with a Jep Interpreter must happen on the same thread, there is no way around that. There are some carefully managed resources in the cpython interpreter that depend on thread local variables we cannot change so trying to allow multithreaded usage tends to decrease stability.

If you have code or datastructures you want to share I recommend putting them in a python module and importing it into multiple SharedInterpreters. SharedInterpreters will use the exact same module object so it will only be initialized by the first shared interpreter and other interpreters will be able to reuse anything within that module.

**Comment by zcaudate** [comment]
@bsteffensmeier: 

Yes, I'd like to be able to have multiple SharedInterpreters running. However, it's not working for me at the moment. 

```

1. Unhandled jep.JepException
   JEP THREAD WARNING: Unsafe reuse of thread
   nRepl-session-d03dea19-dc14-4abb-87a3-1251a81a6465 for another
   Python sub-interpreter.  Please close() the previous Jep instance
   to ensure stability.

                  Jep.java:  263  jep.Jep/<init>
    SharedInterpreter.java:   56  jep.SharedInterpreter/<init>
                      REPL:   17  hara.lib.jep/eval23435
```

Also, can you explain `If you have code or datastructures you want to share I recommend putting them in a python module and importing it into multiple SharedInterpreters` a bit more. For example, if I wanted to submit jobs to a shared dask infrastructure from clojure, can I use the method you described?

**Comment by bsteffensmeier** [comment]
You can only have one Interpreter on a thread at a time. That error indicates you already have an interpreter on the thread and you are trying to create another one. You must close the existing interpreters that are using the thread before opening a new one.

You can see an example of using a module to share data between interpreters in our tests at [TestSharedInterpreter](https://github.com/ninia/jep/blob/dev_3.9/src/test/java/jep/test/TestSharedInterpreter.java). In this case I created a new list on the sys module and then I access and modify that list from many SharedInterpreters running on different threads. I do not recommend abusing the sys module like this but you can do the same thing using a module you create and you should be able to store and reuse any python objects within that module.

**Comment by zcaudate** [comment]
I created a single thread that initiates the interpreter then listens to an input queue to pass back to the interpreter. It works pretty well.

Is there a reason why environments are isolated via threads?

**Comment by bsteffensmeier** [comment]
There are some carefully managed resources in the cpython interpreter that depend on thread local variables we cannot change so trying to allow multithreaded usage tends to decrease stability. Specifically the [PyGILState API](https://docs.python.org/3/c-api/init.html#non-python-created-threads) is a significant obstacle to multiple interpreters on a a thread.

**Comment by zcaudate** [comment]
Thanks for link. I understand what Jep is doing a lot better now.
