### ISSUE TITLE
How to force close a session

### ISSUE THREAD

**Issue by zcaudate** [ninia/jep#262]
Is there a way to force close an Interpreter from another thread (the interpreter remains even though the created thread has finished)

1. Unhandled jep.JepException
   JEP THREAD WARNING: Unsafe close() of Python sub-interpreter by
   thread nRepl-session-35a569d1-854c-48b5-9737-f35e6b9db17b.  Please
   close() from the creating thread to ensure stability.

                  Jep.java: 1040  jep.Jep/close

**Comment by bsteffensmeier** [comment]
No. You must create, use, and close the interpreter on the thread where it was created.

**Comment by zcaudate** [comment]
thanks. I figured it out.
