### ISSUE TITLE
How to interrupt a long running process?

### ISSUE THREAD

**Issue by zcaudate** [ninia/jep#263]
Is there a way to stop a long running `.exec` process?

For example, if there was a call to download `tensorflow` in a SharedInterpretor, which might take ages because of network issues, how would be the best way to stop the download?

**Comment by bsteffensmeier** [comment]
Is it possible to interrupt a tensorflow download in a python application with multiple threads? If it is possible then please provide more details on how that is done, it should also be possible from Jep. If it is not possible to interrupt a tensorflow download in a python application with multiple threads then it will not be possible in jep.

**Comment by zcaudate** [comment]
I'm not sure if it is actually possible via python but that may be the best option. thanks.

**Comment by jsnps** [comment]
@bsteffensmeier 
Do you see a way to achieve this with the PyThreadState_SetAsyncExc trick?

The examples, I'm seeing are typically using threading.ident() as ID, which returns null on a java thread and afaik is different from the os thread id. Yet, jep creates a PyThreadState which holds a thread_id - is there any way to get this id from java (maybe on the same thread, before the task starts?) and inject an exception from another thread? Would it be the "expected" id for the setAsyncExc API?

https://discuss.python.org/t/what-about-interruptible-threads/17373/19
https://docs.python.org/3/c-api/init.html#c.PyThreadState_SetAsyncExc
https://github.com/kata198/func_timeout/blob/50baa8db502fd24acc0f2a1bc473649505336997/func_timeout/StoppableThread.py#L125

**Comment by bsteffensmeier** [comment]
That is really interesting, I don't think I have looked at that function before. It looks like the thread_id in the PyThreadState jep creates is [the id it is looking for](https://github.com/python/cpython/blob/7cee276d551a41d9271daf2a6bcd7def55555973/Python/pystate.c#L2186) so it should be theoretically possible to add something to expose that. I do not think there is any way in the current jep code to get that id in either java or python.

We could consider adding something to the Interpreter interface to expose that function. The biggest complication I can think of would be how to create the exception. For a SharedInterpreter you could create an exception from another SharedInterpreter on the thread doing the interupting but for a SubInterpreter I think you would have to create an exception beforehand and hang onto it in java to use when setting the exception.

Adding that would take more time than I can give jep right now but if someone has a use case where this would help and wants to contribute a PR then I think this is something that makes sense for jep.
