### ISSUE TITLE
Warning on platform depencency

### ISSUE THREAD

**Issue by Reissner** [ninia/jep#267]
**Describe the problem**
command mvn install yields 
```
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
```
which is easily to resolve: 
just add definition of encoding in pom. 
My environment is linux but i think this is a quire general problem. 

Sent already a pull request.

**Comment by valoeghese** [comment]
should this issue be closed?
