### ISSUE TITLE
Inappropriate Exception in call to method in MainInterpreter

### ISSUE THREAD

**Issue by Reissner** [ninia/jep#269]
In class MainInterpreter, methods setInitParams, setSharedModulesArgv and setJepLibraryPath 
throw a JepException when called after initializing the python interpreter. 

This is not appropriate i feel. 
Instead IllegalStateException is forseen 
as these methods are called in a state in which calling them is not allowed. 
From the documentation of IllegalStateException: 
```
Signals that a method has been invoked at an illegal or inappropriate time. 
In other words, the Java environment or Java application is not in an appropriate state 
for the requested operation.
```
Also this is an unchecked exception, whereas JepException is checked 
which forces the caller to declare in calling method or to try catch it. 
Both really cumbersome. 
With IllegalStateException, this is not needed. 
The case an exception is thrown can be solved by changing implementation. 
So no need to check. 

Similar case: SharedInterpreter.setConfig(JepConfig). 
But here, only part can be resolved using IllegalStateException. 
The other exception (caused by SharedModules) must be treated differently.

**Comment by ndjensen** [comment]
[As previously stated](https://github.com/ninia/jep/issues/249#issuecomment-626032683), JepException will become an unchecked RuntimeException in Jep 4.0.  We don't want to change it or the method signatures or behavior in the Jep 3.x series.  Please submit a pull request to the dev_4.0 branch to change the few spots you think IllegalStateException is more appropriate than JepException.

**Comment by ndjensen** [comment]
Exceptions have been changed on dev_4.0 branch here: https://github.com/ninia/jep/commit/a06d949f2d5036234fdd30efc89540410868151c
