### ISSUE TITLE
Is there a way of directly accessing the memory address of an interpretor object?

### ISSUE THREAD

**Issue by zcaudate** [ninia/jep#270]
I'd like to be able to create a pyarrow object and have it's memory passed to java and vice versa, is there a good way of doing this?

**Comment by bsteffensmeier** [comment]
Yes, use [PyObject](http://ninia.github.io/jep/javadoc/3.9/jep/python/PyObject.html) to access a python object form java without copying any memory. You can get a PyObject by passing `PyObject.class` as the second argument to [Interpreter.getValue()](http://ninia.github.io/jep/javadoc/3.9/jep/Interpreter.html#getValue-java.lang.String-java.lang.Class-)

**Comment by zcaudate** [comment]
thanks. that's really great help.
