### ISSUE TITLE
Jep with restricted privileges

### ISSUE THREAD

**Issue by s16508pjwstk** [ninia/jep#277]
Hi, 

I have an application which allows the user to execute python code in embedded mode using jep. Whole app is run on ubuntu with sudo user due to many system operations being performed during app runtime.

Unfortunately this implementation allows our app user to perform unwanted vulnerable system operation on server via python code execution.

Is there is any possibility to run Jep with restricted privileges to avoid problems mentioned above?

Thanks in advance.

**Comment by bsteffensmeier** [comment]
Since jep runs python in the same process as your application it will always have the same privileges as the rest of your application. I do not see any way we could possibly help restrict privileges.

**Comment by s16508pjwstk** [comment]
hmm, that's not good.
Have you ever encountered such a case like this? The only thing I want to achieve is dangerous code execution blocking.
Code filtering isn't perfect solution, it's too easy to bypass.

**Comment by bsteffensmeier** [comment]
Other users have reported a desire to restrict python but I am not aware of anyone who has been successful. Python itself does not easily support restricted execution of user supplied code, Python does not become more secure by embedding it in Java.

**Comment by Stewori** [comment]
For this issue you may want to consider using Jython (if you can do without C-extensions and using Python 2 for now). It can run Python code subject to Java security managers. (Of course there may still be security holes in the JVM, but that's a different story.)

**Comment by s16508pjwstk** [comment]
Ok, thank you for an explanation.
