### ISSUE TITLE
Jep doesn't build for Python 3.7.3 in Windows 10

### ISSUE THREAD

**Issue by muratcanozdemir** [ninia/jep#278]
**Describe the problem**
I tried building Jep to install it in my local Windows 10 machine with every single available MSVC compiler out there, from 14.10 to 14.26, but it always returns this error with VC14.1 missing. I checked the installation folders in my local drive, run the distutils code snippets to trace the result there when it finds a valid VC14 compiler (it finds the correct directory), but the installation script cannot find this, and fails there every single time. Honestly it would be much easier if there would be a .whl installation available, given the difficulties in Windows machines still not completely solved.

**Environment (please complete the following information):**
- OS Platform, Distribution, and Version: Windows 10 Enterprise, 1909
- Python Distribution and Version: Python 3.7.3
- Java Distribution and Version: JDK 1.8.252
- Jep Version: 3.9.0
- Python packages used (e.g. numpy, pandas, tensorflow):  time, socket, logging

**Logs**
Please attach the complete console output of the build.

Collecting jep
  Using cached jep-3.9.0.tar.gz (3.0 MB)
Building wheels for collected packages: jep
  Building wheel for jep (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\program files (x86)\python37-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = 
...
  Complete output (94 lines):
  numpy include found at c:\program files (x86)\python37-32\lib\site-packages\numpy\core\include
  running bdist_wheel
  running build
  running setup_java
  Using JAVA_HOME: C:\DEV\JDK
  running build_java
  C:\DEV\JDK\bin\javac.exe -deprecation -d build\java -classpath src src\main\java\jep\AbstractNDArray.java src\main\java\jep\ClassEnquirer.java src\main\java\jep\ClassList.java src\main\java\jep\DirectNDArray.java src\main\java\jep\Interpreter.java src\main\java\jep\Jep.java src\main\java\jep\JepAccess.java src\main\java\jep\JepConfig.java src\main\java\jep\JepException.java src\main\java\jep\LibraryLocator.java src\main\java\jep\MainInterpreter.java src\main\java\jep\NamingConventionClassEnquirer.java src\main\java\jep\NDArray.java src\main\java\jep\Proxy.java src\main\java\jep\PyConfig.java src\main\java\jep\Run.java src\main\java\jep\SharedInterpreter.java src\main\java\jep\SubInterpreter.java src\main\java\jep\Util.java src\main\java\jep\python\InvocationHandler.java src\main\java\jep\python\MemoryManager.java src\main\java\jep\python\PyCallable.java src\main\java\jep\python\PyObject.java src\main\java\jep\python\PyPointer.java
  Picked up _JAVA_OPTIONS: -Djava.net.preferIPv4Stack=true
  C:\DEV\JDK\bin\javah.exe -classpath build\java -d build\include jep.Jep jep.MainInterpreter jep.python.InvocationHandler jep.python.PyObject jep.python.PyCallable jep.python.PyPointer
  Picked up _JAVA_OPTIONS: -Djava.net.preferIPv4Stack=true
  C:\DEV\JDK\bin\javac.exe -deprecation -d build\java\test -classpath build\java;src src\test\java\jep\test\Test.java src\test\java\jep\test\TestCloseWithThreads.java src\test\java\jep\test\TestCompiledScript.java src\test\java\jep\test\TestDefaultMethods.java src\test\java\jep\test\TestExceptionCause.java src\test\java\jep\test\TestExec.java src\test\java\jep\test\TestGetByteArray.java src\test\java\jep\test\TestGetCollectionBoxing.java src\test\java\jep\test\TestGetJPyObject.java src\test\java\jep\test\TestGetTempValue.java src\test\java\jep\test\TestGetWithClass.java src\test\java\jep\test\TestInvoke.java src\test\java\jep\test\TestOverload.java src\test\java\jep\test\TestPreInitVariables.java src\test\java\jep\test\TestSharedArgv.java src\test\java\jep\test\TestSharedInterpreter.java src\test\java\jep\test\TestSharedModules.java src\test\java\jep\test\TestSharedModulesThreads.java src\test\java\jep\test\closeable\TestAutoCloseable.java src\test\java\jep\test\numpy\TestNumpy.java src\test\java\jep\test\numpy\TestNumpyArrayToString.java src\test\java\jep\test\numpy\TestNumpyProdShared.java src\test\java\jep\test\numpy\example\TestNumpyGILFreeze.java src\test\java\jep\test\numpy\example\TestNumpyMemoryLeak.java src\test\java\jep\test\numpy\example\TestNumpyProdLost.java src\test\java\jep\test\numpy\example\TestScipyFreeze.java src\test\java\jep\test\synchronization\TestCrossLangSync.java src\test\java\jep\test\types\TestFieldTypes.java src\test\java\jep\test\types\TestMethodTypes.java src\test\java\jep\test\types\TestStaticFieldTypes.java src\test\java\jep\test\types\TestStaticMethodTypes.java
  Picked up _JAVA_OPTIONS: -Djava.net.preferIPv4Stack=true
  copying src\main\java\jep\AbstractNDArray.java to build\java\jep.src\main\java\jep\AbstractNDArray.java
  copying src\main\java\jep\ClassEnquirer.java to build\java\jep.src\main\java\jep\ClassEnquirer.java
  copying src\main\java\jep\ClassList.java to build\java\jep.src\main\java\jep\ClassList.java
  copying src\main\java\jep\DirectNDArray.java to build\java\jep.src\main\java\jep\DirectNDArray.java
  copying src\main\java\jep\Interpreter.java to build\java\jep.src\main\java\jep\Interpreter.java
  copying src\main\java\jep\Jep.java to build\java\jep.src\main\java\jep\Jep.java
  copying src\main\java\jep\JepAccess.java to build\java\jep.src\main\java\jep\JepAccess.java
  copying src\main\java\jep\JepConfig.java to build\java\jep.src\main\java\jep\JepConfig.java
  copying src\main\java\jep\JepException.java to build\java\jep.src\main\java\jep\JepException.java
  copying src\main\java\jep\LibraryLocator.java to build\java\jep.src\main\java\jep\LibraryLocator.java
  copying src\main\java\jep\MainInterpreter.java to build\java\jep.src\main\java\jep\MainInterpreter.java
  copying src\main\java\jep\NamingConventionClassEnquirer.java to build\java\jep.src\main\java\jep\NamingConventionClassEnquirer.java
  copying src\main\java\jep\NDArray.java to build\java\jep.src\main\java\jep\NDArray.java
  copying src\main\java\jep\Proxy.java to build\java\jep.src\main\java\jep\Proxy.java
  copying src\main\java\jep\PyConfig.java to build\java\jep.src\main\java\jep\PyConfig.java
  copying src\main\java\jep\Run.java to build\java\jep.src\main\java\jep\Run.java
  copying src\main\java\jep\SharedInterpreter.java to build\java\jep.src\main\java\jep\SharedInterpreter.java
  copying src\main\java\jep\SubInterpreter.java to build\java\jep.src\main\java\jep\SubInterpreter.java
  copying src\main\java\jep\Util.java to build\java\jep.src\main\java\jep\Util.java
  copying src\main\java\jep\python\InvocationHandler.java to build\java\jep.src\main\java\jep\python\InvocationHandler.java
  copying src\main\java\jep\python\MemoryManager.java to build\java\jep.src\main\java\jep\python\MemoryManager.java
  copying src\main\java\jep\python\PyCallable.java to build\java\jep.src\main\java\jep\python\PyCallable.java
  copying src\main\java\jep\python\PyObject.java to build\java\jep.src\main\java\jep\python\PyObject.java
  copying src\main\java\jep\python\PyPointer.java to build\java\jep.src\main\java\jep\python\PyPointer.java
  copying src\test\java\jep\test\Test.java to build\java\jep.test.src\test\java\jep\test\Test.java
  copying src\test\java\jep\test\TestCloseWithThreads.java to build\java\jep.test.src\test\java\jep\test\TestCloseWithThreads.java
  copying src\test\java\jep\test\TestCompiledScript.java to build\java\jep.test.src\test\java\jep\test\TestCompiledScript.java
  copying src\test\java\jep\test\TestDefaultMethods.java to build\java\jep.test.src\test\java\jep\test\TestDefaultMethods.java
  copying src\test\java\jep\test\TestExceptionCause.java to build\java\jep.test.src\test\java\jep\test\TestExceptionCause.java
  copying src\test\java\jep\test\TestExec.java to build\java\jep.test.src\test\java\jep\test\TestExec.java
  copying src\test\java\jep\test\TestGetByteArray.java to build\java\jep.test.src\test\java\jep\test\TestGetByteArray.java
  copying src\test\java\jep\test\TestGetCollectionBoxing.java to build\java\jep.test.src\test\java\jep\test\TestGetCollectionBoxing.java
  copying src\test\java\jep\test\TestGetJPyObject.java to build\java\jep.test.src\test\java\jep\test\TestGetJPyObject.java
  copying src\test\java\jep\test\TestGetTempValue.java to build\java\jep.test.src\test\java\jep\test\TestGetTempValue.java
  copying src\test\java\jep\test\TestGetWithClass.java to build\java\jep.test.src\test\java\jep\test\TestGetWithClass.java
  copying src\test\java\jep\test\TestInvoke.java to build\java\jep.test.src\test\java\jep\test\TestInvoke.java
  copying src\test\java\jep\test\TestOverload.java to build\java\jep.test.src\test\java\jep\test\TestOverload.java
  copying src\test\java\jep\test\TestPreInitVariables.java to build\java\jep.test.src\test\java\jep\test\TestPreInitVariables.java
  copying src\test\java\jep\test\TestSharedArgv.java to build\java\jep.test.src\test\java\jep\test\TestSharedArgv.java
  copying src\test\java\jep\test\TestSharedInterpreter.java to build\java\jep.test.src\test\java\jep\test\TestSharedInterpreter.java
  copying src\test\java\jep\test\TestSharedModules.java to build\java\jep.test.src\test\java\jep\test\TestSharedModules.java
  copying src\test\java\jep\test\TestSharedModulesThreads.java to build\java\jep.test.src\test\java\jep\test\TestSharedModulesThreads.java
  copying src\test\java\jep\test\closeable\TestAutoCloseable.java to build\java\jep.test.src\test\java\jep\test\closeable\TestAutoCloseable.java
  copying src\test\java\jep\test\numpy\TestNumpy.java to build\java\jep.test.src\test\java\jep\test\numpy\TestNumpy.java
  copying src\test\java\jep\test\numpy\TestNumpyArrayToString.java to build\java\jep.test.src\test\java\jep\test\numpy\TestNumpyArrayToString.java
  copying src\test\java\jep\test\numpy\TestNumpyProdShared.java to build\java\jep.test.src\test\java\jep\test\numpy\TestNumpyProdShared.java
  copying src\test\java\jep\test\numpy\example\TestNumpyGILFreeze.java to build\java\jep.test.src\test\java\jep\test\numpy\example\TestNumpyGILFreeze.java
  copying src\test\java\jep\test\numpy\example\TestNumpyMemoryLeak.java to build\java\jep.test.src\test\java\jep\test\numpy\example\TestNumpyMemoryLeak.java
  copying src\test\java\jep\test\numpy\example\TestNumpyProdLost.java to build\java\jep.test.src\test\java\jep\test\numpy\example\TestNumpyProdLost.java
  copying src\test\java\jep\test\numpy\example\TestScipyFreeze.java to build\java\jep.test.src\test\java\jep\test\numpy\example\TestScipyFreeze.java
  copying src\test\java\jep\test\synchronization\TestCrossLangSync.java to build\java\jep.test.src\test\java\jep\test\synchronization\TestCrossLangSync.java
  copying src\test\java\jep\test\types\TestFieldTypes.java to build\java\jep.test.src\test\java\jep\test\types\TestFieldTypes.java
  copying src\test\java\jep\test\types\TestMethodTypes.java to build\java\jep.test.src\test\java\jep\test\types\TestMethodTypes.java
  copying src\test\java\jep\test\types\TestStaticFieldTypes.java to build\java\jep.test.src\test\java\jep\test\types\TestStaticFieldTypes.java
  copying src\test\java\jep\test\types\TestStaticMethodTypes.java to build\java\jep.test.src\test\java\jep\test\types\TestStaticMethodTypes.java
  running build_jar
  copying src/main/resources/jep/classlist_7.txt to build/java/jep
  copying src/main/resources/jep/classlist_8.txt to build/java/jep
  copying src/main/resources/jep/classlist_9.txt to build/java/jep
  copying src/main/resources/jep/classlist_10.txt to build/java/jep
  copying src/main/resources/jep/classlist_11.txt to build/java/jep
  C:\DEV\JDK\bin\jar.exe -cf build/java/jep-3.9.0-sources.jar -C build/java/jep.src/main/java jep
  Picked up _JAVA_OPTIONS: -Djava.net.preferIPv4Stack=true
  C:\DEV\JDK\bin\jar.exe -cfe build/java/jep-3.9.0.jar jep.Run -C build/java jep
  Picked up _JAVA_OPTIONS: -Djava.net.preferIPv4Stack=true
  C:\DEV\JDK\bin\jar.exe -cf build/java/jep-3.9.0-test-sources.jar -C build/java/jep.test.src/test/java jep
  Picked up _JAVA_OPTIONS: -Djava.net.preferIPv4Stack=true
  C:\DEV\JDK\bin\jar.exe -cfe build/java/jep-3.9.0-test.jar test.jep.Test -C build/java/test jep
  Picked up _JAVA_OPTIONS: -Djava.net.preferIPv4Stack=true
  running build_py
  creating build\lib.win32-3.7
  creating build\lib.win32-3.7\jep
  copying src\main\python\jep\console.py -> build\lib.win32-3.7\jep
  copying src\main\python\jep\java_import_hook.py -> build\lib.win32-3.7\jep
  copying src\main\python\jep\jdbc.py -> build\lib.win32-3.7\jep
  copying src\main\python\jep\redirect_streams.py -> build\lib.win32-3.7\jep
  copying src\main\python\jep\shared_modules_hook.py -> build\lib.win32-3.7\jep
  copying src\main\python\jep\version.py -> build\lib.win32-3.7\jep
  copying src\main\python\jep\__init__.py -> build\lib.win32-3.7\jep
  running build_ext
  building 'jep' extension
  error: Microsoft Visual C++ 14.1 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
  ----------------------------------------
  ERROR: Failed building wheel for jep
  Running setup.py clean for jep
Failed to build jep
DEPRECATION: Could not build wheels for jep which do not use PEP 517. pip will fall back to legacy 'setup.py install' for these. pip 21.0 will remove support for this functionality. A possible replacement is to fix the wheel build issue reported above. You can find discussion regarding this at https://github.com/pypa/pip/issues/8368.
Installing collected packages: jep
    Running setup.py install for jep ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\program files (x86)\python37-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = 
...
    Complete output (94 lines):
    numpy include found at c:\program files (x86)\python37-32\lib\site-packages\numpy\core\include
    running install
    running build
    running setup_java
    Using JAVA_HOME: C:\DEV\JDK
    running build_java
    C:\DEV\JDK\bin\javac.exe -deprecation -d build\java -classpath src src\main\java\jep\AbstractNDArray.java src\main\java\jep\ClassEnquirer.java src\main\java\jep\ClassList.java src\main\java\jep\DirectNDArray.java src\main\java\jep\Interpreter.java src\main\java\jep\Jep.java src\main\java\jep\JepAccess.java src\main\java\jep\JepConfig.java src\main\java\jep\JepException.java src\main\java\jep\LibraryLocator.java src\main\java\jep\MainInterpreter.java src\main\java\jep\NamingConventionClassEnquirer.java src\main\java\jep\NDArray.java src\main\java\jep\Proxy.java src\main\java\jep\PyConfig.java src\main\java\jep\Run.java src\main\java\jep\SharedInterpreter.java src\main\java\jep\SubInterpreter.java src\main\java\jep\Util.java src\main\java\jep\python\InvocationHandler.java src\main\java\jep\python\MemoryManager.java src\main\java\jep\python\PyCallable.java src\main\java\jep\python\PyObject.java src\main\java\jep\python\PyPointer.java
    Picked up _JAVA_OPTIONS: -Djava.net.preferIPv4Stack=true
    C:\DEV\JDK\bin\javah.exe -classpath build\java -d build\include jep.Jep jep.MainInterpreter jep.python.InvocationHandler jep.python.PyObject jep.python.PyCallable jep.python.PyPointer
    Picked up _JAVA_OPTIONS: -Djava.net.preferIPv4Stack=true
    C:\DEV\JDK\bin\javac.exe -deprecation -d build\java\test -classpath build\java;src src\test\java\jep\test\Test.java src\test\java\jep\test\TestCloseWithThreads.java src\test\java\jep\test\TestCompiledScript.java src\test\java\jep\test\TestDefaultMethods.java src\test\java\jep\test\TestExceptionCause.java src\test\java\jep\test\TestExec.java src\test\java\jep\test\TestGetByteArray.java src\test\java\jep\test\TestGetCollectionBoxing.java src\test\java\jep\test\TestGetJPyObject.java src\test\java\jep\test\TestGetTempValue.java src\test\java\jep\test\TestGetWithClass.java src\test\java\jep\test\TestInvoke.java src\test\java\jep\test\TestOverload.java src\test\java\jep\test\TestPreInitVariables.java src\test\java\jep\test\TestSharedArgv.java src\test\java\jep\test\TestSharedInterpreter.java src\test\java\jep\test\TestSharedModules.java src\test\java\jep\test\TestSharedModulesThreads.java src\test\java\jep\test\closeable\TestAutoCloseable.java src\test\java\jep\test\numpy\TestNumpy.java src\test\java\jep\test\numpy\TestNumpyArrayToString.java src\test\java\jep\test\numpy\TestNumpyProdShared.java src\test\java\jep\test\numpy\example\TestNumpyGILFreeze.java src\test\java\jep\test\numpy\example\TestNumpyMemoryLeak.java src\test\java\jep\test\numpy\example\TestNumpyProdLost.java src\test\java\jep\test\numpy\example\TestScipyFreeze.java src\test\java\jep\test\synchronization\TestCrossLangSync.java src\test\java\jep\test\types\TestFieldTypes.java src\test\java\jep\test\types\TestMethodTypes.java src\test\java\jep\test\types\TestStaticFieldTypes.java src\test\java\jep\test\types\TestStaticMethodTypes.java
    Picked up _JAVA_OPTIONS: -Djava.net.preferIPv4Stack=true
    copying src\main\java\jep\AbstractNDArray.java to build\java\jep.src\main\java\jep\AbstractNDArray.java
    copying src\main\java\jep\ClassEnquirer.java to build\java\jep.src\main\java\jep\ClassEnquirer.java
    copying src\main\java\jep\ClassList.java to build\java\jep.src\main\java\jep\ClassList.java
    copying src\main\java\jep\DirectNDArray.java to build\java\jep.src\main\java\jep\DirectNDArray.java
    copying src\main\java\jep\Interpreter.java to build\java\jep.src\main\java\jep\Interpreter.java
    copying src\main\java\jep\Jep.java to build\java\jep.src\main\java\jep\Jep.java
    copying src\main\java\jep\JepAccess.java to build\java\jep.src\main\java\jep\JepAccess.java
    copying src\main\java\jep\JepConfig.java to build\java\jep.src\main\java\jep\JepConfig.java
    copying src\main\java\jep\JepException.java to build\java\jep.src\main\java\jep\JepException.java
    copying src\main\java\jep\LibraryLocator.java to build\java\jep.src\main\java\jep\LibraryLocator.java
    copying src\main\java\jep\MainInterpreter.java to build\java\jep.src\main\java\jep\MainInterpreter.java
    copying src\main\java\jep\NamingConventionClassEnquirer.java to build\java\jep.src\main\java\jep\NamingConventionClassEnquirer.java
    copying src\main\java\jep\NDArray.java to build\java\jep.src\main\java\jep\NDArray.java
    copying src\main\java\jep\Proxy.java to build\java\jep.src\main\java\jep\Proxy.java
    copying src\main\java\jep\PyConfig.java to build\java\jep.src\main\java\jep\PyConfig.java
    copying src\main\java\jep\Run.java to build\java\jep.src\main\java\jep\Run.java
    copying src\main\java\jep\SharedInterpreter.java to build\java\jep.src\main\java\jep\SharedInterpreter.java
    copying src\main\java\jep\SubInterpreter.java to build\java\jep.src\main\java\jep\SubInterpreter.java
    copying src\main\java\jep\Util.java to build\java\jep.src\main\java\jep\Util.java
    copying src\main\java\jep\python\InvocationHandler.java to build\java\jep.src\main\java\jep\python\InvocationHandler.java
    copying src\main\java\jep\python\MemoryManager.java to build\java\jep.src\main\java\jep\python\MemoryManager.java
    copying src\main\java\jep\python\PyCallable.java to build\java\jep.src\main\java\jep\python\PyCallable.java
    copying src\main\java\jep\python\PyObject.java to build\java\jep.src\main\java\jep\python\PyObject.java
    copying src\main\java\jep\python\PyPointer.java to build\java\jep.src\main\java\jep\python\PyPointer.java
    copying src\test\java\jep\test\Test.java to build\java\jep.test.src\test\java\jep\test\Test.java
    copying src\test\java\jep\test\TestCloseWithThreads.java to build\java\jep.test.src\test\java\jep\test\TestCloseWithThreads.java
    copying src\test\java\jep\test\TestCompiledScript.java to build\java\jep.test.src\test\java\jep\test\TestCompiledScript.java
    copying src\test\java\jep\test\TestDefaultMethods.java to build\java\jep.test.src\test\java\jep\test\TestDefaultMethods.java
    copying src\test\java\jep\test\TestExceptionCause.java to build\java\jep.test.src\test\java\jep\test\TestExceptionCause.java
    copying src\test\java\jep\test\TestExec.java to build\java\jep.test.src\test\java\jep\test\TestExec.java
    copying src\test\java\jep\test\TestGetByteArray.java to build\java\jep.test.src\test\java\jep\test\TestGetByteArray.java
    copying src\test\java\jep\test\TestGetCollectionBoxing.java to build\java\jep.test.src\test\java\jep\test\TestGetCollectionBoxing.java
    copying src\test\java\jep\test\TestGetJPyObject.java to build\java\jep.test.src\test\java\jep\test\TestGetJPyObject.java
    copying src\test\java\jep\test\TestGetTempValue.java to build\java\jep.test.src\test\java\jep\test\TestGetTempValue.java
    copying src\test\java\jep\test\TestGetWithClass.java to build\java\jep.test.src\test\java\jep\test\TestGetWithClass.java
    copying src\test\java\jep\test\TestInvoke.java to build\java\jep.test.src\test\java\jep\test\TestInvoke.java
    copying src\test\java\jep\test\TestOverload.java to build\java\jep.test.src\test\java\jep\test\TestOverload.java
    copying src\test\java\jep\test\TestPreInitVariables.java to build\java\jep.test.src\test\java\jep\test\TestPreInitVariables.java
    copying src\test\java\jep\test\TestSharedArgv.java to build\java\jep.test.src\test\java\jep\test\TestSharedArgv.java
    copying src\test\java\jep\test\TestSharedInterpreter.java to build\java\jep.test.src\test\java\jep\test\TestSharedInterpreter.java
    copying src\test\java\jep\test\TestSharedModules.java to build\java\jep.test.src\test\java\jep\test\TestSharedModules.java
    copying src\test\java\jep\test\TestSharedModulesThreads.java to build\java\jep.test.src\test\java\jep\test\TestSharedModulesThreads.java
    copying src\test\java\jep\test\closeable\TestAutoCloseable.java to build\java\jep.test.src\test\java\jep\test\closeable\TestAutoCloseable.java
    copying src\test\java\jep\test\numpy\TestNumpy.java to build\java\jep.test.src\test\java\jep\test\numpy\TestNumpy.java
    copying src\test\java\jep\test\numpy\TestNumpyArrayToString.java to build\java\jep.test.src\test\java\jep\test\numpy\TestNumpyArrayToString.java
    copying src\test\java\jep\test\numpy\TestNumpyProdShared.java to build\java\jep.test.src\test\java\jep\test\numpy\TestNumpyProdShared.java
    copying src\test\java\jep\test\numpy\example\TestNumpyGILFreeze.java to build\java\jep.test.src\test\java\jep\test\numpy\example\TestNumpyGILFreeze.java
    copying src\test\java\jep\test\numpy\example\TestNumpyMemoryLeak.java to build\java\jep.test.src\test\java\jep\test\numpy\example\TestNumpyMemoryLeak.java
    copying src\test\java\jep\test\numpy\example\TestNumpyProdLost.java to build\java\jep.test.src\test\java\jep\test\numpy\example\TestNumpyProdLost.java
    copying src\test\java\jep\test\numpy\example\TestScipyFreeze.java to build\java\jep.test.src\test\java\jep\test\numpy\example\TestScipyFreeze.java
    copying src\test\java\jep\test\synchronization\TestCrossLangSync.java to build\java\jep.test.src\test\java\jep\test\synchronization\TestCrossLangSync.java
    copying src\test\java\jep\test\types\TestFieldTypes.java to build\java\jep.test.src\test\java\jep\test\types\TestFieldTypes.java
    copying src\test\java\jep\test\types\TestMethodTypes.java to build\java\jep.test.src\test\java\jep\test\types\TestMethodTypes.java
    copying src\test\java\jep\test\types\TestStaticFieldTypes.java to build\java\jep.test.src\test\java\jep\test\types\TestStaticFieldTypes.java
    copying src\test\java\jep\test\types\TestStaticMethodTypes.java to build\java\jep.test.src\test\java\jep\test\types\TestStaticMethodTypes.java
    running build_jar
    copying src/main/resources/jep/classlist_7.txt to build/java/jep
    copying src/main/resources/jep/classlist_8.txt to build/java/jep
    copying src/main/resources/jep/classlist_9.txt to build/java/jep
    copying src/main/resources/jep/classlist_10.txt to build/java/jep
    copying src/main/resources/jep/classlist_11.txt to build/java/jep
    C:\DEV\JDK\bin\jar.exe -cf build/java/jep-3.9.0-sources.jar -C build/java/jep.src/main/java jep
    Picked up _JAVA_OPTIONS: -Djava.net.preferIPv4Stack=true
    C:\DEV\JDK\bin\jar.exe -cfe build/java/jep-3.9.0.jar jep.Run -C build/java jep
    Picked up _JAVA_OPTIONS: -Djava.net.preferIPv4Stack=true
    C:\DEV\JDK\bin\jar.exe -cf build/java/jep-3.9.0-test-sources.jar -C build/java/jep.test.src/test/java jep
    Picked up _JAVA_OPTIONS: -Djava.net.preferIPv4Stack=true
    C:\DEV\JDK\bin\jar.exe -cfe build/java/jep-3.9.0-test.jar test.jep.Test -C build/java/test jep
    Picked up _JAVA_OPTIONS: -Djava.net.preferIPv4Stack=true
    running build_py
    creating build\lib.win32-3.7
    creating build\lib.win32-3.7\jep
    copying src\main\python\jep\console.py -> build\lib.win32-3.7\jep
    copying src\main\python\jep\java_import_hook.py -> build\lib.win32-3.7\jep
    copying src\main\python\jep\jdbc.py -> build\lib.win32-3.7\jep
    copying src\main\python\jep\redirect_streams.py -> build\lib.win32-3.7\jep
    copying src\main\python\jep\shared_modules_hook.py -> build\lib.win32-3.7\jep
    copying src\main\python\jep\version.py -> build\lib.win32-3.7\jep
    copying src\main\python\jep\__init__.py -> build\lib.win32-3.7\jep
    running build_ext
    building 'jep' extension
    error: Microsoft Visual C++ 14.1 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\program files (x86)\python37-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] =... Check the logs for full command output.

**Additional context**

**Comment by pacher** [comment]
How do you run it? Just `pip install jep` from command prompt? Are you sure it is the right prompt? For example I had to use `x64 Native Tools Command Prompt for VS 2019` shortcut in the start menu to start command prompt where jep built successfully. And even though it is a prompt for VS 2019, the build did not succeed until I installed build tools for VS 2015...

**Comment by muratcanozdemir** [comment]
Yeah, the correct procedure is to use VS 2015 Build Tools, so not v14.1.

**Comment by peteman001** [comment]
Greetings - we are having the same issue and are using this thread as a guide for solving (we feel we are close).   PACHER - can you clarify how you ran the command to install?  Your entry seems to indicate you have BOTH VS 2019 and 2015 installed.   Did you uninstall 2019 and replace it with 2015?

**Comment by peteman001** [comment]
Perhaps "muratcanozdemir" could clarify also how this was accomplished successfully?

**Comment by peteman001** [comment]
Update- in Win 10 we uninstalled VS 2019 and installed Build tools 2015.  Then from the Start menu we selected x64 Native Tools Command Prompt and once that window opened we simply typed  pip install jep.  And it worked.

Thank you leaving these hints.
