### ISSUE TITLE
How to load python without configuring environment variables？

### ISSUE THREAD

**Issue by caoruiahwh** [ninia/jep#279]
###   Describe the question
**To use jep, you must install python and configure environment variables. How to use libraries in java (such as numpy) without configuring environment variables?**
### Concrete example
    public static void main(String[] args) throws JepException {
        Interpreter interp = null;
        try {
            interp = new SubInterpreter();
            interp.exec("import io");
            interp.exec("sys.stdout = io.TextIOWrapper(sys.stdout.buffer,encoding='utf-8')");
            interp.exec("a=2"); 
            interp.exec("print(a)");
            interp.exec("x = a+2");  
            interp.exec("print(x+2)");
        } catch (Throwable e) {
            e.printStackTrace();
            System.exit(1);
        } finally {
            if (interp != null) {
                interp.close();
            }
        }
        System.exit(0);
    }

**When I delete the python system environment variable, the result of the operation will report an error, as shown below:**
java.lang.UnsatisfiedLinkError: C:\Program Files\Java\jdk1.8.0_11\jre\bin\jep.dll: Can't find dependent libraries
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1929)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1835)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1119)
	at jep.MainInterpreter.initialize(MainInterpreter.java:128)
	at jep.MainInterpreter.getMainInterpreter(MainInterpreter.java:101)
	at jep.Jep.<init>(Jep.java:256)
	at jep.Jep.<init>(Jep.java:251)
	at jep.SubInterpreter.<init>(SubInterpreter.java:63)
	at ChapterOne.Example1_1.main(Example1_1.java:16)

**How to solve this problem？**
### Environments
windows 10 
jep 3.9
python 3.6.8
The java compiler used is eclipse

**Comment by ndjensen** [comment]
You didn't state which environment variable you are deleting.  Regardless, you are getting into how the operating system finds and loads libraries.  Jep does not aim to solve that.

**Comment by caoruiahwh** [comment]
> You didn't state which environment variable you are deleting. Regardless, you are getting into how the operating system finds and loads libraries. Jep does not aim to solve that.

The deleted python environment variable is " D:\Program Files (x86)\python3.6;D:\Program Files (x86)\python3.6\Scripts;" in the Path of System variable. I tried to add the following code and modify PythonHome.In order not to load python through environment variables, but the same error as before occurred.
`PyConfig pyConfig = new PyConfig().setPythonHome("D:/Program Files (x86)/python3.6");
findJepLibrary(pyConfig);`

**Comment by bsteffensmeier** [comment]
#275 may help you, try installing jep from the dev_3.9 branch and see if that resolves your issue.

**Comment by caoruiahwh** [comment]
> #275 may help you, try installing jep from the dev_3.9 branch and see if that resolves your issue.

Your suggestion solved my problem perfectly, thanks.
