### ISSUE TITLE
How can I embed JEP into my application?

### ISSUE THREAD

**Issue by anthonyhu81** [ninia/jep#280]
I'd like to use JEP in my application and have get it to work with pip installed JEP. 
Is it possible to embed JEP package in my application so that the user do not need to setup build environment to install JEP?

Thanks!

**Comment by anthonyhu81** [comment]
Why the JEP package must locate in $Python_path/Lib/site-packages?
I moved the JEP package to other path (c:\\testpath\\), and create interpreter by following code:
    interp = new SubInterpreter( new JepConfig().setIncludePath("c:\\testpath"));
got  the JepExecption: jep.JepException: 
    <class 'ImportError'>: dynamic module does not define module export function (PyInit_jep)

How can I fix this?

**Comment by bsteffensmeier** [comment]
The problem with trying to package jep with a java application is that the jep liibrary is built for a specific version of python so you must have the same version of python installed on the system. If you are not also packaging python then it is likely you would run into issues with user having the wrong python version.

That error means that python was trying to import libjep, not the jep directory. Please ensure that c:\testpath contains a jep directory which should contain __init__.py, c:\testpath should not contain libjep.dll.

**Comment by anthonyhu81** [comment]
The path "c:\testpath\jep" has already been included in %path%

**Comment by anthonyhu81** [comment]
I can get it to work now, this maybe caused by the jep.pth file (has the content "c:\testpath\jep").
Removed this file, and jep works for me.

And have one more question, I build jep with Python3.8.2, this jep only can work with python3.8.2? or can work with all the python3.8.x?

**Comment by anthonyhu81** [comment]
It works with Python3.8.1, but not with Python3.7.9.

**Comment by anthonyhu81** [comment]
Thank you, bsteffensmeier
I will close this issue.
