### ISSUE TITLE
How to pass Java Maps, Iterables and Callables to Python

### ISSUE THREAD

**Issue by yunboouyang** [ninia/jep#281]
Following https://github.com/ninia/jep/wiki/How-Jep-Works, we can pass Java primitives and jep.NDArray to a python interpreter via Jep. 

However, passing non-primitive types involves de-constructing non-primitive types, sending to a python interpreter and re-constructing these types. I'm wondering how Jep deals with Java non-primitive types. For example, how do we pass Java Maps to python so that internally they could be converted to python dictionaries easily? From my experience I only got PyJObject from the point-of-view of the python interpreter and I cannot get data easily from a PyJObject. We have the similar need for Java Iterables and Callables.

**Comment by bsteffensmeier** [comment]
If you pass a Java map into the python interpreter you should get a pyjmap object in python, which provides similar functionality to a dict, for example you can access and assign objects to the map using [] indexing as though it were a dict. Similarly Java iterables are converted to pyjiterables which are iterable in Python and Callables are translated to pyjcallables which you can call in python just like any python callable. All these python classes extend PyJObject so you should be able to also use any regular java methods available on these objects from python to access any java functionality that isn't exposed through the python interface.

**Comment by yunboouyang** [comment]
Thank you for the quick reply! I just tried assigning objects to the map using [] indexing but the program failed with the error `jep.JepException: <class 'TypeError'>: 'jep.PyJObject' object does not support item assignment`. A simple code snippet to test it out is shown as follows:
```
    jep.set("d", Map(1 -> 1.0, 2 -> 2.0))
    jep.exec("d[1] = 2.0")
    jep.getValue("d").asInstanceOf[Map[Int, Double]]
```
I'm using jep 3.9.0.

**Comment by bsteffensmeier** [comment]
Pyjmap is only used if your object is an instanceof java.util.Map. It looks like you are using a scala map which isn't a java.util.Map. You will have to convert to a java.util.Map before passing your object to the interpreter or rely on calling java methods on your object from python to access the elements.

**Comment by yunboouyang** [comment]
Thank you! I tried java.util.Map. [] indexing can be used successfully. However other python dict methods for `PyJMap` like `items()` didn't work. Do you have any documentation about supported methods for `PyJMap`?

**Comment by bsteffensmeier** [comment]
I do not have any documentation. From [the source](https://github.com/ninia/jep/blob/master/src/main/c/Objects/pyjmap.c) it looks like we only iplement 4 etra methods in pyjmap, three of which are part of the [PyMappingMethods](https://docs.python.org/3/c-api/typeobj.html#c.PyMappingMethods) and the forth is contains so you can use `in`. For accessing the items you would have to use the java API so I recommend calling `entrySet` instead.

**Comment by ndjensen** [comment]
In general PyJMap and similar classes can handle Python syntax.  It should follow duck typing in that you shouldn't have to know if you're using a Python Dictionary or a Java Map.  For example, you can do the following with a PyJMap (I used the jep script to test this, you should play with that):

```python
from java.util import HashMap
x = HashMap()
x['abc'] = 1.0
x['def'] = 2.0
for i in x:
     print(i, x[i])
```
Methods available will be the Java object's public methods.  Since Jep is a Python interpreter, to see what's available use `dir(yourMapInstance)`.
```
>>> dir(x)
['clear', 'clone', 'compute', 'computeIfAbsent', 'computeIfPresent', 'containsKey', 'containsValue', 'entrySet', 'equals', 'forEach', 'get', 'getClass', 'getOrDefault', 'hashCode', 'isEmpty', 'java_name', 'keySet', 'merge', 'notify', 'notifyAll', 'put', 'putAll', 'putIfAbsent', 'remove', 'replace', 'replaceAll', 'size', 'toString', 'values', 'wait']
```
