### ISSUE TITLE
jep 3.8.2 console crashes when built and run inside a venv

### ISSUE THREAD

**Issue by tgurney** [ninia/jep#284]
```
(venv)$ jep
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007f7b6c1ea700 (most recent call first):
Aborted (core dumped)

```

Reproduction steps (run in bash, assumes jep package is downloaded to $HOME):
```
cd
python3 -m venv venv
source ~/venv/bin/activate
tar xf jep-3.8.2.tar.gz
cd jep-3.8.2/
python3 setup.py clean build install
jep
```

- OS Platform, Distribution, and Version: RHEL 7.8 x86_64
- Python Distribution and Version: Python 3.6.8-13 RHEL 7 RPM
- Java Distribution and Version: OpenJDK 11.0.8.10, from RHEL 7 RPM java-11-openjdk
- Jep Version: 3.8.2
- Python packages used: None, clean system Python 3 install and clean virtualenv.

Other info:
- I can successfully run /usr/bin/python3 and import encodings.
- jep console runs as expected when installed outside of the virtual environment, to the default /usr/local location.
- ~/venv/bin/jep looks like this:
```
#!/bin/sh

VIRTUAL_ENV=/home/tgurney/venv
export VIRTUAL_ENV


LD_LIBRARY_PATH="/usr/lib64:/home/tgurney/venv/lib64/python3.6/site-packages/"; export LD_LIBRARY_PATH
LD_PRELOAD="/usr/lib64/libpython3.6m.so"; export LD_PRELOAD

if test "x$VIRTUAL_ENV" != "x"; then
  PATH="$VIRTUAL_ENV/bin:$PATH"
  export PATH
  PYTHONHOME="$VIRTUAL_ENV"
  export PYTHONHOME
fi

cp="/home/tgurney/venv/lib64/python3.6/site-packages/jep/jep-3.8.2.jar"
if test "x$CLASSPATH" != "x"; then
    cp="$cp":"$CLASSPATH"
fi

jni_path="/home/tgurney/venv/lib64/python3.6/site-packages/jep"

args=$*
if test "x$args" = "x"; then
  args="/home/tgurney/venv/lib64/python3.6/site-packages/jep/console.py"
fi

exec java -classpath "$cp" -Djava.library.path="$jni_path" jep.Run $args
```

**Comment by bsteffensmeier** [comment]
If you modify ~/venv/bin/jep  and remove the lines that set PYTHONHOME does it work? I think we are not supposed to set PYTHONHOME for a venv.

**Comment by tgurney** [comment]
Yes, that seems to have fixed it.

**Comment by tgurney** [comment]
So is this a bug, or a problem with how I am installing jep?

**Comment by bsteffensmeier** [comment]
I think it is a bug and we need to remove those [2 lines from the script](https://github.com/ninia/jep/blob/dev_3.9/src/main/scripts/jep#L13). I'm not sure if that is true of all environments, especially python2 so we might need to make them conditional. I believe that script was written before python3 support was added.

**Comment by pradeepgowda21** [comment]
I'm using JEP 3.9.1, even then I get the same error in vEnv. But works like a charm outside the vEnv

System macOS

**Comment by bsteffensmeier** [comment]
Those two lines were removed in jep 3.9.1 with 3506fb8
