### ISSUE TITLE
Stream redirection to custom output streams

### ISSUE THREAD

**Issue by mathbagu** [ninia/jep#286]
**Is your feature request related to a problem? Please describe.**
In the current version I used (v.3.8), it's possible to redirect the outputs of the python interpreter to the Java `System.out` and `System.err`. In our integration, we would like to redirect these streams to custom OutputStreams, for instance the output in files, or to get the output as a string (ByteArrayOutputStream).

**Describe the solution you'd like**
I would like to be able to set the output stream and the error stream, as I can do with Jython for instance:
```
    pyInterp.setOut(context.getOutputStream());
    pyInterp.setErr(context.getErrorStream());
```

**Describe alternatives you've considered**
As a workaround, I copy/paste the `redirect_streams.py` script and change the code to access to a context object I previously add in the binding:
```
    jep.set("context", context);
    jep.runScript("/path/to/the/redirect_streams.py");
    jep.eval("setup()");
```

Example of changes I made in the script:
```
    def __init__(self):
        self.oldout = sys.stdout
        self.printmethod = getattr(context.getOutputStream(), 'print')
        self.flushmethod = getattr(context.getOutputStream(), 'flush')
```

**Additional context**
N/A

**Comment by ndjensen** [comment]
Makes sense.  Feel free to contribute a pull request.  If it gets worked we should do it on the dev_4.0 branch.

**Comment by mario45211** [comment]
+1

**Comment by pacher** [comment]
+1
I was asking for such a feature already (https://github.com/ninia/jep/issues/151#issuecomment-665732992) 
@mathbagu Are you planning to work on PR for this? Anybody else?

**Comment by ndjensen** [comment]
I'm committed this on the dev_4.0 branch.  https://github.com/ninia/jep/commit/f67b874b637e24ac3b725f2e89a57b51cded95e1

**Comment by ndjensen** [comment]
Closing as Jep 4.0 has now been released.
