### ISSUE TITLE
What is the mechanism of jep calling java files?

### ISSUE THREAD

**Issue by caoruiahwh** [ninia/jep#289]
**Describe the problem**
I try to use jep in my application, so I want to know how jep calls java through python code.

**Example**
            interp.exec("from ChapterTwo import Example2_4 as E2_4");
            interp.exec("Num=E2_4()");
            interp.exec("num=Num.testIntAdd(3,4)");
            interp.exec("print(num)");
-ChapterTwo is a java package;
-Example2_4(Example2_4.java) is a java file
What is the mechanism of python code calling java files?
**Environment (please complete the following information):**
- win10:
- python 3.6.8
- jdk1.8.0_11
- Jep3.9.1

**Comment by ndjensen** [comment]
For importing a Java class, Jep has a custom python import hook that imports a java.lang.Class as a PyJClass.  A PyJClass is a Python wrapper around the Java class.  Then Jep uses JNI when you call methods on Java objects.  For more information, see [the wiki](https://github.com/ninia/jep/wiki/How-Jep-Works).
