### ISSUE TITLE
type error after upgrade to jep 3.9.0 and python 3.8.5

### ISSUE THREAD

**Issue by fsauer65** [ninia/jep#290]
After upgrading from python 2.7.x to python 3.8.5 and jep 3.9.0, I see the following exception:

jep.JepException: <class 'TypeError'>: Buffer format 'l' is not valid for a byte[].
at jep.Jep.invoke(Native Method) at jep.Jep.invoke(Jep.java:396)
at com.***.aggregates.featsy.Featsy$.$anonfun$run$2(Featsy.scala:291)
at nl.grons.metrics4.scala.Timer.time(Timer.scala:54)
at com.***.aggregates.featsy.Featsy$.$anonfun$run$1(Featsy.scala:291)
at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:671)
at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:430)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)

The python code  I invoke returns a dictionary, which I cast to a Java Hashmap in my Scala code.
The dictionary does contain a Long, which may be where the 'l' comes from ??? this worked fine
in 2.7.x

python code:
def run(data):
    cstart = time.time()
    result = calc_feats(convert_jep(data))
    cend = time.time()
    result['featsy_perf'] = cend - cstart
    return result

Scala code:
interpreter.invoke("run", data.asInstanceOf[AnyRef]).asInstanceOf[JM]

where JM = 
  type JM = java.util.Map[String,Any]

**Comment by bsteffensmeier** [comment]
The error is coming from [here](https://github.com/ninia/jep/blob/dev_3.9/src/main/c/Jep/convert_p2j.c#L864). The code snippet you included does not provide any indication of how you would have ended up there. That code will hit when a Python object is converted to a Java object. The Python object being converted implements the [Buffer Protocol](https://docs.python.org/3/c-api/buffer.html) and based off your error the Python object contains unsigned ints. This object would be more complicated than a simple Long, it must be something like a array.array or a numpy array. To fix this you need to figure out which Python object is being converted and you will need to change the object to something that can be converted into the type of Java object you want.

**Comment by fsauer65** [comment]
Turns out there were some NumPy floats and ints in that dictionary... That was never an issue before, we did not even realize they were in there...

**Comment by bsteffensmeier** [comment]
If numpy is found when jep is built then jep will include advanced handling for numpy types that would prevent you from getting that error. Since you see that error I suspect that numpy was not found when jep is built. You could try rebuilding jep with numpy support to avoid that error. It seems likely that you may have been able to avoid the error in previous versions of jep if you had built jep to include numpy support.

**Comment by fsauer65** [comment]
all good now (but have another separate issue with a SIGSEGV), closing this one

**Comment by fsauer65** [comment]
fixed
