### ISSUE TITLE
Can't build container on Ubuntu 16

### ISSUE THREAD

**Issue by Matrix187** [ninia/jep#293]
**Describe the problem**
A clear and concise description of what the problem is.

**Search for existing solutions**
The Jep build is automatically tested and confirmed to be working in Linux, OS X, and Windows using Travis and AppVeyor. We cannot possibly test every environment so we rely on the community to document any issues and solutions in other environments. Please search for a similar problem and solution on both the [mailing list](https://groups.google.com/forum/#!forum/jep-project) and the existing closed github issues before opening a new issue.

**Environment (please complete the following information):**
- OS Platform, Distribution, and Version: Ubuntu 16.04.7 LTS 
- Python Distribution and Version: Python 3.7.4 
- Java Distribution and Version: openjdk version "1.8.0_265" OpenJDK Runtime Environment (build 1.8.0_265-8u265-b01-0ubuntu2~16.04-b01)
- Jep Version: latest from git
- Python packages used (e.g. numpy, pandas, tensorflow): none

**Logs**
Complete!
Loaded plugins: fastestmirror, ovl
Cleaning repos: base extras updates
Cleaning up list of fastest mirrors
Removing intermediate container fb19e392389d
 ---> c70ea5c6302f
Step 5/15 : ENV JAVA_HOME  /usr/java/jdk1.8.0_181-amd64
 ---> Running in 0735d6e49fe6
Removing intermediate container 0735d6e49fe6
 ---> b1bec64db5f1
Step 6/15 : RUN alternatives --set java $JAVA_HOME/jre/bin/java  && alternatives --set javac $JAVA_HOME/bin/javac
 ---> Running in 588039f2b624
/usr/java/jdk1.8.0_181-amd64/jre/bin/java has not been configured as an alternative for java
The command '/bin/sh -c alternatives --set java $JAVA_HOME/jre/bin/java  && alternatives --set javac $JAVA_HOME/bin/javac' returned a non-zero code: 2

**Additional context**
Trying to build it with command "docker build -t jep-app:latest ."

**Comment by bsteffensmeier** [comment]
You did not make it into the jep build, it appears to be a problem with your Dockerfile. WE do not maintain any Dockerfiles so your problem does not occur in any code or configuration that is part of this project.
