### ISSUE TITLE
A docker image for using Jep

### ISSUE THREAD

**Issue by Ben-Epstein** [ninia/jep#296]
I really like this project and I rely on it for a lot of work, but I often have problems picking back up when I haven't used it in a while, and setting paths, installing Python correctly etc. I created a Docker image for working with Jep that has everything preset for you and a README for instructions on how to run Java classes. I thought I'd post it here in case anyone wants a lightweight image to experiment with.

It's running java1.8, Python3.8, and Jep==3.9.0

https://hub.docker.com/repository/docker/bepstein/jep-python

**Comment by L-JiaHui** [comment]
hi，image not found 
Can I send it again？

**Comment by Ben-Epstein** [comment]
Hi @L-JiaHui I'm not sure what you mean exactly. I'm able to access the image, it seems to be public (I can see it in a private browser window). What was the error you got?

**Comment by L-JiaHui** [comment]
Thank you for your previous visits were 404, now it is OK.
Are you an image built with Dockerfile?

**Comment by kamjin1996** [comment]
Hello, can anyone provide the relevant dockerfile? I may need to do some additional customisation, thanks a lot!
