### ISSUE TITLE
Jep/Python is not being excuted in Java

### ISSUE THREAD

**Issue by Klodovskyy** [ninia/jep#298]
**Describe the bug**
This is not a bug for sure, my guess it's something related to the developement environement, the code is being build successfully and even shows if there is any Python syntax errors on exec, but when everything is correct it doesn't return any results.

**Expected behavior**
Printing any interp.eval() result in console, only .eval(" of some Java code") is working, but thats not the case with Python.

**Environment **
- Windows 10
- Python 3.7 & tried with Python 3.5
- JDK 1.8.x.x
- Jep Version: 3.9.1
- Python packages used (numpy, pandas)

**Code**
`public class AnotherTest {
    public static void main(String[] args){
        try (SharedInterpreter interp = new SharedInterpreter()) {
            Object [] data = new Object[] {5, 10, "this is a test"};
            interp.set("data",data);
            interp.eval("print('hello from Jep!')");
            interp.eval("print(type(data))");
            interp.eval("print(data[0],data[1],data[2])");
            interp.eval("import sys" );
            interp.eval("print(sys.version)");
        }
        catch (JepException e) {
            e.printStackTrace();
        }
    }
    
}`

BUILD SUCCESSFUL ! No Exceptions but no results also !

**Comment by Klodovskyy** [comment]
I forgot to mention that importing a Python library returns an error too, for example : 

interp.eval("import pandas" ); 

Console : 

jep.JepException: <class 'ModuleNotFoundError'>: No module named 'pandas'
	at <string>.<module>(<string>:1)
	at jep.Jep.eval(Native Method)
	at jep.Jep.eval(Jep.java:451)
	at jep_package.AnotherTest.main(AnotherTest.java:24)

**Comment by bsteffensmeier** [comment]
Python print will normally go to stdout. In some environments such as an IDE the java output is redirected somewhere else and it may not be obvious where stdout is even going. Jep can redirect python print statements to java System.out, you just need to use [JepConfig.setRedirectOutputStreams](http://ninia.github.io/jep/javadoc/3.9/jep/JepConfig.html#setRedirectOutputStreams-boolean-).

For resolving the import problems I recommend looking at sys.path in the jep interpreter and verifying that pandaas is in one of those locations.

**Comment by Klodovskyy** [comment]
Redirecting Jep's redirect_streams.setup() method did the job.
Much appreciated @bsteffensmeier  !

I'm still trying to figure out what's wrong with the libs import , matter of fact I was only able to import sys, the others like Numpy,TensorFlow,Pandas are not being recongnized .

**Comment by Klodovskyy** [comment]
it's all good now , had to add lib\site-packages to sys path . Thanks again for the hints
