### ISSUE TITLE
Problem calling Java constructors from Python after Jep installation in python environment.

### ISSUE THREAD

**Issue by johnson-ajar** [ninia/jep#302]
**Describe the problem**
Installed Jep in a python environment (python_examples) using anaconda using environment.yml. The installation Jep was successful after setting JAVA_HOME in $ENV_HOME/etc/conda/activate.d/env_vars.sh. As expected the Jep libraries and files were installed at the location ~/anaconda3/python_examples/lib/python3.8/site-packages/jep. After activating the python_examples environment, I opened a python-cli and try to call java constructors
e.g.
from java.util import HashMap 
from java.util import ArrayList as AL

I get the following error. 
ModuleNotFoundError: No module named 'java'.

Not sure what I am missing in my python environment. 
Need help to understand what causing the issue and how to fix it.

**Environment (please complete the following information):**
- OS Platform, Distribution, and Version: Fedora Linux, 
- Python Distribution and Version: 3.8.6
- Java Distribution and Version: openJDK 1.8.0
- Jep Version: 3.9.1
- Python packages used (e.g. numpy, pandas, tensorflow):

**Logs**
Please attach the complete console output of the build.
Python 3.8.6 | packaged by conda-forge | (default, Oct  7 2020, 19:08:05) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from java.util import HashMap
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'java'
**Additional context**

**Comment by bsteffensmeier** [comment]
Jep is a library to let you embed python in a java application. Currently if your main application is python then jep cannot be used. 

Jep comes with a script that will run java and use jep to run python scripts so you can run python without writing a java application. A python script that is run using the jep script can import java classes. This script is named `jep` and it is installed in the bin directory of your python installation. You can ruun it with no argumetns to start an interactive interpreter or provide the name of a python script to run.
