### ISSUE TITLE
Feature: `exec` precompiled code

### ISSUE THREAD

**Issue by mario45211** [ninia/jep#304]
**Is your feature request related to a problem? Please describe.**
Redundant `exec` calls with the same code impact general application's performance. That would be great to compile once - exec many times, storing that code in some cache.

**Describe the solution you'd like**
The `Jep` API should has `compile()` method, which underneath compile given code string and return compiled code's object (like `PyCode` instance in Jython), which can be used in consecutive `exec` invocation (refer to `pyembed_compile_string` in `pyembed.c` file, which retrieve such a compiled code instance)

**Describe alternatives you've considered**
```java
pythonInterpreter.set("string", codeToCompile);
pythonInterpreter.exec("code = compile(string,'<string>','exec')");
Object code = pythonInterpreter.getValue("code");
...
pythonInterpreter.set("code", code);
pythonInterpreter.exec("code"); //has not any effect
```
Manual compiling code (like above) does not returns a compiled code's object, but its string representation (which, I know, is valid with Jep nature). Passing retrieved `code` to `exec` method has not effect obviously.

Please, let me know, what you think about such feature.

Best regards!

**Comment by bsteffensmeier** [comment]
You should be able to achieve the desired result using the current API. One possibility would be to just leave the compiled code in a global variable in your interpreter, then you should be able to exec it multiple times without recompiling.

```java
pythonInterpreter.set("string", codeToCompile);
pythonInterpreter.exec("code = compile(string,'<string>','exec')");
...
pythonInterpreter.exec("exec(code)");
...
pythonInterpreter.exec("exec(code)");
```

If you want to store the code in java you can do that by specifying you need a PyObject when you call getValue.

```java
pythonInterpreter.set("string", codeToCompile);
pythonInterpreter.exec("code = compile(string,'<string>','exec')");
PyObject code = pythonInterpreter.getValue("code", PyObject.class);
...
pythonInterpreter.set("code", code);
pythonInterpreter.exec("exec(code)");
```

In general I think it would be better to put the code in a python function and then use jep to exec the function definition. Python will automatically compile the code within the function so you can call the function multiple times and it should be equivalent to precompiling the code. Another advantage of a function is that it can be used from java as a [PyCallable](http://ninia.github.io/jep/javadoc/3.9/jep/python/PyCallable.html) like this:

```java
     jep.exec("def hello(arg):\n" +
              "    return 'Hello ' +  str(arg)");
     PyCallable pyHello = jep.getValue("hello", PyCallable.class);
     String result = (String) pyHello.call("World");
```

**Comment by mario45211** [comment]
@bsteffensmeier Thanks for your answer. I tested your second proposition and indeed that approach was enough to meet my requirements.

Best regards!
