### ISSUE TITLE
SharedInterpreter constructor does not fulfill its contract

### ISSUE THREAD

**Issue by Robzzson** [ninia/jep#306]
**Describe the bug**
SharedInterpreter constructor does not fulfill its contract. It should throw JepException when jep is not in java.library.path, but it throws java.lang.UnsatisfiedLinkError instead. [here is the problem](https://github.com/ninia/jep/blob/master/src/main/java/jep/MainInterpreter.java#L104)

**To Reproduce**
- [jep](https://pypi.org/project/jep/) should not be installed
- create an instance of SharedInterpreter:
```java
Jep jep = new SharedInterpreter();
```

**Expected behavior**
Constructor throws JepException

**Environment (please complete the following information):**
Any

**Comment by ndjensen** [comment]
I disagree that this is an issue.  UnsatisfiedLinkError is more precise in telling you what went wrong than a JepException.  And an Error is appropriate since it indicates a bad state of things, not something an application can easily recover from (without outside intervention of installing jep).

**Comment by Robzzson** [comment]
Hello @ndjensen,

Although the UnsatisfiedLinkError is a subtype of Error, it does not feel nearly as serious as some of the other possible jvm errors. I think it'd be better if it was up to the developer to decide if they can recover or not. Currently one does an ordinary try-catch block expecting to catch JepException in case something goes wrong. In my opinion the error should be wrapped inside of JepException and include error's message and stacktrace - it won't loose any verbosity that way.

If you feel the proposed approach is wrong, then the occurring errors could be at least mentioned in the SharedInterpreter constructor javadoc.

Cheers!
