### ISSUE TITLE
Return real python list

### ISSUE THREAD

**Issue by jsnps** [ninia/jep#316]
Hey, 

maybe that is an easy one, but I currently don't see how to do it properly. I want to return a list from java but on the python side I want it to be a real list, because pyjlist is not implementing the whole list contract - e.g. append does not work. Is there any way to force this from the java side? For my use case it is not relevant to remember the java list reference, typical usage would be: 

values = java_obj.get_values()
values.append("foo")
java_object.set_values(values)

I already tried to use the list constructor from the java side, but of course going back through java will again convert it to a java list and then back to python wrap it as pyjlist:
```Java
	@Test
	public void testList() throws JepException {
		List<String> javaList = Lists.newArrayList();
		try (Jep jep = new SharedInterpreter()) {
			PyCallable list = jep.getValue("list", PyCallable.class);
			Object pyList = list.call(javaList);
			jep.set("pyList", pyList);
			assertTrue(jep.getValue("type(pyList) is list", Boolean.class));
		}
	}
```

My next idea would be to define my own PyList interface and do it in C somewhere here:
https://github.com/ninia/jep/blob/8a2746a2ff67d219d76733f05d526e4c65e9a177/src/main/c/Jep/convert_j2p.c#L196
Instead of wrapping the java object I would then like to invoke the list construrctor to achieve something like "list(javalist)". 

Of course if there is a way from the java side, I would like to avoid this. Any idea?

Thanks :)

**Comment by bsteffensmeier** [comment]
[IPyCallable.callAs](http://ninia.github.io/jep/javadoc/3.9/jep/python/PyCallable.html#callAs-java.lang.Class-java.lang.Object...-) can be used to prevent the conversion of a python list to a java List. which could help your example below.

```Java
	@Test
	public void testList() throws JepException {
		List<String> javaList = Lists.newArrayList();
		try (Jep jep = new SharedInterpreter()) {
			PyCallable list = jep.getValue("list", PyCallable.class);
			Object pyList = list.callAs(PyObject.class, javaList);
			jep.set("pyList", pyList);
			assertTrue(jep.getValue("type(pyList) is list", Boolean.class));
		}
	}
```

Another option would be to create your own list type in Java and add the methods you need so they are callable from python.

**Comment by jsnps** [comment]
Excellent! Thanks for the super fast answer, I knew there must be some easy solution already :)
