### ISSUE TITLE
JEP parallelism Test opening so many Files

### ISSUE THREAD

**Issue by Bishnup1995** [ninia/jep#320]
Hi All,

I found that the Jep is opening so many files when trying to run parallel Jep. I was running 3 instances of long-running `JEP` instances and `lsof` for that process is showing me count as 7241.  Is it acceptable behavior?

**Comment by bsteffensmeier** [comment]
Jep does not typically open 7241 files. What makes you think that these files are opened by jep and not another java or python library you are using?
