### ISSUE TITLE
importerror: dlopen: cannot load any more object with static tls

### ISSUE THREAD

**Issue by Mrliuzh** [ninia/jep#321]
got this error:importerror: dlopen: cannot load any more object with static tls,when i run java app on linux with jep 3.8.2

**Comment by Mrliuzh** [comment]
![image](https://user-images.githubusercontent.com/28565906/114849182-1989e700-9e12-11eb-88a2-d5b2949c1fbe.png)

**Comment by bsteffensmeier** [comment]
Since your error occurs in a regular python import I do not believe it is directly related ito anything in jep. Are you able to import all your needed python libraries from a regular python interpreter?

**Comment by Mrliuzh** [comment]
it run successfully when i  cut this python code from java file,all library needed is imported ,maybe memory issue?

**Comment by Mrliuzh** [comment]
it run successfully when i  cut this python code from java file,all library needed is imported ,maybe memory issue?

**Comment by Mrliuzh** [comment]
i get the solution from  the code,so when i fix this issue  i will  put here
