### ISSUE TITLE
is jep works with jdk 1.6.0.45?

### ISSUE THREAD

**Issue by Mrliuzh** [ninia/jep#326]
**Describe the problem**
is jep works with jdk 1.6.0.45?

**Environment (please complete the following information):**
- OS Platform, Distribution, and Version: windows/linux
- Python Distribution and Version: 3.6.5
- Java Distribution and Version: jdk 1.6.0.45
- Jep Version: 3.8.2
- Python packages used (e.g. numpy, pandas, tensorflow):

**Additional context**
is jep works with jdk 1.6.0.45? which version?

**Comment by ndjensen** [comment]
It's on the README in the dependencies section.  Jep 3.9 requires Java 1.7.  If you want to use Java 1.6, you will need to use Jep 3.6 or earlier.
