### ISSUE TITLE
Using Tensorflow on Red Hat 7 with jep

### ISSUE THREAD

**Issue by ikonARdeveloper** [ninia/jep#329]
**Describe the bug**
If I import TensorFlow into a python script and then run using jep my application crashes when jep tries to import TensorFlow. This same process works on Windows and Red Hat 6. Other modules work fine, such as numpy and pandas.

If I run python code that doesn't import TensoFlow jep seems to work as normal, so I am not sure if this is jep or TensorFlow. I have tried running TensorFlow commands from the command line and that works, so that makes me think it is the jep side.

**To Reproduce**
We setup a jep SubInterpreter with a JepConfig of 
`JepConfig jepConfig = new JepConfig().addSharedModules("pandas", "numpy", "h5py", "scipy", "tensorflow").setRedirectOutputStreams(true);`

We then have some code allowing us to dynamically load in libraries and convert inputs and outputs and then run the python code.

I then see the issue if I have a Python script that just imports TensorFlow. For example I imported our module and ran the below dummy method which prints out "First Message" but then crashes:
```
def test():
    print("First Message")
    import tensorflow as tf
    print("Second Message")
    print(tf.reduce_sum(tf.random.normal([1000, 1000])))

    return 
```

**Expected behavior**
On a none Red Hat 7 OS TensorFlow loads and the method is run. TensorFlow should load in Red Hat 7 too.

**Environment (please complete the following information):**
- OS Platform, Distribution, and Version: RHEL 7
- Python Distribution and Version: miniconda, Python 3.8.8
- Java Distribution and Version: Zulu 1.8.0.282
- Jep Version: 3.9.1
- Python packages used (e.g. numpy, pandas, tensorflow): TensorFlow

**Additional context**
We build a python distribution that we package with our application, the Linux one is built on RHEL 6. I have tried rebuilding on RHEL7 and using that distribution but I get the same error. 

Here is are the errors shown in the terminal when the application crashes:

> *** Error in `/home/our_app/jre/bin/java': munmap_chunk(): invalid pointer: 0x00007fcc00ba2360 ***
> ======= Backtrace: =========
> /lib64/libc.so.6(+0x7f3e4)[0x7fcd0d3ac3e4]
> /usr/lib64/libLLVM-6.0-rhel.so(_ZNSt10_HashtableISsSsSaISsENSt8__detail9_IdentityESt8equal_toISsESt4hashISsENS1_18_Mod_range_hashingENS1_20_Default_ranged_hashENS1_20_Prime_rehash_policyENS1_17_Hashtable_traitsILb1ELb1ELb1EEEE21_M_insert_unique_nodeEmmPNS1_10_Hash_nodeISsLb1EEE+0xf8)[0x7fcc21e1d588]
> /home/our_app/python/lib/python3.8/site-packages/tensorflow/python/../libtensorflow_framework.so.2(_ZNSt10_HashtableISsSsSaISsENSt8__detail9_IdentityESt8equal_toISsESt4hashISsENS1_18_Mod_range_hashingENS1_20_Default_ranged_hashENS1_20_Prime_rehash_policyENS1_17_Hashtable_traitsILb1ELb1ELb1EEEE9_M_insertIRKSsNS1_10_AllocNodeISaINS1_10_Hash_nodeISsLb1EEEEEEEESt4pairINS1_14_Node_iteratorISsLb1ELb1EEEbEOT_RKT0_St17integral_constantIbLb1EE+0x99)[0x7fcb6d264e79]
> /home/our_app/python/lib/python3.8/site-packages/tensorflow/python/../libtensorflow_framework.so.2(_ZN10tensorflow22UnaryVariantOpRegistry16RegisterDecodeFnERKSsRKSt8functionIFbPNS_7VariantEEE+0x6c6)[0x7fcb6d47e0f6]
> /home/our_app/python/lib/python3.8/site-packages/tensorflow/python/../libtensorflow_framework.so.2(+0x6cdc7b)[0x7fcb6d1e2c7b]
> /lib64/ld-linux-x86-64.so.2(+0xf9b3)[0x7fcd0e0f29b3]
> /lib64/ld-linux-x86-64.so.2(+0x1458e)[0x7fcd0e0f758e]
> /lib64/ld-linux-x86-64.so.2(+0xf7c4)[0x7fcd0e0f27c4]
> /lib64/ld-linux-x86-64.so.2(+0x13b7b)[0x7fcd0e0f6b7b]
> /lib64/libdl.so.2(+0xfab)[0x7fcd0d6fbfab]
> /lib64/ld-linux-x86-64.so.2(+0xf7c4)[0x7fcd0e0f27c4]
> /lib64/libdl.so.2(+0x15ad)[0x7fcd0d6fc5ad]
> /lib64/libdl.so.2(dlopen+0x31)[0x7fcd0d6fc041]
> /home/our_app/python/lib/libpython3.8.so.1.0(_PyImport_FindSharedFuncptr+0x195)[0x7fcd0decdf25]
> /home/our_app/python/lib/libpython3.8.so.1.0(_PyImport_LoadDynamicModuleWithSpec+0x177)[0x7fcd0de810f7]
> /home/our_app/python/lib/libpython3.8.so.1.0(+0x153dc8)[0x7fcd0de85dc8]
> /home/our_app/python/lib/libpython3.8.so.1.0(+0x23ff2c)[0x7fcd0df71f2c]
> /home/our_app/python/lib/libpython3.8.so.1.0(PyVectorcall_Call+0x6f)[0x7fcd0ddf148f]
> /home/our_app/python/lib/libpython3.8.so.1.0(_PyEval_EvalFrameDefault+0x6e25)[0x7fcd0dda31e5]
> /home/our_app/python/lib/libpython3.8.so.1.0(_PyEval_EvalCodeWithName+0xbed)[0x7fcd0df9601d]
> /home/our_app/python/lib/libpython3.8.so.1.0(_PyFunction_Vectorcall+0x93)[0x7fcd0ddf38d3]
> /home/our_app/python/lib/libpython3.8.so.1.0(+0x736b7)[0x7fcd0dda56b7]
> /home/our_app/python/lib/libpython3.8.so.1.0(_PyEval_EvalFrameDefault+0x6b7f)[0x7fcd0dda2f3f]
> /home/our_app/python/lib/libpython3.8.so.1.0(+0x6a320)[0x7fcd0dd9c320]
> /home/our_app/python/lib/libpython3.8.so.1.0(+0x736b7)[0x7fcd0dda56b7]
> /home/our_app/python/lib/libpython3.8.so.1.0(_PyEval_EvalFrameDefault+0x3397)[0x7fcd0dd9f757]
> /home/our_app/python/lib/libpython3.8.so.1.0(+0x6a320)[0x7fcd0dd9c320]
> /home/our_app/python/lib/libpython3.8.so.1.0(+0x736b7)[0x7fcd0dda56b7]
> /home/our_app/python/lib/libpython3.8.so.1.0(_PyEval_EvalFrameDefault+0x3413)[0x7fcd0dd9f7d3]
> /home/our_app/python/lib/libpython3.8.so.1.0(+0x6a320)[0x7fcd0dd9c320]
> /home/our_app/python/lib/libpython3.8.so.1.0(+0x736b7)[0x7fcd0dda56b7]
> /home/our_app/python/lib/libpython3.8.so.1.0(_PyEval_EvalFrameDefault+0x3413)[0x7fcd0dd9f7d3]
> /home/our_app/python/lib/libpython3.8.so.1.0(+0x6a320)[0x7fcd0dd9c320]
> /home/our_app/python/lib/libpython3.8.so.1.0(+0x736b7)[0x7fcd0dda56b7]
> /home/our_app/python/lib/libpython3.8.so.1.0(_PyEval_EvalFrameDefault+0x3413)[0x7fcd0dd9f7d3]
> /home/our_app/python/lib/libpython3.8.so.1.0(+0x6a320)[0x7fcd0dd9c320]
> /home/our_app/python/lib/libpython3.8.so.1.0(+0xbd750)[0x7fcd0ddef750]
> /home/our_app/python/lib/libpython3.8.so.1.0(_PyObject_CallMethodIdObjArgs+0xfa)[0x7fcd0ddf1efa]
> /home/our_app/python/lib/libpython3.8.so.1.0(PyImport_ImportModuleLevelObject+0x482)[0x7fcd0de83252]
> /home/our_app/python/lib/libpython3.8.so.1.0(_PyEval_EvalFrameDefault+0x6654)[0x7fcd0dda2a14]
> /home/our_app/python/lib/libpython3.8.so.1.0(_PyEval_EvalCodeWithName+0xbed)[0x7fcd0df9601d]
> /home/our_app/python/lib/libpython3.8.so.1.0(PyEval_EvalCode+0x23)[0x7fcd0defef33]
> /home/our_app/python/lib/libpython3.8.so.1.0(+0x1cd1fd)[0x7fcd0deff1fd]
> /home/our_app/python/lib/libpython3.8.so.1.0(+0x23ff2c)[0x7fcd0df71f2c]
> /home/our_app/python/lib/libpython3.8.so.1.0(PyVectorcall_Call+0x6f)[0x7fcd0ddf148f]
> /home/our_app/python/lib/libpython3.8.so.1.0(_PyEval_EvalFrameDefault+0x6e25)[0x7fcd0dda31e5]
> /home/our_app/python/lib/libpython3.8.so.1.0(_PyEval_EvalCodeWithName+0xbed)[0x7fcd0df9601d]
> /home/our_app/python/lib/libpython3.8.so.1.0(_PyFunction_Vectorcall+0x93)[0x7fcd0ddf38d3]
> /home/our_app/python/lib/libpython3.8.so.1.0(+0x736b7)[0x7fcd0dda56b7]
> /home/our_app/python/lib/libpython3.8.so.1.0(_PyEval_EvalFrameDefault+0x6b7f)[0x7fcd0dda2f3f]
> /home/our_app/python/lib/libpython3.8.so.1.0(+0x6a320)[0x7fcd0dd9c320]
> /home/our_app/python/lib/libpython3.8.so.1.0(+0x736b7)[0x7fcd0dda56b7]
> /home/our_app/python/lib/libpython3.8.so.1.0(_PyEval_EvalFrameDefault+0x3397)[0x7fcd0dd9f757]
> /home/our_app/python/lib/libpython3.8.so.1.0(+0x6a320)[0x7fcd0dd9c320]
> /home/our_app/python/lib/libpython3.8.so.1.0(+0x736b7)[0x7fcd0dda56b7]
> /home/our_app/python/lib/libpython3.8.so.1.0(_PyEval_EvalFrameDefault+0x3413)[0x7fcd0dd9f7d3]
> /home/our_app/python/lib/libpython3.8.so.1.0(+0x6a320)[0x7fcd0dd9c320]
> /home/our_app/python/lib/libpython3.8.so.1.0(+0x736b7)[0x7fcd0dda56b7]
> /home/our_app/python/lib/libpython3.8.so.1.0(_PyEval_EvalFrameDefault+0x3413)[0x7fcd0dd9f7d3]

I also looked in /var/log/messages and have:

> abrt-hook-ccpp: Process 27083 (java) of user 1000 killed by SIGABRT - dumping core
> abrt-hook-ccpp: Failed to create core_backtrace: waitpid failed: No child processes
> abrt-server: Executable '/home/our_app/jre/bin/java' doesn't belong to any package and ProcessUnpackaged is set to 'no'
> abrt-server: 'post-create' on '/var/spool/abrt/ccpp-2021-05-24-07:43:22-27083' exited with 1
> abrt-server: Deleting problem directory '/var/spool/abrt/ccpp-2021-05-24-07:43:22-27083'

Thanks for any help!

**Comment by ikonARdeveloper** [comment]
So I have managed to get this working. I had been installing all my python modules using pip, I have now moved to conda. Having re-created my python distribution in this way I got past this issue. I did see some other issues, but I am confident none of it falls in Jep's remit.

**Comment by priyadarshi9** [comment]
Hey, I have been getting similar error while importing tensorflow. (On a mac) How did you get around this issue?
