### ISSUE TITLE
Override __repr__ of PyJObject

### ISSUE THREAD

**Issue by jsnps** [ninia/jep#330]
Hey guys, 

is it possible to override the __repr__ function of PyJObject (python wrappers around java objects)? 

In Jython there was a default __repr__ implementation, but an overriden toString method of PyObject subclasses was also taken as __repr__ override. We have quite some tests relying on these strings (e.g. a list of objects prints the repr string rather than the str string) - we admit that these tests should be reworked and not rely on the string representation of the objects. Another place, where these repr strings are appearing "unfamiliar" is our interactive console - it was easier to use / understand with the toString of our API objects. 
I experimented a bit and couldn't find a way to achieve this without going into the C code. Maybe I missed something?

I tried:
a) define a __repr__ function on the java objects, with the hope that this one could be picked up.
b) monkeypatch the function on the python object. I can "get" the __repr__ function, but when trying to assign something (eg. __str__) to it, python complains with "object has no attribute '__repr__'."

Is there any simple way to achieve this without modifying jep?

One idea (requiring jep modifications) would be to simply implement tp_repr - similar like tp_str, just checking for the existence of a repr method on the java object and use this one, if present. 
[PyJObect](https://github.com/ninia/jep/blob/master/src/main/c/Objects/pyjobject.c#L540)

Another idea (not thought through), implement the required functions for allowing to customize/extend PyJObject and provide a way to have control over what wrapper class should be instantiated. Maybe this ties into the custom converters idea, which was mentioned in another thread.

Thanks!

**Comment by bsteffensmeier** [comment]
I can't think of any way to do it without modifying jep. I tried defining a `__repr__` method on the java object but it isn't picked up, I think the java methods are currently instance attributes instead of class attributes which may be why it doesn't work.

I would be in favor of modifying jep so that there is either a special name or attribute on a java method that could be detected by a custom tp_repr on pyjpbject to allow overrides.

**Comment by ndjensen** [comment]
@bsteffensmeier, can we close this as included in Jep 4.0?
