### ISSUE TITLE
java 使用 JEP调用python算法 执行一次可以，第二次立马报错

### ISSUE THREAD

**Issue by L-JiaHui** [ninia/jep#331]
public static Object callPython(String fileName, String methodName, Object... params) {

        // TODO V-6
        final JepConfig jepConfig = new JepConfig();
        // 算法文件路径
        final String property = System.getProperty("user.dir");
        String path = property + "/zheneng-service-device/src/main/resources/python";
        log.info("path:{}", path);
        jepConfig.addIncludePaths(path);

        Object result = null;
        try (Interpreter interpreter = new SubInterpreter(jepConfig)) {
            // 导入算法
            interpreter.eval("from" + " " + fileName + " " + "import *");
            // 函数名  参数
            result = interpreter.invoke(methodName, params);
        } catch (UnsatisfiedLinkError | JepException e) {
            e.printStackTrace();
        } 
        log.info("result:{}", result);
        return result;
    }

## 第二次访问报错

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000000140c7c003, pid=1508, tid=0x0000000000009803
#
# JRE version: Java(TM) SE Runtime Environment (8.0_291-b10) (build 1.8.0_291-b10)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.291-b10 mixed mode bsd-amd64 compressed oops)
# Problematic frame:
# C  [_multiarray_umath.cpython-37m-darwin.so+0x12f003]  PyArray_Item_INCREF+0x33
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /Users/l-jiahui/Local/Zheneng/zhenenng/hs_err_pid1508.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

**Comment by L-JiaHui** [comment]
有大佬帮我看看嘛

**Comment by ndjensen** [comment]
Your crash is in numpy.  Try using `SharedInterpreter` instead of `SubInterpreter` or use shared modules such as `JepConfig.addSharedModules("numpy")`.

**Comment by L-JiaHui** [comment]
Thank you
