### ISSUE TITLE
docker

### ISSUE THREAD

**Issue by L-JiaHui** [ninia/jep#334]
Family, there are no Python and Java-based containers？
I want to build containers based on Python and Java environments.
I try to build it myself,But to perform(python setup.py build install) error
![bug](https://user-images.githubusercontent.com/63582034/124723693-e1400380-df3d-11eb-9368-cb61449347ea.jpg)

**Comment by bsteffensmeier** [comment]
See https://github.com/ninia/jep/issues/220#issuecomment-567925146

**Comment by L-JiaHui** [comment]
@bsteffensmeier think you
