### ISSUE TITLE
jep.JepException: <class 'ModuleNotFoundError'>: No module named 'numpy'

### ISSUE THREAD

**Issue by Marmot01** [ninia/jep#337]
I run JEP through eclipse on Linux. When I import a third-party library (such as numpy) of python, it will report "jep.JepException: <class 'ModuleNotFoundError'>: No module named 'numpy'" . But my Python has numpy installed

**Comment by ndjensen** [comment]
You possibly have more than one Python on your system and it's not picking up the one you want.  You can configure the Python interpreter it uses in Pydev if you're using Pydev.

**Comment by ndjensen** [comment]
Based on #340, closing this as resolved.  Solution there was to use environment variable LD_LIBRARY_PATH on Linux to point to the directory containing the libpython.so that should be used.
