### ISSUE TITLE
 jep.JepException: <class 'UnicodeDecodeError'>: utf-8 when passing a text including emoji to python:

### ISSUE THREAD

**Issue by hejhejjasonji** [ninia/jep#345]
I create a instance of sharedInterpreter() to pass a string including some emojis such as 🛒 by the mothod of ".set", then when I exec to try to get values from python, it throw the following exception:

Exception in thread "main" jep.JepException: <class 'UnicodeDecodeError'>: utf-8
	at jep.Jep.set(Native Method)
	at jep.Jep.set(Jep.java:625)
	at jep.Jep.set(Jep.java:582)
	at sentiment_jep.predict.show(predict.java:41)
	at sentiment_jep.predict.main(predict.java:56)
it works fine on my python client and also can print it in java console.  It occurs when I am trying to let jep pass this emoji to python. 
Kindly ask do I miss something for the config?

thanks a lot！

- OS Platform, Distribution, and Version: windows 10
- Python Distribution and Version: 3.6
- Java Distribution and Version: 1.8
- Jep Version: 3.9.0/3.9.1(tried both)

**Comment by hejhejjasonji** [comment]
java: 
public class predict {
       private  Interpreter interp = new SharedInterpreter();
       public String show(String raw_text) throws JepException, JsonProcessingException {
                interp.eval("from sentiment.predict import grpc_predict");
                interp.set("arg", raw_text);
                interp.exec("x =grpc_predict.show(str(arg))");
                String result = (String) interp.getValue("x");
                return result;
    }
}
  public static void main(String[] args) throws JepException, JsonProcessingException {
        predict qingqing=new predict();
        String a = "\uD83C\uDF81";
        System.out.print(qingqing.show(a))
}

python:
def show(text):
      return test

**Comment by hejhejjasonji** [comment]
hi @bsteffensmeier ,thank you so much for checking this out. It is good to know  it supposed to be good to run. I do not why but it works after changing the method of".exec" to ".invoke" to get values. 
I will then check the locale as you said later. Hope to figure out why it works by using "invoke" not "exec".
worked code:
```
public class predict {
       private  Interpreter interp = new SharedInterpreter();
       public String show(String raw_text) throws JepException, JsonProcessingException {
                interp.eval("from sentiment.predict import grpc_predict");
                **String result = (String) interp.invoke("grpc_predict.show",raw_text);**
                return result;
    }
}
  public static void main(String[] args) throws JepException, JsonProcessingException {
        predict qingqing=new predict();
        String a = "\uD83C\uDF81";
        System.out.print(qingqing.show(a))
}
```

**Comment by bsteffensmeier** [comment]
I am closing this as inactive because I cannot reproduce the problem so cannot do anything to solve it.
