### ISSUE TITLE
SyntaxError: no viable alternative at input ...

### ISSUE THREAD

**Issue by mike-hunhoff** [ninia/jep#346]
When using ` Jep.runScript` to execute a Python script containing

```python
example = "!"
print(f"hello{example}\nworld")
```

I receive the error

```python
SyntaxError: no viable alternative at input '"hello{example}\nworld"'
```

I'm unsure where the issue lies as the script file doesn't appear to be read before invoking cypthon `PyRun_File` at https://github.com/ninia/jep/blob/8a2746a2ff67d219d76733f05d526e4c65e9a177/src/main/c/Jep/pyembed.c#L1617

I'm interested to hear your thoughts on where the issue might be. tia

Jep: `4.0`
Java: `openjdk 11.0.12`
Python: `3.9.6`
OS: `Ubuntu 20.04.2 LTS`

**Comment by bsteffensmeier** [comment]
It works fine for me:

Code:
```java
class Test {

    public static void main(String[] args) throws JepException {
        try (SharedInterpreter interpreter = new SharedInterpreter()) {
            interpreter.runScript("test.py");
        }
    }
}
```

```python
example = "!"
print(f"hello{example}\nworld")
```

Output:
```
hello!
world
```

**Comment by mike-hunhoff** [comment]
Thank you for checking - I believe this was user error.
