### ISSUE TITLE
python file in jar load error,error message is <class 'ModuleNotFoundError'>

### ISSUE THREAD

**Issue by 1024lzx** [ninia/jep#348]
env desciption:
java 1.8
python 3.9
jep 3.9.1

java code：
        String pathPrefix = MagiService.class.getResource("").getPath();
        String scriptPath = "script";
        String pythonFilePath = pathPrefix.concat(scriptPath);
        System.out.println("path:" + pythonFilePath);
        JepConfig config = new JepConfig();
        config.addIncludePaths(pythonFilePath);
        try (Interpreter interp = new SubInterpreter(config)) {
            interp.eval("from magi.services import *");
            interp.eval("api = MagiServices().lzx_test");
            long beginTime = System.currentTimeMillis();
            Object result = interp.getValue("api");
            System.out.println("time spend:" + (System.currentTimeMillis() - beginTime));
            if (result != null) {
                System.out.println(result);
            }
            System.out.println("done");
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }

i can run success in local  idea terminal,but when i package it to a jar file, through "java -jar xxx".it will fail with error.error message is 
path:file:/Users/liangzhenxing/lzx/source/prophet-fbi-as/prophet-fbi-as-service/target/prophet-fbi-as-service.jar!/BOOT-INF/classes!/com/sankuai/rc/prophet/fbi/as/magi/script
<class 'ModuleNotFoundError'>: No module named 'magi'

i confirm the path is right,
the difference is 
local idea terminal print python path is 
path:/Users/liangzhenxing/lzx/source/prophet-fbi-as/prophet-fbi-as-service/target/classes/com/sankuai/rc/prophet/fbi/as/magi/script
in jar run mode,it became 
path:file:/Users/liangzhenxing/lzx/source/prophet-fbi-as/prophet-fbi-as-service/target/prophet-fbi-as-service.jar!/BOOT-INF/classes!/com/sankuai/rc/prophet/fbi/as/magi/script

please technical experts answer my question,thanks

**Comment by 1024lzx** [comment]
Additional information
the variable "pythonFilePath" is use for store custom python file

**Comment by bsteffensmeier** [comment]
The includePath for you interpreter must contain directories on the file system. The path you are providing is referencing a directory in a jar file which is not a path that is currently supported. I recommend you extract your python files to a temporary location on the filesystem and add that location as an include path instead.

**Comment by 1024lzx** [comment]
> The includePath for you interpreter must contain directories on the file system. The path you are providing is referencing a directory in a jar file which is not a path that is currently supported. I recommend you extract your python files to a temporary location on the filesystem and add that location as an include path instead.

thanks a lot
