### ISSUE TITLE
Tests freeze in python 3.9.9

### ISSUE THREAD

**Issue by bsteffensmeier** [ninia/jep#359]
When I try to build jep against python 3.9.9 the test hang and never complete. I have traced it to calling [sys.exit(0) in a test](https://github.com/ninia/jep/blob/master/src/test/python/subprocess/iter_itr_crash.py#L12). We may be able to work around this by removing that call from the test but I have also noticed sys.exit() will freeze an interactive interpreter, which might be a problem.

We have [some code for handling the exit but it just calls PyErr_PrintEx() to handle the exit](https://github.com/ninia/jep/blob/master/src/main/c/Jep/jep_exceptions.c#L61). I traced through PyErr_PrintEx() and found that the freeze occurs in t[hreading._shutdown()](https://github.com/python/cpython/blob/v3.9.9/Lib/threading.py#L1470). That function was recently changed in a [python bug](https://bugs.python.org/issue1596321) and I believe that change is what is causing the problem.

The problem does not exist in earlier versions of python 3.9. It does not exist in python 3.10.0 but the change was merged into the 3.10 branch so it will likely affect 3.10 whenever the next python version is released.

**Comment by bsteffensmeier** [comment]
In #361 I have changed the behavior so that we will call exit() ourselves in native code rather than relying on python to exit. 

In the future I think we need to stop handling SystemExit specially and allow it to be wrapped as a JepException and handled in java. For Run.java we would like to catch that exception and exit from java but that will require a new mechanism for getting the exit code from a SystemExit wrapped in a JepException so there is more work to do.

**Comment by ndjensen** [comment]
This is fixed in Jep 4.0.1.
