### ISSUE TITLE
Limit Python CPU time and memory limits [Security]

### ISSUE THREAD

**Issue by cyraid** [ninia/jep#364]
**Is your feature request related to a problem? Please describe.**
A long running exec, or huge heap allocation.

**Describe the solution you'd like**
It would be nice to have limitations imposed on execution like max CPU time, heap limit (for Python, not for Java/process).

**Describe alternatives you've considered**
GraalVM Python has sandbox limitations in the enterprise version.

**Additional context**

**Comment by bsteffensmeier** [comment]
Our goal is to allow interoperability between cpython and java within the same process. Since cpython does not provide any API for limiting the memory or CPU time used by python I do not think this is something that can be implemented within the scope of this project.
