### ISSUE TITLE
Reset the jep library path after MainInterpreter is initialized

### ISSUE THREAD

**Issue by neil-benn** [ninia/jep#365]
Hello,

  I've got the following use case:

- The system starts up and MainInterpreter.setJepLibraryPath(jepPath) is called to set a jep library
- A small python script is executed to check everything is working OK
- The user then goes to our software and tries to change that library path so we can reload the jep library
- We then called MainInterpreter.setJepLibraryPath(jepPath); again with the new path
- This then throws an IllegalStateException

  The reason for this is that static instance variable in the MainInterpreter has been initialised and therefore the instance variable is set.  Is there a way I can say to the system to clear everything out and restart?

Cheers,

Neil

**Comment by bsteffensmeier** [comment]
I do not think it will be possible to unload or reload the jep library. Java and JNI provides no explicit mechanism for unloading native libraries. I have read some reports that you can unload libraries if you stop using the ClassLoader responsible for loading the JNI classes. I have done some limited tests in the past and never found a way to make that work. It may be dependent on the specific JVM. Even if that works I anticipate there would be additional complications trying to reload the python libraries and the native libraries used by some python modules that would make this impossible.

**Comment by neil-benn** [comment]
Hello,

  Thanks, i thought that maybe the case.  I'll just get the user to restart
the app if they change that setting.

Cheers

Neil
