### ISSUE TITLE
Hook for importing python packages to accept/deny.

### ISSUE THREAD

**Issue by cyraid** [ninia/jep#369]
**Describe the solution you'd like**
Like the ClassEnquirer on the java side, it'd be nice to be able to accept packages on a import-by-import basis.

**Describe alternatives you've considered**
GraalVM has sandboxing options.

----

For example:

import io

This would call the Enquirer and allow/disallow the import.

**Comment by bsteffensmeier** [comment]
Jep is just using the standard cpython import mechanisms for importing any python modules. I do not consider any changes to the import process to be within the scope of jep so I have no plans to work this.
