### ISSUE TITLE
Get "The main Python interpreter previously failed to initialize." error

### ISSUE THREAD

**Issue by sunyu90325** [ninia/jep#370]
Hi there,

I get JEP run on a sample JAVA application. It works perfectly. However, when I try to use Jep in my real application. It throws an error when I initialize the interpreter. The error message is "The main Python interpreter previously failed to initialize.". 
I saw the error in the Jep source(MainInterpreter getMainInterpreter()), but I'm still not sure what is the cause of it. Could you 
The only configuration difference between the sample application and the real application is: 

In the sample application, I put "-Djava.library.path=C:\Python39\Lib\site-packages\jep" in the VM argument of the run configuration.
In the real application, I put it in the .bat file which is used to start the application.
..\jre\bin\javaw -Xmx512m  -Xdebug -Djava.library.path=C:\Python39\Lib\site-packages\jep 
-Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=1044 -jar ..\lib\run_client.jar

Could you help to see what I can try to fix this error? I really appreciate your help!

**Comment by bsteffensmeier** [comment]
This error is typically caused by some problem loading the jep library or the necessary python libraries. If you could provide the whole stack trace of all the errors occuring in your application it would give us a better understanding of what is happening. In general the first thing to check would be to make sure libjep.dll is installed at C:\Python39\Lib\site-packages\jep\.

**Comment by sunyu90325** [comment]
Thanks for your reply. There is no stack trace. The only information I find is "java.lang.UnsatisfiedLinkError: jep (Not found in java.library.path)". Hmm, It looks like the java library path is not set correctly. But I already add it to the bat file... 
And jep.dll(windows version) is in that directory.

**Comment by bsteffensmeier** [comment]
If jep.dll is in the correct location then the next thing to check would be to make sure the python dll is able to be loaded. I am not very familiar with how windows loads libraries but you may need to find the python dll(maybe in C:\Python39\Lib\) and add the directory that contains it to PATH. Alternatively you could try setting PYTHON_HOME to "C:\Python39" in which case jep will try to find libpython.

**Comment by sunyu90325** [comment]
Thank you for your help. I figured it out. I should set PYTHONHOME to "C:\Python39"(not PYTHON_HOME). And I need to put jep.dll under Python39/DLLs folder.
