### ISSUE TITLE
Exception while trying to invoke a python function which returns a bytestring-jep.JepException: <class 'BufferError'>: Object is not writable.

### ISSUE THREAD

**Issue by XhinoMullaymeri** [ninia/jep#373]
**Problem**
I am trying to invoke a python function which returns a bytestring and I keep getting an exception.
Same code did run without any issues using Jep 3.9.1.

Sample code/over simplified :
**Python**
  ```
    def get_binary(arg_1, arg_2):
          return b'binary'
```
**Java**
```
import jep.Interpreter;
Interpreter interpreter;
byte[] myBinary;
myBinary = (byte[]) interpreter.invoke("get_binary", ["a1","a2"]);

```
**Exception**
```
    jep.JepException: <class 'BufferError'>: Object is not writable.
        at jep.Jep.invoke(Native Method)
        at jep.Jep.invoke(Jep.java:257)
```

**Environment (please complete the following information):**
- Oracle Linux Server 7.3"
- Python 3.6.13
- java (TM) version 1.8.0_261
- Jep Version: 4.0.1
- Python packages:
numpy                     1.19.5 
pandas                    1.1.5
scipy                     1.5.4

**Comment by bsteffensmeier** [comment]
Thanks for reporting this issue and providing an easily repeatable test case, I agree it is a significant regression. I have posted a pull request that I believe fixes your issue. If you can, consider testing the change in the PR against your specific use case and verify it fixes your problem.

**Comment by XhinoMullaymeri** [comment]
Hello Ben, 
I can confirm that the change in the PR solved my case. Thanks for the fast response!
