### ISSUE TITLE
Does Jep share memory with allocated JVM memory?

### ISSUE THREAD

**Issue by Mythical-Forest-Collective** [ninia/jep#376]
Heya, I'm using Jep in my project on a machine with a limited amount of RAM (all of which is dedicated to the program), does Jep make Python share the memory with the JVM?

**Comment by bsteffensmeier** [comment]
Jep will load python libraries into the same process as the JVM but outside of the JVM heap. The amount of memory used depends on what python commands you execute, what python libraries you use, and how many python objects are created. Direct NIO Buffers can be passed from java to python and can be used to share Java Memory with python but most objects created in python will be using memory outside the JVM.

**Comment by Mythical-Forest-Collective** [comment]
Ah okay then, thanks aha
