### ISSUE TITLE
Mac M1 -  have 'arm64', need 'x86_64'

### ISSUE THREAD

**Issue by ton3r** [ninia/jep#389]
I've installed JEP on my Mac Pro M1, but during the use of it I got the Exception

`java.lang.UnsatisfiedLinkError: /opt/homebrew/lib/python3.9/site-packages/jep/jep.cpython-39-darwin.so: dlopen(/opt/homebrew/lib/python3.9/site-packages/jep/jep.cpython-39-darwin.so, 0x0001): tried: '/opt/homebrew/lib/python3.9/site-packages/jep/jep.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/usr/lib/jep.cpython-39-darwin.so' (no such file)`

**Environment (please complete the following information):**
- MacOS Monterey 12.2.1
- python3.9
- Java 8
- Jep Version:
`rw-r--r--  1 batman  admin  162084 20 Apr 08:21 jep-4.0.3.jar`
`rwxr-xr-x  1 batman  admin  272757 20 Apr 08:21 jep.cpython-39-darwin.so`

`mbp-m1 ~ % pip install --upgrade jep
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Requirement already satisfied: jep in /opt/homebrew/lib/python3.9/site-packages (4.0.0)
Collecting jep
  Downloading jep-4.0.3.tar.gz (3.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 16.0 MB/s eta 0:00:00
`

Is there a way or a build to use it with Apple Silicon M1?

Thanks for help,

Tom

**Comment by bsteffensmeier** [comment]
Make sure that your Java installation and Python installation are using a compatible architecture. Based of this error you are using an arm64 version of Python with an x86_64 version of Java. Jep will work with either architecture. Jep is built by Python and loaded by Java so if they are not the same architecture it will not work.

**Comment by plapa** [comment]
You can also check more details on this issue I opened #379

**Comment by ton3r** [comment]
Yes! azul in arm version solves my probs! Thanks!
