### ISSUE TITLE
FAQ Update Request - Allowing Arbitrary Code Execution

### ISSUE THREAD

**Issue by bahrigencsoy** [ninia/jep#390]
We are evaluating JEP to embed in an enterprise application, that would allow **USER** to write arbitrary python functions. I have checked around the documentation, but could not find anything if this is one of the expected usages of the library.

I would love FAQ to state the target audience of the library. For example is it intended to be used within the same team where both python and Java code is tested before production, or is it safe enough to execute any (untested) python code w/o taking down the Java process.

**Comment by bsteffensmeier** [comment]
Jep does not provide any sand-boxing of the executed Python so the user will have the full power of Python including the ability to read/write files and start new processes. In general executing Python code from jep is as safe as running the code from the eval() function in Python. There are numerous articles and discussions online about how safe eval() is, I find this [stackoverflow post](https://stackoverflow.com/questions/661084/security-of-pythons-eval-on-untrusted-strings) provides a concise explanation and it contains many links for more information.

If you are not concerned with potentially malicious actors then I do not think you need to strictly have the Python and Java developed at the same time on the same team. I have worked on a large program which allowed users to modify and run Python scripts independently from the main application developers and while it is theoretically possible to cause crashes from Python it is not a frequent occurrence or a major source of problems.

Let me know if you find this information helpful and I can put it up on the FAQ as well.

**Comment by bahrigencsoy** [comment]
We have to assume that user accounts can be compromised and have malicious intent. For example [this](https://codegolf.stackexchange.com/a/22383) kills the Java process, among with possible others in the same page.

So, yes, I think this would be a valuable FAQ entry.

**Comment by Techcable** [comment]
Just FYI the java security manager is [deprecated for removal in Java 17](https://openjdk.java.net/jeps/411). Any java-level controls would be difficult (even with jython).

CPython doesn't really support sandboxing even if Jep did.

Unfortunately, Lua and Javascript VMs seem to be the only language implementations with good sandboxes.

You may want to consider isolation at the process level ([bubblewrap](https://github.com/containers/bubblewrap) is pretty great). This would require spinning up multiple JVMs....

**Comment by bsteffensmeier** [comment]
I've added my comments to the [FAQ on the wiki ](https://github.com/ninia/jep/wiki/FAQ)so I am closing this.
