### ISSUE TITLE
NullPointerException in ClassList.loadClassList when context class loader is unavailable in current thread.

### ISSUE THREAD

**Issue by Htarlov** [ninia/jep#401]
**Describe the bug**
If we try to use Jep from a thread that has context class loader null (e.g. thread created from the outside of Java runtime) it fails with java.lang.NullPointerException at line  282 in ClassList in method loadClassList.

**To Reproduce**
Not yet have code to reproduce. A possible way similar to what we try to do:
- install Ant Media Server community
- git clone sample plugins https://github.com/ant-media/Plugins/ 
- open SamplePlugin with Eclipse JEE with Maven
- add Jep as dependency and try to instantiate it from f.ex. packet listener https://github.com/ant-media/Plugins/blob/master/SamplePlugin/src/main/java/io/antmedia/app/SamplePacketListener.java in onAudioPacket in a standard default way

**Expected behavior**
Instance of the class should be created without exception.

**Environment (please complete the following information):**
- OS Ubuntu 18.04
- Python 3.8
- OpenJDK Runtime Environment (build 11.0.15+10-Ubuntu-0ubuntu0.18.04.1)
- Jep Version: 4.0.3,  3.8.2
- Python packages: numpy

**Additional context**
When Thread.currentThread().getContextClassLoader() returns null then that null is added to the list of class loaders and then code tries to call in = cl.getResourceAsStream(rsc); and fails. A null check is needed before adding a class loader to the list.

**Comment by ndjensen** [comment]
Fixed in Jep 4.1.0.
