### ISSUE TITLE
How can I activate a different conda environment at runtime?

### ISSUE THREAD

**Issue by fguillotpro** [ninia/jep#408]
Hello!
I am using a "hardcoded" conda environment set using MainInterpreter.setJepLibraryPath(), it is working fine (still need to set LD_PRELOAD manually for numpy to work but I see that it is being resolved).
I use SharedInterpreter:
```java
public void init() {
	MainInterpreter.setJepLibraryPath("/opt/conda/envs/<conda_env_name>/lib/python3.8/site-packages/jep/libjep.so");
}

public Object executeService() throws JepException {
	try (Interpreter interp = new SharedInterpreter()) {
	   // do stuff like interp.exec(code) and interp.invoke(function, params)
	}
}
```

Now I would like to be able to dynamically specify a different environment at runtime (equivalent of "source activate some_env") to be used by the executeService method. Instead of relying on my init(), maybe I could use a pool of interpreters initialized with the different environments.
With my current understanding of JEP, I am not sure if it can be done within the same JVM. If yes, how do I proceed? Thanks.

**Environment:**
- OS Platform, Distribution, and Version: adoptopenjdk/openjdk8 docker image
- Python Distribution and Version: conda python=3.8.10
- Java Distribution and Version: openjdk8 latest
- Jep Version: 4.0.3
- Python packages used (e.g. numpy, pandas, tensorflow): numpy pytorch etc.

**Comment by bsteffensmeier** [comment]
> With my current understanding of JEP, I am not sure if it can be done within the same JVM.

That is correct, once jep is loaded it will continue to use the same Python environment until the JVM terminates and there is no way to change that.

**Comment by fguillotpro** [comment]
> > With my current understanding of JEP, I am not sure if it can be done within the same JVM.
> 
> That is correct, once jep is loaded it will continue to use the same Python environment until the JVM terminates and there is no way to change that.

Ok thanks.
