### ISSUE TITLE
How do I install JEP in eclipse and get it working so I can use MetPy and python awips 

### ISSUE THREAD

**Issue by Linuxuser1234** [ninia/jep#409]

**Comment by bsteffensmeier** [comment]
From the [README](https://github.com/ninia/jep#installation): Simply run `pip install jep` to install jep. The install will place a jep jar in the jep directory of your site-packages and this can be imported into eclipse. The jep jar is also available through [maven](https://mvnrepository.com/artifact/black.ninia/jep/4.0.3). We do not offer support here for MetPy or python awips.
