### ISSUE TITLE
warning: mpd_setminalloc: ignoring request to set MPD_MINALLOC a second time

### ISSUE THREAD

**Issue by Mickey0811** [ninia/jep#419]
I have created 10 Java threads, and I hope to create one SubInterpreter  for each thread ,but the following error still occurred.,please help children

/AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/python3/python3-110/Python/Modules/_decimal/libmpdec/context.c:55: warning: mpd_setminalloc: ignoring request to set MPD_MINALLOC a second time

**Comment by Mickey0811** [comment]
I want to create multiple threads, and each thread creates a sharedinterpreter, and then use these threads to execute the same method of Python at the same time, but I feel that the efficiency is not good, and the actual effect is the same as the serial execution of these sharedinterpreters. How is this going on? Is there any way to make multiple threads process the same Python method at the same time

**Comment by bsteffensmeier** [comment]
You may be running into the Global Interpreter Lock(GIL). More information about [Jep and the GIL is on the wiki](https://github.com/ninia/jep/wiki/Jep-and-the-GIL).

**Comment by Mickey0811** [comment]
Can I use multiple processes to process the same function to make full use of the multi-core resources of the computer
However, when I create a multi process to call the specified function in the python file and execute the python method through JEP, the following error will be reported

‘’‘
UserWarning: resource_tracker: process died unexpectedly, relaunching.  Some resources might leak.
  warnings.warn('resource_tracker: process died unexpectedly, '
Unrecognized option: -c
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
’‘’

What is the reason for this
