### ISSUE TITLE
Access my own Java classes from Graal JS

### ISSUE THREAD

**Issue by Daniel-Alievsky** [ninia/jep#424]
I have very simple test:

```
package net.algart.bridges.graalvm.tests;
import org.graalvm.polyglot.Context;
public class GraalVMFullAccessToJava {
    public void test() {
        System.out.println("test");
    }

    public static void testStatic() {
        System.out.println("testStatic");
    }

    public static void main(String[] args) {
        Context context = Context.newBuilder("js")
                .allowAllAccess(true)
                .build();

        context.eval("js","java.lang.System.out.println('Hello')");
        context.getBindings("js").putMember("test", new GraalVMFullAccessToJava());
        context.eval("js","test.test()");
        context.eval("js","Java.type('net.algart.bridges.graalvm.tests.GraalVMFullAccessToJava').testStatic()");
        context.eval("js","net.algart.bridges.graalvm.tests.GraalVMFullAccessToJava.testStatic()");
    }
}

```

GraalVM after allowAllAccess, really, allows to access to any standard Java classes and also to an instance of my class, added to bindings. Also it works via Java.type(). But the last line does not work! Results:

Hello
test
testStatic
Exception in thread "main" ReferenceError: net is not defined
	at <js> :program(Unnamed:1:0-2)
	at org.graalvm.polyglot.Context.eval(Context.java:425)
	at net.algart.bridges.graalvm.tests.GraalVMFullAccessToJava.main(GraalVMFullAccessToJava.java:47)

What is the reason? What is the difference between standard "java.lang.System" class and my own class?

**Comment by ndjensen** [comment]
It appears you opened this ticket in the wrong project.

**Comment by Daniel-Alievsky** [comment]
You are absolutely right, sorry... It is another project, Graal.
Could you remove this wrong issue, please?
