### ISSUE TITLE
java.lang.NoSuchMethodError: jep.Jep.set(Ljava/lang/String;Ljava/lang/String;)V

### ISSUE THREAD

**Issue by wanran-cell** [ninia/jep#427]
**Describe the problem**
The code failed to run at this line
jep.set("trainedFolder", Normalizer.NEURALDATA_PREFIX + "\\" + folderName + "\\train\\ckpt");
String base = Normalizer.NEURALDATA_PREFIX.replace("\\", "\\\\");
Error:java.lang.NoSuchMethodError: jep.Jep.set(Ljava/lang/String;Ljava/lang/String;)V

**Environment (please complete the following information):**
- OS Platform, Distribution, and Version:win10
- Python Distribution and Version:3.7
- Java Distribution and Version:1.8
- Jep Version:4.0.3
- Python packages used (e.g. numpy, pandas, tensorflow):tensorflow1.14.0

**Comment by bsteffensmeier** [comment]
It looks like you are trying to run java code compiled with jep 3.9 using jep 4.0 at runtime. As indicated in [the release notes for Jep 4.0](https://github.com/ninia/jep/blob/master/release_notes/4.0-notes.rst#jep-40-release-notes) there are changes that make it incompatible with previous versions of jep so this will not work.

In this case the JVM is looking for [a set method that is defined in Jep 3.9](http://ninia.github.io/jep/javadoc/3.9/jep/Jep.html#set-java.lang.String-java.lang.String-) but [not present in Jep 4.0](http://ninia.github.io/jep/javadoc/4.0/jep/Jep.html). If you recompile your java code [the remaining set method](http://ninia.github.io/jep/javadoc/4.0/jep/Jep.html#set-java.lang.String-java.lang.Object-) should work with your existing code.

**Comment by wanran-cell** [comment]
Yes, when I used Jep 4.03 and recompiled the java code, it worked well. Thank you very much!
