### ISSUE TITLE
Possibility of loading specific python version

### ISSUE THREAD

**Issue by carlosuc3m** [ninia/jep#431]
**Describe the problem**
Hello, I am trying to use JEP with different Python distributions. For that I configure the PyConfig  object with different Python distributions. In Windows it works perfectly. However for Linux i am finding it a little bit complicated.

My Python distributions are stored in the folder /usr/lib. There I have /usr/lib/python3.9, /usr/lib/python3.8 and /usr/lib/python3.10.
Due to the files that JEP searches I need to provide the directory "/usr" so Jep can work. This issue does not allow me to select the wanted Python version. 
Is there any way to fix this issue?

**Environment (please complete the following information):**
- Ubuntu 22
- All Python distributions possible
- All possible Java distributions
- Jep Version: 4.0.3

regards,
Carlos

**Comment by bsteffensmeier** [comment]
You may be able to load a specific version by using [MainInterpreter.setJepLibraryPath()](http://ninia.github.io/jep/javadoc/4.0/jep/MainInterpreter.html#setJepLibraryPath-java.lang.String-) to ensure the jep library is loaded from the specific python install that you want to use.

**Comment by carlosuc3m** [comment]
Great I ve tried it and it works
