### ISSUE TITLE
Can I dynamically switch python version by "setJepLibraryPath"

### ISSUE THREAD

**Issue by WangRey** [ninia/jep#441]
**Describe the problem**
I need to dynamically change the version of the interpreter created in the project, depending on the parameters passed in. Is it possible to do that? I tried it. The problem arises. "Jep.setLibraryPath called after initializing python interpreter"
**Environment (please complete the following information):**
- OS Platform, Distribution, and Version:Linux
- Python Distribution and Version:
- Java Distribution and Version:
- Jep Version:4.0.3
- Python packages used (e.g. numpy, pandas, tensorflow):

**Comment by bsteffensmeier** [comment]
No, it is not possible to switch Python versions after Jep has been initialized.
