### ISSUE TITLE
Getting IndentationError on with statement

### ISSUE THREAD

**Issue by pdutta777** [ninia/jep#443]
I am trying to write an indented "with" statement, and getting this error:
`Exception in thread "main" jep.JepException: <class 'IndentationError'>: ('expected an indented block', ('<string>', 1, 54, "with pa.OSFile('/tmp/sparkless.arrow', 'wb') as sink:\n"))`

The code block is:
```
pyjep.exec("with pa.OSFile('/tmp/dummy.arrow', 'wb') as sink:")
pyjep.exec("  with pa.ipc.new_file(sink, df.tbl.schema) as writer:")
pyjep.exec("    for batch in df.tbl.to_batches():")
pyjep.exec("      writer.write(batch)")
```

Is there another way to do this?
This is with jep 4.1.0

**Comment by bsteffensmeier** [comment]
You will need to pass the entire statement into the exec at the same time, like this:

```java
pyjep.exec("with pa.OSFile('/tmp/dummy.arrow', 'wb') as sink:\n" +
           "  with pa.ipc.new_file(sink, df.tbl.schema) as writer:\n" +
           "    for batch in df.tbl.to_batches():\n" +
           "      writer.write(batch)\n")
```

**Comment by pdutta777** [comment]
Thank you. This is working
