### ISSUE TITLE
Why JEP .dll/.so are not distributed with the package?

### ISSUE THREAD

**Issue by akuleshov7** [ninia/jep#450]
Is there any reason why .dll are not distributed with JEP? And everyone needs to build it during the pip install?
Just curious

**Comment by ndjensen** [comment]
Jep is a small project, we only have two active developers, and I am one of those but I haven't been very active recently.  Neither of us wants to take on the responsibility of producing wheels for different platforms and different versions of Python every time we do a release.  Furthermore, there is a complication in that we don't know if someone using Jep wants it compiled with numpy support or not.

**Comment by akuleshov7** [comment]
> Jep is a small project, we only have two active developers, and I am one of those but I haven't been very active recently. Neither of us wants to take on the responsibility of producing wheels for different platforms and different versions of Python every time we do a release. Furthermore, there is a complication in that we don't know if someone using Jep wants it compiled with numpy support or not.

Got it, thank you! As I know some people like @icemachined tried to build it: https://github.com/icemachined/jep-distro/releases

**Comment by icemachined** [comment]
Yes, you can reference my distro in your readme https://github.com/icemachined/jep-distro. 
I've made releases for 4.1.0 and 4.1.1 releases.
It allows jep usage without pip install and building binaries. Building from sources is quite fragile process.
You can also see example of usage of this distro https://github.com/icemachined/jep-distro-example
