### ISSUE TITLE
varargs support in overloaded methods

### ISSUE THREAD

**Issue by andvazqu** [ninia/jep#451]
pyjmultimethod won't match the correct method when using overloaded methods with variable arguments.

**To reproduce**
Use a java class with an overloaded method and variable arguments, such as:
![java_class](https://user-images.githubusercontent.com/48433864/212087745-81bf3087-afa8-4a5c-9fbb-5301147a70d0.png)

Calls to these methods from the jep console return "expected x but received y" or "No such method" errors:
![jep_console](https://user-images.githubusercontent.com/48433864/212088098-e17f29e5-7eee-4cba-9abf-0fd10bebf036.png)

**Expected behavior**
![jep_console_fix](https://user-images.githubusercontent.com/48433864/212088518-5b8855f7-eec9-480d-b7f1-68162146210f.png)

**Comments**
_pyjmultimethod_call_ checks _parameterCount == argsSize_, so a call to _method(1)_ is matched to _method(String...args)_ instead of to _method(int arg, String...args)_ .  _method()_ finds no compatible match.

Made some quick changes to _pyjmultimethod_call_  :
![changes_to_pyjmultimethocall](https://user-images.githubusercontent.com/48433864/212092188-1b43fa39-f92d-4f2f-bd67-1e7d28387efe.png)

and _PyJMethod_CheckArguments_ : 
![changes_to_pyjmethodcheckarguments](https://user-images.githubusercontent.com/48433864/212092218-e7cee089-4390-45aa-9151-9e0139578f3a.png)

to take into consideration variable arguments. This worked for my use case (see expected behavior), but haven't tested it thoroughly. 

**Environment:**
- Windows 10
- Python 3.9
- OpenJDK 11.0.15
- Jep Version 3.9.1 (saw same behavior on 4.1.1)

**Comment by andvazqu** [comment]
Thanks for the quick reply! I added a type check for the use case you mentioned of a method overloaded with varargs of different types and created a pull request.

**Comment by bsteffensmeier** [comment]
This PR was merged into the [4.2 release](https://github.com/ninia/jep/blob/v4.2.0/release_notes/4.2-notes.rst#improved-support-for-varargs) which was officially released today so I am closing this issue.
