### ISSUE TITLE
Exception caught when I called SharedInterpreter.close() function with a High-frequency calling.

### ISSUE THREAD

**Issue by yaha-yj** [ninia/jep#460]
**Describe the bug**
I had an object pool in a python module which was imported into the SharedInterpreter. I don't know if this caused this exception. 

When I created a SharedInterpreter, did sth and close it in one thread with a High-frequency calling, an execption was caught and raised.

Maybe the pyobject was changed in pool and the closing operation was done at the same time?
![image](https://user-images.githubusercontent.com/81953363/227433626-a48dc2aa-e36a-4868-b3c4-77b354a468a2.png)

The number of PyObjects was getting bigger quickly.
![image](https://user-images.githubusercontent.com/81953363/227435175-31d6c4d6-cde1-4a68-bbed-b51bfa163eac.png)

After a while, my jvm crashed...
![image](https://user-images.githubusercontent.com/81953363/227434212-3bcf7601-554f-487c-bf1d-b19bb349f341.png)

**Expected behavior**
How to fix it?

**Environment (please complete the following information):**
- OS Platform, Distribution, and Version: Ubuntu 22.04
- Python Distribution and Version: CPython 3.9.13
- Java Distribution and Version: openjdk version "1.8.0_362"
- Jep Version: 4.1.1
- Python packages used (e.g. numpy, pandas, tensorflow): rpyc

**Comment by ndjensen** [comment]
Why did you close the ticket?  Are you synchronizing externally?  We should be able to fix the ConcurrentModificationException.  I'm not sure how much that relates to the crash, but it looks like MemoryManager isn't thread safe.

**Comment by nomiuo** [comment]
Sorry. I forgot to close the object, so the jvm crashed...
