### ISSUE TITLE
Passing HashMap as an argument of type dict

### ISSUE THREAD

**Issue by jep-learner** [ninia/jep#461]
**Describe the problem**
I am having a problem passing an object of type `HashMap` as an argument of type`dict`. 

Python module `testdict`:

```
def test_dict(param_dict={}):
    for key, value in param_dict.items():
        pass
```

Java class:

```
package org.example;

import jep.Interpreter;
import jep.JepConfig;
import jep.SharedInterpreter;

import java.util.HashMap;

public class ExampleApp {
    public static void main(String[] args) {
        JepConfig config = new JepConfig();
        try (Interpreter interp = new SharedInterpreter()) {
            interp.exec("import testdict");
            HashMap arg = new HashMap();
            interp.set("param_dict", arg);
            interp.exec("testdict.test_dict(param_dict)");
        }catch(Exception e){
            e.printStackTrace();
        }
    }
}
```
Exception:
```
jep.JepException: <class 'AttributeError'>: 'HashMap' object has no attribute 'items'
	at .../testdict.test_dict(testdict.py:2)
	at <string>.<module>(<string>:1)
	at jep.Jep.exec(Native Method)
	at jep.Jep.exec(Jep.java:341)
	at org.example.ExampleApp.main(ExampleApp.java:16)
```

Could you please advise how to fix this issue on the Java side? The Python function signature can not be changed.

Thank you.

**Environment (please complete the following information):**
- OS Platform, Distribution, and Version:
- Python Distribution and Version: 3.10
- Java Distribution and Version: 11
- Jep Version: 4.1.1
- Python packages used (e.g. numpy, pandas, tensorflow): none

**Comment by bsteffensmeier** [comment]
Java Maps are not converted to dicts and while some dict functionality is added by jep they are not completely interchangeable. 
You can write python code to convert the map to a dict. You could use [Map.forEach()](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/Map.html#forEach(java.util.function.BiConsumer)) to convert a map to a dict without much code:

```java
interp.exec("real_param_dict = {}")
interp.exec("param_dict.forEach(lambda k,v: real_param_dict.update({k:v}))"
interp.exec("param_dict = real_param_dict")
```
There is some more information on working with maps in python in [this post](https://github.com/ninia/jep/issues/281#issuecomment-682063181).

**Comment by jep-learner** [comment]
Thank you!
