### ISSUE TITLE
output string with error

### ISSUE THREAD

**Issue by scape7yu** [ninia/jep#484]
When I output English, everything is ok, but when I output Chinese, error comes.

For example:
```python
# output with print
print('中文')
# UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-5: ordinal not in range(128)

# or

# output a excel file of Chinese name
import xlwt

workbook = xlwt.Workbook(encoding='utf-8')
# some code ...
workbook.save('/tmp/中文.xls')
# UnicodeEncodeError: 'ascii' codec can't encode characters in position 5-6: ordinal not in range(128)

**Comment by bsteffensmeier** [comment]
That print statement works correctly on my system without any errors. I suspect there is a problem with your locale settings. I recommend reading more about how Python handles different locale settings. My system seems to be using a UTF-8 encoding while it appears your system is using ascii so I would reco0mmend trying to change settings to get a UTF-8 encoding.

**Comment by scape7yu** [comment]
> 

Thanks for your advice, my code is running on Docker, after I set up it's LANG=zh_CN.UTF-8, this problem disappeared.
So, it's not a issue about JEP.
