### ISSUE TITLE
sometimes, when i new SharedInterpreter, it crashed  most time is ok

### ISSUE THREAD

**Issue by gengxinyuan** [ninia/jep#488]
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x000000000000b8c6, pid=1068, tid=0x00007f732e9e9700
#
# JRE version: OpenJDK Runtime Environment (8.0_345-b01) (build 1.8.0_345-b01)
# Java VM: OpenJDK 64-Bit Server VM (25.345-b01 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  0x000000000000b8c6
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# If you would like to submit a bug report, please visit:
#   https://bugzilla.redhat.com/enter_bug.cgi?product=Red%20Hat%20Enterprise%20Linux%207&component=java-1.8.0-openjdk
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

---------------  T H R E A D  ---------------

Current thread (0x00007f76c82eb000):  JavaThread "task-35" [_thread_in_native, id=41635, stack(0x00007f732e8e9000,0x00007f732e9ea000)]

siginfo: si_signo: 11 (SIGSEGV), si_code: 1 (SEGV_MAPERR), si_addr: 0x000000000000b8c6

Registers:
RAX=0x00007f76621caa00, RBX=0x00007f766248f288, RCX=0x0000000000000000, RDX=0x00007f732e9e7df0
RSP=0x00007f732e9e7d48, RBP=0x00007f732e9e7db8, RSI=0x00007f732e9e7de8, RDI=0x00007f76c82eb2e0
R8 =0x0000000000000000, R9 =0x00007f732e9e7df0, R10=0x00007f78410184db, R11=0x00007f7856941f10
R12=0x0000000000000000, R13=0x00007f766248f280, R14=0x00007f732e9e7df0, R15=0x00007f76c82eb000
RIP=0x000000000000b8c6, EFLAGS=0x0000000000010287, CSGSFS=0x0000000000000033, ERR=0x0000000000000014
  TRAPNO=0x000000000000000e

Top of Stack: (sp=0x00007f732e9e7d48)
0x00007f732e9e7d48:   00007f7841018507 0000000000000012
0x00007f732e9e7d58:   5b2de16451eda500 00000007933436a0
0x00007f732e9e7d68:   00007f783878e600 0000000000000000
0x00007f732e9e7d78:   00007f732e9e7d78 0000000000000000
0x00007f732e9e7d88:   00007f732e9e7df0 00007f7662490c18
0x00007f732e9e7d98:   0000000000000000 00007f766248f288
0x00007f732e9e7da8:   0000000000000000 00007f732e9e7dd8
0x00007f732e9e7db8:   00007f732e9e7e40 00007f7841007b90
0x00007f732e9e7dc8:   0000000000000000 00007f7841011af7
0x00007f732e9e7dd8:   0000000000000000 0000000000000000
0x00007f732e9e7de8:   0000000080220ab0 00000006b9065918
0x00007f732e9e7df8:   00000006b9065918 00007f732e9e7e00
0x00007f732e9e7e08:   00007f766248ef09 00007f732e9e7e78
0x00007f732e9e7e18:   00007f7662490c18 00007f74699ea270
0x00007f732e9e7e28:   00007f766248ef50 00007f732e9e7dd8
0x00007f732e9e7e38:   00007f732e9e7e68 00007f732e9e7ec0
0x00007f732e9e7e48:   00007f78410080a1 0000000000000000
0x00007f732e9e7e58:   0000000000000000 0000000082572468
0x00007f732e9e7e68:   0000000000000000 000000008231ef30
0x00007f732e9e7e78:   00000006b9065918 00007f732e9e7e80
0x00007f732e9e7e88:   00007f766248d30d 00007f732e9e7ed0
0x00007f732e9e7e98:   00007f7662491540 00007f74699e9d98
0x00007f732e9e7ea8:   00007f766248d328 00007f732e9e7e68
0x00007f732e9e7eb8:   00007f732e9e7ed0 00007f732e9e7f30
0x00007f732e9e7ec8:   00007f78410080a1 00000006b9065918
0x00007f732e9e7ed8:   00000006b9065918 00000049964d7509
0x00007f732e9e7ee8:   00000000812d2218 00007f732e9e7ee0
0x00007f732e9e7ef8:   00007f77591f3d40 00007f732e9e7fc8
0x00007f732e9e7f08:   00007f770300b7c8 0000000000000000
0x00007f732e9e7f18:   00007f77591f4288 00007f732e9e7ed0
0x00007f732e9e7f28:   00007f732e9e7fc0 00007f732e9e8030
0x00007f732e9e7f38:   00007f78410004e7 0000000000000000 

Instructions: (pc=0x000000000000b8c6)
0x000000000000b8a6:   
[error occurred during error reporting (printing registers, top of stack, instructions near pc), id 0xb]

Register to memory mapping:

RAX=
[error occurred during error reporting (printing register info), id 0xb]

Stack: [0x00007f732e8e9000,0x00007f732e9ea000],  sp=0x00007f732e9e7d48,  free space=1019k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  0x000000000000b8c6
j  jep.Jep.<init>(Ljep/JepConfig;Z)V+193
j  jep.SharedInterpreter.<init>()V+5
j  com.lenovo.solver.pythonconnector.Service.CNxAppHelperInterpreter.InterpreterCall(Lcom/lenovo/solver/pythonconnector/vo/modelInputData;)Z+824
v  ~StubRoutines::call_stub
V  [libjvm.so+0x69f39e]  JavaCalls::call_helper(JavaValue*, methodHandle*, JavaCallArguments*, Thread*)+0xf6e
V  [libjvm.so+0x9c579f]  Reflection::invoke(instanceKlassHandle, methodHandle, Handle, bool, objArrayHandle, BasicType, objArrayHandle, bool, Thread*)+0x80f
V  [libjvm.so+0x9c6123]  Reflection::invoke_method(oopDesc*, Handle, objArrayHandle, Thread*)+0x193
V  [libjvm.so+0x73fd73]  JVM_InvokeMethod+0x1b3
J 2272  sun.reflect.NativeMethodAccessorImpl.invoke0(Ljava/lang/reflect/Method;Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object; (0 bytes) @ 0x00007f784199d93d [0x00007f784199d840+0xfd]
J 11693 C2 sun.reflect.NativeMethodAccessorImpl.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object; (104 bytes) @ 0x00007f78420de7f4 [0x00007f78420de780+0x74]
J 23016 C2 org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(Ljava/lang/Object;Ljava/lang/reflect/Method;[Ljava/lang/Object;)Ljava/lang/Object; (94 bytes) @ 0x00007f7843dc7b98 [0x00007f7843dc7ae0+0xb8]
j  org.springframework.aop.framework.JdkDynamicAopProxy.invoke(Ljava/lang/Object;Ljava/lang/reflect/Method;[Ljava/lang/Object;)Ljava/lang/Object;+358
j  com.sun.proxy.$Proxy125.InterpreterCall(Lcom/lenovo/solver/pythonconnector/vo/modelInputData;)Z+16
j  com.lenovo.ml.pae.mrp.service.MrpService.invokeAlgorithm(II)V+140
j  com.lenovo.ml.pae.mrp.service.MrpService$$FastClassBySpringCGLIB$$145a41.invoke(ILjava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;+232
J 21232 C2 org.springframework.aop.framework.ReflectiveMethodInvocation.proceed()Ljava/lang/Object; (126 bytes) @ 0x00007f7844faeea4 [0x00007f7844faedc0+0xe4]
j  org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(Lorg/aopalliance/intercept/MethodInvocation;Ljava/lang/reflect/Method;)Ljava/lang/Object;+1
j  org.springframework.aop.interceptor.AsyncExecutionInterceptor$$Lambda$472.call()Ljava/lang/Object;+12
J 23339 C2 java.util.concurrent.FutureTask.run()V (126 bytes) @ 0x00007f7842b9e674 [0x00007f7842b9e400+0x274]
J 21585 C2 java.util.concurrent.ThreadPoolExecutor.runWorker(Ljava/util/concurrent/ThreadPoolExecutor$Worker;)V (225 bytes) @ 0x00007f784374a2ec [0x00007f784374a140+0x1ac]
j  java.util.concurrent.ThreadPoolExecutor$Worker.run()V+5
j  java.lang.Thread.run()V+11
v  ~StubRoutines::call_stub
V  [libjvm.so+0x69f39e]  JavaCalls::call_helper(JavaValue*, methodHandle*, JavaCallArguments*, Thread*)+0xf6e
V  [libjvm.so+0x69c754]  JavaCalls::call_virtual(JavaValue*, KlassHandle, Symbol*, Symbol*, JavaCallArguments*, Thread*)+0x2c4
V  [libjvm.so+0x69cd69]  JavaCalls::call_virtual(JavaValue*, Handle, KlassHandle, Symbol*, Symbol*, Thread*)+0x59
V  [libjvm.so+0x734ab1]  thread_entry(JavaThread*, Thread*)+0xa1
V  [libjvm.so+0xb0d7d2]  JavaThread::thread_main_inner()+0x212
V  [libjvm.so+0x93e942]  java_start(Thread*)+0xf2
C  [libpthread.so.0+0x7ea5]  start_thread+0xc5

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  jep.Jep.init(Ljava/lang/ClassLoader;ZZ)J+0
j  jep.Jep.<init>(Ljep/JepConfig;Z)V+193
j  jep.SharedInterpreter.<init>()V+5
j  com.lenovo.solver.pythonconnector.Service.CNxAppHelperInterpreter.InterpreterCall(Lcom/lenovo/solver/pythonconnector/vo/modelInputData;)Z+824
v  ~StubRoutines::call_stub
J 2272  sun.reflect.NativeMethodAccessorImpl.invoke0(Ljava/lang/reflect/Method;Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object; (0 bytes) @ 0x00007f784199d8c7 [0x00007f784199d840+0x87]
J 11693 C2 sun.reflect.NativeMethodAccessorImpl.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object; (104 bytes) @ 0x00007f78420de7f4 [0x00007f78420de780+0x74]
J 23016 C2 org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(Ljava/lang/Object;Ljava/lang/reflect/Method;[Ljava/lang/Object;)Ljava/lang/Object; (94 bytes) @ 0x00007f7843dc7b98 [0x00007f7843dc7ae0+0xb8]
j  org.springframework.aop.framework.JdkDynamicAopProxy.invoke(Ljava/lang/Object;Ljava/lang/reflect/Method;[Ljava/lang/Object;)Ljava/lang/Object;+358
j  com.sun.proxy.$Proxy125.InterpreterCall(Lcom/lenovo/solver/pythonconnector/vo/modelInputData;)Z+16
j  com.lenovo.ml.pae.mrp.service.MrpService.invokeAlgorithm(II)V+140
j  com.lenovo.ml.pae.mrp.service.MrpService$$FastClassBySpringCGLIB$$145a41.invoke(ILjava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;+232
J 21232 C2 org.springframework.aop.framework.ReflectiveMethodInvocation.proceed()Ljava/lang/Object; (126 bytes) @ 0x00007f7844faeea4 [0x00007f7844faedc0+0xe4]
j  org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(Lorg/aopalliance/intercept/MethodInvocation;Ljava/lang/reflect/Method;)Ljava/lang/Object;+1
j  org.springframework.aop.interceptor.AsyncExecutionInterceptor$$Lambda$472.call()Ljava/lang/Object;+12
J 23339 C2 java.util.concurrent.FutureTask.run()V (126 bytes) @ 0x00007f7842b9e674 [0x00007f7842b9e400+0x274]
J 21585 C2 java.util.concurrent.ThreadPoolExecutor.runWorker(Ljava/util/concurrent/ThreadPoolExecutor$Worker;)V (225 bytes) @ 0x00007f784374a2ec [0x00007f784374a140+0x1ac]
j  java.util.concurrent.ThreadPoolExecutor$Worker.run()V+5
j  java.lang.Thread.run()V+11
v  ~StubRoutines::call_stub

**Comment by bsteffensmeier** [comment]
Since this is not a common occurrence with other jep users the most likely cause is something in your environment or interoperability with a specific python library you are using. I recommend you provide the information requested in the [bug report template](https://github.com/ninia/jep/issues/new?template=bug_report.md) and try to provide an reproducible test case so that we have the information we need to identify the cause of your issue.

**Comment by gengxinyuan** [comment]
ok i report as bug。and close this。bug link：
https://github.com/ninia/jep/issues/489
