### ISSUE TITLE
Installed Jep not numpy enabled despite numpy package being pre-installed

### ISSUE THREAD

**Issue by georgea3** [ninia/jep#490]
**Describe the problem**
I have installed Jep 4.1.1 through pip and source and despite having numpy pre-installed always, Jep ends up being NOT numpy enabled. I dont get any error messages or warnings on Jep installation. I dont see any messages in the console about numpy either (whether found or not found).
I confirm Jep is not numpy enabled by running 
```
import jep
jep.JEP_NUMPY_ENABLED
```
and this returns 0.

Any help greatly appreciated, thank you.

**Environment (please complete the following information):**
- OS Platform, Distribution, and Version: RHEL7
- Python Distribution and Version: Linux 3.11.4 (built from source)
- Java Distribution and Version: Oracle 1.8.0.171
- Jep Version: 4.1.1
- Python packages used (e.g. numpy, pandas, tensorflow): numpy 1.24.3, pandas 2.0.3, tensorflow 1.13.0

**Comment by bsteffensmeier** [comment]
That is unusual. One potential problem is that pip will cache packages so if you previously built jep without numpy installed then even if you do `pip uninstall jep` and `pip install jep` it will use the cached package and you will not have numpy support. To make sure this isn't the case you can do `pip uninstall jep`, `pip cache remove jep` and then `pip install jep`

Another thing to help troubleshooting, when you install jep you should be able to get the full logs from setup.py by doing `pip3 install jep --log jep.log` that log file should include a line [from setup.py](https://github.com/ninia/jep/blob/v4.1.1/setup.py#L34-L38) that says either "numpy include found at" or "numpy not found".

**Comment by georgea3** [comment]
It must have been a cache problem as following your steps has resolved my problem. 
The log file now does indeed say 
`2023-08-15T21:59:13,318   numpy include found at /home/~/Desktop/take6/lib/python3.11/site-packages/numpy/core/include
`
Thanks very much for the help and prompt reply.
