### ISSUE TITLE
Unable to obtain standard output with jep

### ISSUE THREAD

**Issue by qmj123** [ninia/jep#505]
hi!
Unable to obtain standard output through jep in Java.
![image](https://github.com/ninia/jep/assets/33482101/b157f46a-1bb0-41e3-8b03-15515f882c76)

**Comment by ndjensen** [comment]
Try importing `sys` and call `sys.stdout.flush()`.  Or use `JepConfig.setRedirectStdout(System.out)` to use Java's System.out PrinstStream.

**Comment by qmj123** [comment]
Thank you very much for your reply. We have obtained it according to the method you mentioned.
