### ISSUE TITLE
Cannot Import Custom Module

### ISSUE THREAD

**Issue by aghasemi** [ninia/jep#514]
**Describe the problem**
Hello,
Is there a special method for importing custom modules (i.e. Python files in the same directory) vs. ordinary, installed modules? I get "NoModuleFoundError" despite haveing the Python file in the same directory and making sure that both Java and Python are in the right "current directory". 

Many thanks
Best
 
**Environment (please complete the following information):**
- OS Platform, Distribution, and Version: Ubuntu 22.04
- Python Distribution and Version: 3.10.12
- Java Distribution and Version: 21
- Jep Version: 4.2.0
- Python packages used (e.g. numpy, pandas, tensorflow): none

**Comment by bsteffensmeier** [comment]
When embedding python the current working directory is not automatically added to the path. You can add the cwd to the path by adding "." to [JepConfig.addIncludePath](https://ninia.github.io/jep/javadoc/4.2/jep/JepConfig.html#addIncludePaths-java.lang.String...-), or the PYTHONPATH env var or adding it to sys.path in the Interpreter.

**Comment by aghasemi** [comment]
Worked. Many thanks.
