### ISSUE TITLE
Java Runtime Environment crashed after using SharedInterpreter.invoke() twice

### ISSUE THREAD

**Issue by Loc300** [ninia/jep#522]
The problem:
I need to make predictions with pytorch in java and so im trying to use JEP to communicate between java and python.
On the first iteration i get an output as expected, but after the first run, i get this large error message 

 A fatal error has been detected by the Java Runtime Environment:

SIGSEGV (0xb) at pc=0x00007ff815e1f3e4, pid=3753, tid=0x0000000000002803

JRE version: OpenJDK Runtime Environment (8.0_302-b08) (build 1.8.0_302-b08)
Java VM: OpenJDK 64-Bit Server VM (25.302-b08 mixed mode bsd-amd64 compressed oops)
Problematic frame:
 C  [libsystem_pthread.dylib+0x13e4]  pthread_mutex_lock+0x4
somtimes: C  [Python+0x12d713]  take_gil+0x30

Im using the 
`
MainInterpreter.setJepLibraryPath()
`
to set the libjep.jnilib path on mac.

And   
` interp.eval("import sys"); &
  interp.eval("sys.path.append('')
`
 to define the path in which other .py functionalities have been defined
                  
`interp.runScript()` to get to the python file path
and `interp.invoke()` to execute the method with the required parameters

Could someone help me with this?

Im Using an M1 Macbook Pro
- Sonoma 14.4 (23E214)
- Python 3.11
- JEP==4.2.0
- Python packages are mostly pytorch, numpy, logging and json

**Comment by bsteffensmeier** [comment]
Are you using SharedInterpreter or SubInterpreter. Numpy is not compatible with SubInterpreter and will often fail when it is used in a second SubInterpreter. If that is the problem then using SharedINterpreter should fix it.

**Comment by ndjensen** [comment]
I'm not sure Jep can do anything about a SIGSEGV in `libsystem_pthread.dylib`.  Was there a stacktrace that showed what was calling take_gil or pthread_mutex_lock?  If you could create a small, reproducible test case that shows the issue, that would help.

**Comment by Loc300** [comment]
So im using gradle and my project calling jep. Im really bad at reading such errors. There are `Thread` and `Process` wich are looking like that


> ---------------  T H R E A D  ---------------

Current thread (0x00007fae75809000):  JavaThread "main" [_thread_in_native, id=9219, stack(0x000000030d631000,0x000000030d731000)]

siginfo: si_signo: 11 (SIGSEGV), si_code: 1 (SEGV_MAPERR), si_addr: 0x0000012b7ba8f1b8

Registers:
RAX=0x0000000000000000, RBX=0x00007fae22f06350, RCX=0x000000030d7310ac, RDX=0x0000000000000001
RSP=0x000000030d730010, RBP=0x000000030d730010, RSI=0x00000001849a9770, RDI=0x0000012b7ba8f1b8
R8 =0x0000000000005798, R9 =0xffffffff00000000, R10=0x0000000000000000, R11=0x0000000100000000
R12=0x000000012b840017, R13=0x0000012b7ba8f000, R14=0x00007fae22f06350, R15=0x0000000000000000
RIP=0x00007ff8148833e4, EFLAGS=0x0000000000000247, ERR=0x0000000000000004
  TRAPNO=0x000000000000000e

Top of Stack: (sp=0x000000030d730010)
0x000000030d730010:   000000030d730080 000000012b5a6728
0x000000030d730020:   00007fae06206c20 00000001849e7270
0x000000030d730030:   3fd3333333333333 000000014a3f7713
0x000000030d730040:   0000012b7ba8f1b8 3fd3333333333333
0x000000030d730050:   000000030d730218 00007fae22f06350
0x000000030d730060:   0000000135461fe0 000000012ea1a320
0x000000030d730070:   00007fae43135c70 0000000000000000
0x000000030d730080:   000000030d7300a0 000000012b5a6f4a
0x000000030d730090:   0000000000000001 000000030d7300e8
0x000000030d7300a0:   000000030d7300c0 000000012dc510e3
0x000000030d7300b0:   0000000000000001 00000001849a9770
0x000000030d7300c0:   000000030d730160 000000012e197849
0x000000030d7300d0:   000000030d730190 000000012b832cb0
0x000000030d7300e0:   000000012b8410f8 00007fae22f06350
0x000000030d7300f0:   00007fae03370101 0000000000000000
0x000000030d730100:   000000030d730170 0000600000416378
0x000000030d730110:   000000030d730170 000000012e230802
0x000000030d730120:   000000030d730170 0000000100000000
0x000000030d730130:   000000012b832c40 000000030d730220
0x000000030d730140:   000000030d730190 00007fae033779d0
0x000000030d730150:   00006000004162b8 0000600000416280
0x000000030d730160:   000000030d730180 000000012c769327
0x000000030d730170:   000000012c795098 0000600000416280
0x000000030d730180:   000000030d7301a0 000000012c754f8d
0x000000030d730190:   0000600000416280 00006000004161c0
0x000000030d7301a0:   000000030d7301c0 000000012c75521e
0x000000030d7301b0:   000000012c795098 00007fae430f04d0
0x000000030d7301c0:   000000030d7301e0 000000014dad92b3
0x000000030d7301d0:   000000015d69a090 00007fae430f04d0
0x000000030d7301e0:   000000030d730200 000000014dad5d1e
0x000000030d7301f0:   000000015d69a090 0000000000000000
0x000000030d730200:   000000030d730220 000000012c755014 

Instructions: (pc=0x00007ff8148833e4)
0x00007ff8148833c4:   34 c1 48 89 03 31 db 48 8d 3d a2 8b 3c 43 e8 a3
0x00007ff8148833d4:   84 00 00 89 d8 5b 41 5e 5d c3 90 90 55 48 89 e5
0x00007ff8148833e4:   48 81 3f 5a 54 55 4d 75 73 8b 47 0c 89 c1 81 e1
0x00007ff8148833f4:   c0 01 00 00 83 f9 40 74 6b 0f ba e0 0e 72 6d 48 

Register to memory mapping:

RAX=0x0000000000000000 is an unknown value
RBX=0x00007fae22f06350 is an unknown value
RCX=0x000000030d7310ac is an unknown value
RDX=0x0000000000000001 is an unknown value
RSP=0x000000030d730010 is pointing into the stack for thread: 0x00007fae75809000
RBP=0x000000030d730010 is pointing into the stack for thread: 0x00007fae75809000
RSI=0x00000001849a9770 is an unknown value
RDI=0x0000012b7ba8f1b8 is an unknown value
R8 =0x0000000000005798 is an unknown value
R9 =0xffffffff00000000 is an unknown value
R10=0x0000000000000000 is an unknown value
R11=0x0000000100000000 is an unknown value
R12=0x000000012b840017: _PyRuntime+0xd58f in /usr/local/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/Python at 0x000000012b479000
R13=0x0000012b7ba8f000 is an unknown value
R14=0x00007fae22f06350 is an unknown value
R15=0x0000000000000000 is an unknown value


Stack: [0x000000030d631000,0x000000030d731000],  sp=0x000000030d730010,  free space=1020k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libsystem_pthread.dylib+0x13e4]  pthread_mutex_lock+0x4
C  [Python+0x12d728]  take_gil+0x45
C  [Python+0x12df4a]  PyEval_AcquireThread+0x13
C  [libtorch_python.dylib+0x430e3]  pybind11::gil_scoped_acquire::gil_scoped_acquire()+0x53
C  [libtorch_python.dylib+0x589849]  (anonymous namespace)::ConcretePyInterpreterVTable::decref(_object*, bool) const+0x29
C  [libc10.dylib+0x2d327]  c10::impl::PyObjectSlot::destroy_pyobj_if_needed()+0x37
C  [libc10.dylib+0x18f8d]  c10::TensorImpl::~TensorImpl()+0x1d
C  [libc10.dylib+0x1921e]  c10::TensorImpl::~TensorImpl()+0xe
C  [libtorch_cpu.dylib+0x39aa2b3]  torch::autograd::DifferentiableViewMeta::~DifferentiableViewMeta()+0x123
C  [libtorch_cpu.dylib+0x39a6d1e]  torch::autograd::DifferentiableViewMeta::~DifferentiableViewMeta()+0xe
C  [libc10.dylib+0x19014]  c10::TensorImpl::~TensorImpl()+0xa4
C  [libc10.dylib+0x1921e]  c10::TensorImpl::~TensorImpl()+0xe
C  [libtorch_python.dylib+0x593265]  c10::MaybeOwned<at::Tensor>::operator=(c10::MaybeOwned<at::Tensor>&&)+0x85
C  [libtorch_python.dylib+0x629b09]  THPVariable_clear(THPVariable*)+0x169
C  [libtorch_python.dylib+0x62a1f4]  THPVariable_subclass_dealloc(_object*)+0x1b4
C  [Python+0x12f9af]  _PyEval_EvalFrameDefault+0x7ef
C  [Python+0x13eec2]  _PyEval_Vector+0x5c
C  [libjep.jnilib+0xeaf1]  pyembed_invoke_as+0x1a1
C  [libjep.jnilib+0xed76]  pyembed_invoke_method_as+0x196
C  [libjep.jnilib+0x7c7e]  Java_jep_Jep_invoke+0x3e
j  jep.Jep.invoke(JLjava/lang/String;[Ljava/lang/Object;Ljava/util/Map;)Ljava/lang/Object;+0
j  jep.Jep.invoke(Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/Object;+38
j  Main.Predict(Ljava/util/List;Ljava/util/List;Ljava/lang/String;)Lde/main$Probabilities;+337
j  test.predict()Z+26
j  test.run()V+54
j  main([Ljava/lang/String;)V+183
v  ~StubRoutines::call_stub
V  [libjvm.dylib+0x2c9563]  JavaCalls::call_helper(JavaValue*, methodHandle*, JavaCallArguments*, Thread*)+0x691
V  [libjvm.dylib+0x304197]  jni_invoke_static(JNIEnv_*, JavaValue*, _jobject*, JNICallType, _jmethodID*, JNI_ArgumentPusher*, Thread*)+0x248
V  [libjvm.dylib+0x307816]  jni_CallStaticVoidMethod+0x1f7
C  [java+0x2d92]  JavaMain+0x9df
C  [libsystem_pthread.dylib+0x618b]  _pthread_start+0x63
C  [libsystem_pthread.dylib+0x1ae3]  thread_start+0xf
C  0x0000000000000000

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  jep.Jep.invoke(JLjava/lang/String;[Ljava/lang/Object;Ljava/util/Map;)Ljava/lang/Object;+0
j  jep.Jep.invoke(Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/Object;+38
j  main.Predict(Ljava/util/List;Ljava/util/List;Ljava/lang/String;)Lde/main$Probabilities;+337
j  test.predict()Z+26
j  test.run()V+54
j  main([Ljava/lang/String;)V+183
v  ~StubRoutines::call_stub


> ---------------  P R O C E S S  ---------------

Java Threads: ( => current thread )
  0x00007fae73ad3000 JavaThread "JepMainInterpreter" daemon [_thread_blocked, id=27427, stack(0x000000030ee85000,0x000000030ef85000)]
  0x00007fae73860800 JavaThread "Service Thread" daemon [_thread_blocked, id=25095, stack(0x000000030ec7f000,0x000000030ed7f000)]
  0x00007fae73857800 JavaThread "C1 CompilerThread3" daemon [_thread_blocked, id=24067, stack(0x000000030eb7c000,0x000000030ec7c000)]
  0x00007fae73854800 JavaThread "C2 CompilerThread2" daemon [_thread_blocked, id=23811, stack(0x000000030ea79000,0x000000030eb79000)]
  0x00007fae74842800 JavaThread "C2 CompilerThread1" daemon [_thread_blocked, id=30723, stack(0x000000030e976000,0x000000030ea76000)]
  0x00007fae74841000 JavaThread "C2 CompilerThread0" daemon [_thread_blocked, id=30979, stack(0x000000030e873000,0x000000030e973000)]
  0x00007fae7483e000 JavaThread "JDWP Command Reader" daemon [_thread_in_native, id=23043, stack(0x000000030e770000,0x000000030e870000)]
  0x00007fae74836800 JavaThread "JDWP Event Helper Thread" daemon [_thread_blocked, id=31747, stack(0x000000030e66d000,0x000000030e76d000)]
  0x00007fae7301d000 JavaThread "JDWP Transport Listener: dt_socket" daemon [_thread_blocked, id=22539, stack(0x000000030e56a000,0x000000030e66a000)]
  0x00007fae7381c800 JavaThread "Signal Dispatcher" daemon [_thread_blocked, id=22275, stack(0x000000030e467000,0x000000030e567000)]
  0x00007fae74816000 JavaThread "Finalizer" daemon [_thread_blocked, id=17439, stack(0x000000030e255000,0x000000030e355000)]
  0x00007fae7581d000 JavaThread "Reference Handler" daemon [_thread_blocked, id=16931, stack(0x000000030e152000,0x000000030e252000)]
=>0x00007fae75809000 JavaThread "main" [_thread_in_native, id=9219, stack(0x000000030d631000,0x000000030d731000)]

Other Threads:
  0x00007fae7581a800 VMThread [stack: 0x000000030e04f000,0x000000030e14f000] [id=20995]
  0x00007fae7306d000 WatcherThread [stack: 0x000000030ed82000,0x000000030ee82000] [id=29699]

VM state:not at safepoint (normal execution)

VM Mutex/Monitor currently owned by a thread: None

heap address: 0x00000006c0000000, size: 4096 MB, Compressed Oops mode: Zero based, Oop shift amount: 3
Narrow klass base: 0x0000000000000000, Narrow klass shift: 3
Compressed class space size: 1073741824 Address: 0x00000007c0000000

Heap:
 PSYoungGen      total 1392640K, used 927250K [0x000000076ab00000, 0x00000007bff00000, 0x00000007c0000000)
  eden space 1391616K, 66% used [0x000000076ab00000,0x00000007a33ec840,0x00000007bfa00000)
  from space 1024K, 59% used [0x00000007bfa00000,0x00000007bfa98000,0x00000007bfb00000)
  to   space 2560K, 0% used [0x00000007bfc80000,0x00000007bfc80000,0x00000007bff00000)
 ParOldGen       total 175104K, used 6638K [0x00000006c0000000, 0x00000006cab00000, 0x000000076ab00000)
  object space 175104K, 3% used [0x00000006c0000000,0x00000006c067bb20,0x00000006cab00000)
 Metaspace       used 9311K, capacity 9652K, committed 9856K, reserved 1058816K
  class space    used 1032K, capacity 1118K, committed 1152K, reserved 1048576K

Card table byte_map: [0x000000010d701000,0x000000010df02000] byte_map_base: 0x000000010a101000

Marking Bits: (ParMarkBitMap*) 0x000000010e844ec8
 Begin Bits: [0x000000011f4cd000, 0x00000001234cd000)
 End Bits:   [0x00000001234cd000, 0x00000001274cd000)

Polling page: 0x000000010ce16000

CodeCache: size=245760Kb used=6046Kb max_used=6082Kb free=239713Kb
 bounds [0x000000010ff77000, 0x0000000110577000, 0x000000011ef77000]
 total_blobs=1703 nmethods=1381 adapters=244
 compilation: enabled

Compilation events (10 events):
Event: 15.362 Thread 0x00007fae73854800 1376       4       com.google.gson.reflect.TypeToken::get (9 bytes)
Event: 15.365 Thread 0x00007fae74841000 nmethod 1374 0x0000000110548c10 code [0x0000000110548e80, 0x0000000110549c50]
Event: 15.365 Thread 0x00007fae74841000 1380       4       com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper::write (80 bytes)
Event: 15.371 Thread 0x00007fae74841000 nmethod 1380 0x000000011054aa10 code [0x000000011054aba0, 0x000000011054af18]
Event: 15.371 Thread 0x00007fae74841000 1379       4       com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter::write (10 bytes)
Event: 15.372 Thread 0x00007fae73854800 nmethod 1376 0x00000001105585d0 code [0x0000000110558840, 0x00000001105596f0]
Event: 15.377 Thread 0x00007fae73857800 1381       3       java.util.regex.Pattern$Branch::match (66 bytes)
Event: 15.378 Thread 0x00007fae73857800 nmethod 1381 0x0000000110541090 code [0x0000000110541240, 0x0000000110541738]
Event: 15.386 Thread 0x00007fae74841000 nmethod 1379 0x000000011055a550 code [0x000000011055a800, 0x000000011055b980]
Event: 15.456 Thread 0x00007fae74842800 nmethod 1377 0x0000000110564810 code [0x0000000110564ee0, 0x000000011056b0a8]

GC Heap History (10 events):
Event: 3.899 GC heap before
{Heap before GC invocations=17 (full 0):
 PSYoungGen      total 1391616K, used 1388544K [0x000000076ab00000, 0x00000007c0000000, 0x00000007c0000000)
  eden space 1388032K, 100% used [0x000000076ab00000,0x00000007bf680000,0x00000007bf680000)
  from space 3584K, 14% used [0x00000007bf980000,0x00000007bfa00000,0x00000007bfd00000)
  to   space 3072K, 0% used [0x00000007bf680000,0x00000007bf680000,0x00000007bf980000)
 ParOldGen       total 175104K, used 4790K [0x00000006c0000000, 0x00000006cab00000, 0x000000076ab00000)
  object space 175104K, 2% used [0x00000006c0000000,0x00000006c04adb10,0x00000006cab00000)
 Metaspace       used 7924K, capacity 8164K, committed 8448K, reserved 1056768K
  class space    used 887K, capacity 944K, committed 1024K, reserved 1048576K
Event: 3.901 GC heap after
Heap after GC invocations=17 (full 0):
 PSYoungGen      total 1391104K, used 576K [0x000000076ab00000, 0x00000007bff80000, 0x00000007c0000000)
  eden space 1388032K, 0% used [0x000000076ab00000,0x000000076ab00000,0x00000007bf680000)
  from space 3072K, 18% used [0x00000007bf680000,0x00000007bf710010,0x00000007bf980000)
  to   space 3072K, 0% used [0x00000007bfc80000,0x00000007bfc80000,0x00000007bff80000)
 ParOldGen       total 175104K, used 5142K [0x00000006c0000000, 0x00000006cab00000, 0x000000076ab00000)
  object space 175104K, 2% used [0x00000006c0000000,0x00000006c0505b10,0x00000006cab00000)
 Metaspace       used 7924K, capacity 8164K, committed 8448K, reserved 1056768K
  class space    used 887K, capacity 944K, committed 1024K, reserved 1048576K
}
Event: 4.152 GC heap before
{Heap before GC invocations=18 (full 0):
 PSYoungGen      total 1391104K, used 1388608K [0x000000076ab00000, 0x00000007bff80000, 0x00000007c0000000)
  eden space 1388032K, 100% used [0x000000076ab00000,0x00000007bf680000,0x00000007bf680000)
  from space 3072K, 18% used [0x00000007bf680000,0x00000007bf710010,0x00000007bf980000)
  to   space 3072K, 0% used [0x00000007bfc80000,0x00000007bfc80000,0x00000007bff80000)
 ParOldGen       total 175104K, used 5142K [0x00000006c0000000, 0x00000006cab00000, 0x000000076ab00000)
  object space 175104K, 2% used [0x00000006c0000000,0x00000006c0505b10,0x00000006cab00000)
 Metaspace       used 7924K, capacity 8164K, committed 8448K, reserved 1056768K
  class space    used 887K, capacity 944K, committed 1024K, reserved 1048576K
Event: 4.162 GC heap after
Heap after GC invocations=18 (full 0):
 PSYoungGen      total 1394176K, used 512K [0x000000076ab00000, 0x00000007c0000000, 0x00000007c0000000)
  eden space 1391104K, 0% used [0x000000076ab00000,0x000000076ab00000,0x00000007bf980000)
  from space 3072K, 16% used [0x00000007bfc80000,0x00000007bfd00000,0x00000007bff80000)
  to   space 3072K, 0% used [0x00000007bf980000,0x00000007bf980000,0x00000007bfc80000)
 ParOldGen       total 175104K, used 5534K [0x00000006c0000000, 0x00000006cab00000, 0x000000076ab00000)
  object space 175104K, 3% used [0x00000006c0000000,0x00000006c0567b20,0x00000006cab00000)
 Metaspace       used 7924K, capacity 8164K, committed 8448K, reserved 1056768K
  class space    used 887K, capacity 944K, committed 1024K, reserved 1048576K
}
Event: 4.408 GC heap before
{Heap before GC invocations=19 (full 0):
 PSYoungGen      total 1394176K, used 1391616K [0x000000076ab00000, 0x00000007c0000000, 0x00000007c0000000)
  eden space 1391104K, 100% used [0x000000076ab00000,0x00000007bf980000,0x00000007bf980000)
  from space 3072K, 16% used [0x00000007bfc80000,0x00000007bfd00000,0x00000007bff80000)
  to   space 3072K, 0% used [0x00000007bf980000,0x00000007bf980000,0x00000007bfc80000)
 ParOldGen       total 175104K, used 5534K [0x00000006c0000000, 0x00000006cab00000, 0x000000076ab00000)
  object space 175104K, 3% used [0x00000006c0000000,0x00000006c0567b20,0x00000006cab00000)
 Metaspace       used 7938K, capacity 8164K, committed 8448K, reserved 1056768K
  class space    used 887K, capacity 944K, committed 1024K, reserved 1048576K
Event: 4.409 GC heap after
Heap after GC invocations=19 (full 0):
 PSYoungGen      total 1394176K, used 512K [0x000000076ab00000, 0x00000007c0000000, 0x00000007c0000000)
  eden space 1391104K, 0% used [0x000000076ab00000,0x000000076ab00000,0x00000007bf980000)
  from space 3072K, 16% used [0x00000007bf980000,0x00000007bfa00000,0x00000007bfc80000)
  to   space 3072K, 0% used [0x00000007bfd00000,0x00000007bfd00000,0x00000007c0000000)
 ParOldGen       total 175104K, used 5902K [0x00000006c0000000, 0x00000006cab00000, 0x000000076ab00000)
  object space 175104K, 3% used [0x00000006c0000000,0x00000006c05c3b20,0x00000006cab00000)
 Metaspace       used 7938K, capacity 8164K, committed 8448K, reserved 1056768K
  class space    used 887K, capacity 944K, committed 1024K, reserved 1048576K
}
Event: 4.661 GC heap before
{Heap before GC invocations=20 (full 0):
 PSYoungGen      total 1394176K, used 1391616K [0x000000076ab00000, 0x00000007c0000000, 0x00000007c0000000)
  eden space 1391104K, 100% used [0x000000076ab00000,0x00000007bf980000,0x00000007bf980000)
  from space 3072K, 16% used [0x00000007bf980000,0x00000007bfa00000,0x00000007bfc80000)
  to   space 3072K, 0% used [0x00000007bfd00000,0x00000007bfd00000,0x00000007c0000000)
 ParOldGen       total 175104K, used 5902K [0x00000006c0000000, 0x00000006cab00000, 0x000000076ab00000)
  object space 175104K, 3% used [0x00000006c0000000,0x00000006c05c3b20,0x00000006cab00000)
 Metaspace       used 7942K, capacity 8164K, committed 8448K, reserved 1056768K
  class space    used 887K, capacity 944K, committed 1024K, reserved 1048576K
Event: 4.673 GC heap after
Heap after GC invocations=20 (full 0):
 PSYoungGen      total 1394688K, used 544K [0x000000076ab00000, 0x00000007c0000000, 0x00000007c0000000)
  eden space 1391616K, 0% used [0x000000076ab00000,0x000000076ab00000,0x00000007bfa00000)
  from space 3072K, 17% used [0x00000007bfd00000,0x00000007bfd88000,0x00000007c0000000)
  to   space 3072K, 0% used [0x00000007bfa00000,0x00000007bfa00000,0x00000007bfd00000)
 ParOldGen       total 175104K, used 6262K [0x00000006c0000000, 0x00000006cab00000, 0x000000076ab00000)
  object space 175104K, 3% used [0x00000006c0000000,0x00000006c061db20,0x00000006cab00000)
 Metaspace       used 7942K, capacity 8164K, committed 8448K, reserved 1056768K
  class space    used 887K, capacity 944K, committed 1024K, reserved 1048576K
}
Event: 4.955 GC heap before
{Heap before GC invocations=21 (full 0):
 PSYoungGen      total 1394688K, used 1392160K [0x000000076ab00000, 0x00000007c0000000, 0x00000007c0000000)
  eden space 1391616K, 100% used [0x000000076ab00000,0x00000007bfa00000,0x00000007bfa00000)
  from space 3072K, 17% used [0x00000007bfd00000,0x00000007bfd88000,0x00000007c0000000)
  to   space 3072K, 0% used [0x00000007bfa00000,0x00000007bfa00000,0x00000007bfd00000)
 ParOldGen       total 175104K, used 6262K [0x00000006c0000000, 0x00000006cab00000, 0x000000076ab00000)
  object space 175104K, 3% used [0x00000006c0000000,0x00000006c061db20,0x00000006cab00000)
 Metaspace       used 7957K, capacity 8164K, committed 8448K, reserved 1056768K
  class space    used 887K, capacity 944K, committed 1024K, reserved 1048576K
Event: 4.957 GC heap after
Heap after GC invocations=21 (full 0):
 PSYoungGen      total 1392640K, used 608K [0x000000076ab00000, 0x00000007bff00000, 0x00000007c0000000)
  eden space 1391616K, 0% used [0x000000076ab00000,0x000000076ab00000,0x00000007bfa00000)
  from space 1024K, 59% used [0x00000007bfa00000,0x00000007bfa98000,0x00000007bfb00000)
  to   space 2560K, 0% used [0x00000007bfc80000,0x00000007bfc80000,0x00000007bff00000)
 ParOldGen       total 175104K, used 6638K [0x00000006c0000000, 0x00000006cab00000, 0x000000076ab00000)
  object space 175104K, 3% used [0x00000006c0000000,0x00000006c067bb20,0x00000006cab00000)
 Metaspace       used 7957K, capacity 8164K, committed 8448K, reserved 1056768K
  class space    used 887K, capacity 944K, committed 1024K, reserved 1048576K
}

Deoptimization events (10 events):
Event: 15.268 Thread 0x00007fae75809000 Uncommon trap: reason=unstable_if action=reinterpret pc=0x00000001104c91d4 method=com.google.gson.internal.$Gson$Types.equals(Ljava/lang/reflect/Type;Ljava/lang/reflect/Type;)Z @ 11
Event: 15.268 Thread 0x00007fae75809000 Uncommon trap: reason=bimorphic action=maybe_recompile pc=0x00000001103791bc method=java.util.HashMap.putVal(ILjava/lang/Object;Ljava/lang/Object;ZZ)Ljava/lang/Object; @ 203
Event: 15.269 Thread 0x00007fae75809000 Uncommon trap: reason=bimorphic action=maybe_recompile pc=0x00000001103791bc method=java.util.HashMap.putVal(ILjava/lang/Object;Ljava/lang/Object;ZZ)Ljava/lang/Object; @ 203
Event: 15.345 Thread 0x00007fae75809000 Uncommon trap: reason=class_check action=maybe_recompile pc=0x00000001104cd4d0 method=com.google.gson.reflect.TypeToken.<init>(Ljava/lang/reflect/Type;)V @ 9
Event: 15.346 Thread 0x00007fae75809000 Uncommon trap: reason=class_check action=maybe_recompile pc=0x00000001104c3f54 method=com.google.gson.internal.$Gson$Types.getRawType(Ljava/lang/reflect/Type;)Ljava/lang/Class; @ 44
Event: 15.348 Thread 0x00007fae75809000 Uncommon trap: reason=class_check action=maybe_recompile pc=0x0000000110515d30 method=com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(Lcom/google/gson/stream/JsonWriter;Ljava/util/Collection;)V @ 16
Event: 15.348 Thread 0x00007fae75809000 Uncommon trap: reason=null_check action=make_not_entrant pc=0x00000001105030f8 method=com.google.gson.Gson.getAdapter(Lcom/google/gson/reflect/TypeToken;)Lcom/google/gson/TypeAdapter; @ 17
Event: 15.350 Thread 0x00007fae75809000 Uncommon trap: reason=class_check action=maybe_recompile pc=0x0000000110515d30 method=com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(Lcom/google/gson/stream/JsonWriter;Ljava/util/Collection;)V @ 16
Event: 15.350 Thread 0x00007fae75809000 Uncommon trap: reason=class_check action=maybe_recompile pc=0x0000000110515d30 method=com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(Lcom/google/gson/stream/JsonWriter;Ljava/util/Collection;)V @ 16
Event: 15.351 Thread 0x00007fae75809000 Uncommon trap: reason=class_check action=maybe_recompile pc=0x0000000110515d30 method=com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(Lcom/google/gson/stream/JsonWriter;Ljava/util/Collection;)V @ 16

Classes redefined (0 events):
No events

Internal exceptions (10 events):
Event: 0.696 Thread 0x00007fae75809000 Exception <a 'java/lang/NoSuchFieldError': method resolution failed> (0x000000076be09908) thrown at [/Users/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-mac-x64-hotspot/workspace/build/src/hotspot/src/share/vm/prims/methodHandles.cpp, line 1176]
Event: 0.919 Thread 0x00007fae75809000 Exception <a 'java/lang/NoSuchMethodError': java.lang.Object.lambda$comparingInt$7b0bb60$1(Ljava/util/function/ToIntFunction;Ljava/lang/Object;Ljava/lang/Object;)I> (0x000000076e358748) thrown at [/Users/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-ma
Event: 0.924 Thread 0x00007fae75809000 Exception <a 'java/lang/NoSuchMethodError': java.lang.Object.lambda$maxBy$1(Ljava/util/Comparator;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;> (0x000000076e364778) thrown at [/Users/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-mac-x64-hots
Event: 11.103 Thread 0x00007fae75809000 Exception <a 'java/lang/ArrayIndexOutOfBoundsException'> (0x00000007926674e8) thrown at [/Users/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-mac-x64-hotspot/workspace/build/src/hotspot/src/share/vm/runtime/sharedRuntime.cpp, line 609]
Event: 11.104 Thread 0x00007fae75809000 Exception <a 'java/lang/ArrayIndexOutOfBoundsException'> (0x00000007926684b0) thrown at [/Users/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-mac-x64-hotspot/workspace/build/src/hotspot/src/share/vm/runtime/sharedRuntime.cpp, line 609]
Event: 11.104 Thread 0x00007fae75809000 Exception <a 'java/lang/ArrayIndexOutOfBoundsException'> (0x00000007926699a0) thrown at [/Users/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-mac-x64-hotspot/workspace/build/src/hotspot/src/share/vm/runtime/sharedRuntime.cpp, line 609]
Event: 11.257 Thread 0x00007fae75809000 Implicit null exception at 0x00000001104d043e to 0x00000001104d09e3
Event: 11.257 Thread 0x00007fae75809000 Exception <a 'java/lang/ArrayIndexOutOfBoundsException'> (0x00000007948441f8) thrown at [/Users/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-mac-x64-hotspot/workspace/build/src/hotspot/src/share/vm/runtime/sharedRuntime.cpp, line 609]
Event: 11.257 Thread 0x00007fae75809000 Exception <a 'java/lang/ArrayIndexOutOfBoundsException'> (0x00000007948453c8) thrown at [/Users/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-mac-x64-hotspot/workspace/build/src/hotspot/src/share/vm/runtime/sharedRuntime.cpp, line 609]
Event: 15.348 Thread 0x00007fae75809000 Implicit null exception at 0x0000000110500f9d to 0x00000001105030db

Events (10 events):
Event: 15.348 Thread 0x00007fae75809000 DEOPT UNPACKING pc=0x000000010ffbc47a sp=0x000000030d730210 mode 2
Event: 15.350 Thread 0x00007fae75809000 Uncommon trap: trap_request=0xffffffde fr.pc=0x0000000110515d30
Event: 15.350 Thread 0x00007fae75809000 DEOPT PACKING pc=0x0000000110515d30 sp=0x000000030d7302a0
Event: 15.350 Thread 0x00007fae75809000 DEOPT UNPACKING pc=0x000000010ffbc47a sp=0x000000030d730340 mode 2
Event: 15.350 Thread 0x00007fae75809000 Uncommon trap: trap_request=0xffffffde fr.pc=0x0000000110515d30
Event: 15.350 Thread 0x00007fae75809000 DEOPT PACKING pc=0x0000000110515d30 sp=0x000000030d7302a0
Event: 15.351 Thread 0x00007fae75809000 DEOPT UNPACKING pc=0x000000010ffbc47a sp=0x000000030d730340 mode 2
Event: 15.351 Thread 0x00007fae75809000 Uncommon trap: trap_request=0xffffffde fr.pc=0x0000000110515d30
Event: 15.351 Thread 0x00007fae75809000 DEOPT PACKING pc=0x0000000110515d30 sp=0x000000030d7302a0
Event: 15.351 Thread 0x00007fae75809000 DEOPT UNPACKING pc=0x000000010ffbc47a sp=0x000000030d730340 mode 2


I know that is pretty long, but i hope that can help.
