### ISSUE TITLE
Time to use `build` from `setuptools` instead of `distutils`?

### ISSUE THREAD

**Issue by abravalheri** [ninia/jep#530]
The following feature in setuptools has been deprecated for almost 2 years and is about to be removed:

https://github.com/pypa/setuptools/blob/1ed759173983656734c3606e9c97a348895e5e0c/setuptools/command/build.py#L13-L27

It might be a good idea to import `build` directly from setuptools for the following code:

https://github.com/ninia/jep/blob/dd2bf345392b1b66fd6c9aeb12c234a557690ba1/commands/__init__.py#L2

(`build` is available directly from setuptools, starting on version v62.4.0)

**Comment by bsteffensmeier** [comment]
Thanks for letting us know. I have updated the code to use the new `build` from setuptools in 0be8c74fec852c08e56961c7f71d07034a3697ab which will be included in the next Jep release(4.2.1)

**Comment by abravalheri** [comment]
Thank you!
