### ISSUE TITLE
Changes to script not reflected in subsequent SharedInterpreter Invoke

### ISSUE THREAD

**Issue by bking-encodia** [ninia/jep#547]
Spring boot application with REST API, calling the REST API uses Jep to invoke function in script. Using SharedInterpreter.

Simplified example that demonstrates the problem:

python script: my_logic.py
`def do_something(): `
`     print("Do something")`

Java code in REST Controller:
`pyInterpreter = new SharedInterpreter();`
`pyInterpreter.exec("import my_logic");`
`pyInterpreter.invoke("my_logic.do_something")`

When I call the REST API, the python script is correctly invoked, I see "Do something" in the console

However if I change my_logic.py to: (Spring boot server still running)
`def do_something(): `
`     print("Do another thing")`

When I call the REST API again, I still see "Do Something" in the console, not my change to the script

My use case is when I change the python script on disk, I need that change to be reflected in the next invocation
How to achieve this? Thanks

**Environment (please complete the following information):**
- Mac/Windows
- Python 3.11
- Java 17
- Jep Version: 4.2.0

**Comment by bsteffensmeier** [comment]
This looks like a duplicate of #492. Please use `importlib.reload` to reload imported modules.

**Comment by bking-encodia** [comment]
@bsteffensmeier Thank you, this method works perfectly
