### ISSUE TITLE
ndarray conversion fails after updating jep, scipy, numpy

### ISSUE THREAD

**Issue by jovrstra** [ninia/jep#560]
Hello,

I recently needed to update some packages (pdfo and then numpy and scipy) and also updated jep to version 4.2.0 (not sure what the previous version was, but it was at least a year old. Since then, I cannot seem to import ndarrays to java.
The line in Java that used to work was:
`	    NDArray<double[]> resultVector = (NDArray<double[]>) jep.getValue("get_result_x()"); `
But now this throws a 
`Exception in thread "main" java.lang.ClassCastException: class [D cannot be cast to class jep.NDArray ([D is in module java.base of loader 'bootstrap'; jep.NDArray is in unnamed module of loader 'app')
	at ds.python.PythonSciPy.test(PythonSciPy.java:119)
	... `

The above get_result_x is a getter applied on a SciPy OptimimizeResult to return the x:
https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.OptimizeResult.html#scipy.optimize.OptimizeResult
Jep is a new SharedInterpreter().

No changes were made to the Java code, I just updated the above packages and changed the referenced jar file to use jep-4.2.0.jar. It worked just prior to these updates.

Can anyone help?

**Comment by jovrstra** [comment]
Could it be that Jep 4.2.0 was not built with numpy support? How to get a numpy supported version?

**Comment by bsteffensmeier** [comment]
> Could it be that Jep 4.2.0 was not built with numpy support? How to get a numpy supported version?

That is likely the cause. Jep will automatically include numpy support if numpy is present when you build jep so you need to install numpy before jep. You can check if numpy support is enabled by doing something like `interpreter.exec("print(jep.JEP_NUMPY_ENABLED)");`. If you are using pip to install jep and you want to rebuild after installing numpy you may need to use the `--no-cache-dir` option for pip or it will reuse your existing jep build without numpy support.

**Comment by jovrstra** [comment]
Numpy support is not enabled (the above command prints 0), so that is the issue.
I have a problem getting it to work though. I removed Jep from (pip uninstall jep), cleared the cache (py -m pip cache purge), downloaded the jep-sources, and ran pip install . --no-cache-dir. Numpy 1.26.4 is installed.
It seems to work:
```
Processing c:\users\...\jep-4.2.0.tar\jep-4.2.0\jep-4.2.0
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: jep
  Building wheel for jep (pyproject.toml) ... done
  Created wheel for jep: filename=jep-4.2.0-cp310-cp310-win_amd64.whl size=357425 sha256=8f52d839e3a43c1dfc22036cc591f6c571ba384f864dbc8fc1dd15b45424b5f8
  Stored in directory: C:\Users\jorg.verstraete\AppData\Local\Temp\pip-ephem-wheel-cache-enes7qra\wheels\92\02\87\e7b17261aa61b4cb677adab9e7b58990f7f49a1d764657e07c
Successfully built jep
Installing collected packages: jep
Successfully installed jep-4.2.0
```
I've updated the Java project with the correct jar file for jep but my Java program behaves the same: it still shows that numpy support is not enabled.
How to build this?

**Comment by jovrstra** [comment]
I managed to build using numpy 1.26.4, and using " python setup.py build" and "python setup.py install". For some reason, when ran from pip, the test for the installation of numpy fails.
I don't know if it would work with numpy 2.1.1, as the include files are not in core\include but in _core\include\numpy (I have the impression that the path in the setup script looks for them in core\include.

**Comment by jovrstra** [comment]
Reopening the issue as installing via python rather than pip will be deprecated, so the issue of building with numpy will be an issue.
DEPRECATION: Loading egg at c:\program files\python312\lib\site-packages\jep-4.2.0-py3.12-win-amd64.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330

**Comment by ndjensen** [comment]
Thanks for sharing what you found.  We had not tried building Jep with numpy 2 yet.  @bsteffensmeier opened pull request #562 to get the build to properly detect numpy 2.

**Comment by jovrstra** [comment]
No problem. I hope it helps. Weird thing is that with numpy 1.26.4 (with the include files in the expected locations), pip install . fails to detect numpy, but python setup.py build works.
(I think we can now safely close this thread :-))
