### ISSUE TITLE
JSONObject in java can not use get method with default value

### ISSUE THREAD

**Issue by githubbbbber** [ninia/jep#567]
**Describe the bug**
I pass a JSONObject in java to python env, but I can't use this_json_object.get("key1", [[]]). 
the json object is like {"key1":[[{"innerKey":"innerValue"}]]}
I can use getattr(this_json_object, 'get')("key1", [[]]) or this_json_object.get("key1") to get the value

**Environment (please complete the following information):**
- OS Platform, Distribution, and Version: linux OS
- Python Distribution and Version: 3.11
- Java Distribution and Version: 11
- Jep Version: 4.20

**Comment by bsteffensmeier** [comment]
Which package is JSONObject in. Can you link the source or javadoc for JSONObject? What error do you get when you use this_json_object.get("key1", [[]])?

**Comment by githubbbbber** [comment]
> Which package is JSONObject in. Can you link the source or javadoc for JSONObject? What error do you get when you use this_json_object.get("key1", [[]])?

error is like   
```
jep.JepException: : Invalid number of arguments: 3, expected 2. 
```
when I use this_json_object.get("key1", [[]]).
if I changed to this_json_object.get("key1"), it worked.
My json package is fastjson in java env, but I'm not sure if it has an influence on that result.

**Comment by bsteffensmeier** [comment]
The [fastjson JSONObject get() method](https://www.javadoc.io/doc/com.alibaba/fastjson/1.2.39/com/alibaba/fastjson/JSONObject.html#get-java.lang.Object-) takes only one argument and you are giving it two arguments. The exception seems appropriate to me.

**Comment by githubbbbber** [comment]
> The [fastjson JSONObject get() method](https://www.javadoc.io/doc/com.alibaba/fastjson/1.2.39/com/alibaba/fastjson/JSONObject.html#get-java.lang.Object-) takes only one argument and you are giving it two arguments. The exception seems appropriate to me.

I don't understand that "this_json_object.get("key1", [[]])" is a python statement. Actually it invoked the fastjson JSONObject get() method?

**Comment by bsteffensmeier** [comment]
> I don't understand that "this_json_object.get("key1", [[]])" is a python statement. Actually it invoked the fastjson JSONObject get() method?

Yes. Jep exposes java objects and their methods in python. For some of the basic builtin types we offer some enhancements and conversions to python types but for most objects and especially 3rd party libraries jep will just allow calling java methods from python.

**Comment by githubbbbber** [comment]
> > I don't understand that "this_json_object.get("key1", [[]])" is a python statement. Actually it invoked the fastjson JSONObject get() method?
> 
> Yes. Jep exposes java objects and their methods in python. For some of the basic builtin types we offer some enhancements and conversions to python types but for most objects and especially 3rd party libraries jep will just allow calling java methods from python.

I get it. Thank you very much.
