### ISSUE TITLE
Putting all python dependencies in jar

### ISSUE THREAD

**Issue by gavrmike** [ninia/jep#89]
Hi! 

I would like to put all python dependencies including python and python`s libraries into jar.
Because i could not install python on machine.

How can i do this? Is it possible?

**Comment by ndjensen** [comment]
Presuming I understand what you're asking,

We've thought about including the site-packages/jep folder in the jar about but don't currently support it.  If you submitted a pull request with a working change it'd get done faster.

An alternative is to use PYTHONPATH to tell Python where to look for the jep folder with the Python modules.  That way jep doesn't have to be installed in the same location as Python.

**Comment by gavrmike** [comment]
Yes, you correct understand that i want to include some python packages in jar (for example: site-packages/jep, site-packages/numpy).

**Comment by ndjensen** [comment]
That's not really Jep's problem to solve.  You can make your own jar with the `jar` command and then you can use Python's `zipimport` module or Java's `JarFile` class to extract or read entries from the jar.
