### ISSUE TITLE
3.7 gives class not found error

### ISSUE THREAD

**Issue by tcederquist** [ninia/jep#91]
- OS Platform, Distribution, and Version:
  - Centos 7
- Python Distribution and Version:
  - 3.6.2-1
- Java Distribution and Version:
  - 3.8.0_141-b16

When built in Docker (which works great if I install with pip3.6 install jep==3.6.4). When pulling the 3.7 release a new error is thrown from Java trying to start jep:

     lang:Exception in thread "Thread-9"
      lang:java.lang.NoClassDefFoundError: jep/DirectNDArray
        at jep.Jep.init(Native Method)
        at jep.Jep.<init>(Jep.java:374)
        at com.erm.rest.language.cpython.api.ECPython.run(ECPython.java:56)
      lang:Caused by: java.lang.ClassNotFoundException: jep.DirectNDArray
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

Starting with this script:

     #!/bin/bash
     export JAVA_HOME=/usr/lib/jvm/java
     export LD_PRELOAD="/usr/lib64/libpython3.6m.so"
     export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib64/python3.6/site-packages/jep:/usr/lib64/python3.6/config-3.6m-x86_64-linux-gnu:/usr/lib64/python3.6/lib-dynload
     cd /usr/share/llf
     java -Duser.dir=/usr/share/llf -jar myLogicRestService.jar $1 -Dorg.apache.commons.logging.diagnostics.dest=STDOUT

**Comment by bsteffensmeier** [comment]
You must have an old version of the jep jar on your class path. DirectNDArray is a new class in 3.7 but it is package in the same jar as Jep.class. Since the stack trace includes Jep, you must've found Jep.class, so you have a Jep.jar on your class path but it is likely the wrong version.

**Comment by bsteffensmeier** [comment]
The line numbers in the stack trace confirm that the java classes are from jep 3.60 or 3.6.1 while the native code from 3.7. This is a problem with the installed environment, not jep so I am closing this.
