### ISSUE TITLE
Jep is listed as a yes and a no.  This is confusing.

### ISSUE THREAD

**Issue by daidoji** [ninia/jep#97]
In the FAQ under the section going

> Java
>Do you need to use CPython modules (e.g. numpy)?
>Yes: Jep is a good fit for you. Alternatives are jpy and JyNI.
>No: Consider Jep, jpy, or Jython.

Is Jep a good and not good fit?  This is confusing.

**Comment by ndjensen** [comment]
I've updated the wording.
